### ISSUE TITLE
[Bug]: Improve output for non-taquified project

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#1033]
### What happened?

For not taquified project the output of any command is

taq [command]

Commands:
  taq init [projectDir]                     Initialize a new project
  taq opt-in                                Opt-in to sharing anonymous usage analytics
  taq opt-out                               Opt-out of sharing anonymous usage analytics
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold

Options:
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]
  -p, --projectDir  Path to your project directory               [default: "./"]
  -e, --env         Specify an environment configuration

Taqueria is currently in BETA. You've been warned. :)

Your config.json file is invalid

That has a lot of additional information and also does not correct info that project was not taquified

### What should have happened?

It would be nice to have one line output if config.json does not exists at all to tell user:
"Project is not taquifed!" 

### Steps to reproduce the bug

1. Install taqueria
2. Create a test folder on your machine
3. Run taq install without running taq init

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zamrokk** [comment]
Please add a verbose mode to debug what is going on

**Comment by hu3man** [comment]
@zamrokk, there are two dev flags you can try out in the meantime:

- `--logPluginRequests`
- `--debug`

**Comment by zamrokk** [comment]
I did some config cleaning and use the vscode plugin, now the state seems
to be ok. I can do all actions
Don't know what happened

Ben

**Comment by hu3man** [comment]
Thanks for the update @zamrokk! Will close this out for now
