### ISSUE TITLE
[Bug]: No README.md file in the jest plugin directory

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#1039]
### What happened?

I was looking in the jest plugin directory for a README.md to see what it is all about and could not find one

### What should have happened?

I should have found a README.md file in the jest plugin directory

### Steps to reproduce the bug

Steps to reproduce the error:
1. Go to the jest plugin directory in the taqueria repo

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Putting in stasis for now
