### ISSUE TITLE
[Bug]: CORS issue trying to connect to sandbox via Temple

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#1046]
### What happened?

When trying to connect to sandbox via Temple getting an issue with CORS
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:20000/chains/main/chain_id. (Reason: CORS header 'Access-Control-Allow-Origin' missing). Status code: 200.`

### What should have happened?

There should be no errors trying to connect to sandbox from any application because environment variable should be set up to *

### Steps to reproduce the bug

Steps to reproduce the error:

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Qwiddle** [comment]
Thanks for filing this report @sinapsist!

Steps to reproduce the error:
1. Initialize new taqueria project (`taq init new-project`)
2. Install flextesa plugin (`taq install @taqueria/plugin-flextesa`)
3. Start local sandbox (`taq start sandbox local`)
4. Attempt to add custom RPC within Temple (`http://localhost:20000`)

Device/wallet specifics:
- Windows & WSL (followed https://taqueria.io/docs/getting-started/installation/)
- Temple Wallet
- Firefox

**Comment by sinapsist** [comment]
It is only applicable for Firefox, Chrome works fine.

**Comment by mweichert** [comment]
This seems to be an issue yet with Taqueria v0.18.
