### ISSUE TITLE
Track Taqueria GitHub Action usage using GA

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#1051]
Add the ability to track GitHub Action utilization using the current Google Analytics usage tracking.

- [ ] Do not track internal CI/CD usage
- [ ] Report to current usage analytics tracking ID
- [ ] Consent will default to yes
- [ ] Details of analytics being on by default added to Taqueria Action readme with details of how to opt-out

**Comment by russellmorton** [comment]
@jchenche we can go ahead with this.

**Comment by hu3man** [comment]
Moving to PB: https://ecadlabs.productboard.com/feature-board/5219572-taqueria-features
