### ISSUE TITLE
[Bug]: Improve error message for issue when docker is not started

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#1053]
### What happened?

When docker is not started taqueria displayed a message with a lot of underlying details.
This message does not include information that docker has not been started on the machine.

```
Booting sandbox...
Error: Command failed: sh -c "docker run --name taqueria-development-local-311ac65b730fc796441e898449c012c1c956619b9129d3fd3f3d24931f779e7c --rm --detach --platform linux/arm64/v8 -p 20000:20000 -v /Users/ivanromanov/workspace/taqueria-test-projects/taq-cors-test:/project -w /app ghcr.io/ecadlabs/taqueria-flextesa:dev-feature-metadata-plugin-7e150408 node index.js --sandbox local"
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 125,
  killed: false,
  signal: null,
  cmd: 'sh -c "docker run --name taqueria-development-local-311ac65b730fc796441e898449c012c1c956619b9129d3fd3f3d24931f779e7c --rm --detach --platform linux/arm64/v8 -p 20000:20000 -v /Users/ivanromanov/workspace/taqueria-test-projects/taq-cors-test:/project -w /app ghcr.io/ecadlabs/taqueria-flextesa:dev-feature-metadata-plugin-7e150408 node index.js --sandbox local"'
}
```

### What should have happened?

It would be better to see some user-friendly message e. g. "Check that your docker is running"

### Steps to reproduce the bug

1. Create taquified project
2. Install flextesa plugin
3. Verity that docker is not running
4. Run taq start sandbox command
5. Observe results.

### Screenshots and images

Screenshot and images
<img width="847" alt="image" src="https://user-images.githubusercontent.com/10706087/181598531-6af2c04a-b5b6-457c-8201-ef9dcfee07ea.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Deprioritized
