### ISSUE TITLE
[Bug]: Automated tests running `taq init` are not initializing the project as a NPM project since `npm init -y` isn't getting run

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#1057]
### What happened?

When running tests through jest/in an automated fashion it isn't initializing the project as a NPM project and allowing for plugins to be installed

### What should have happened?

When we run the command `taq init` as a regular person or if a machine does it it should have the same outcome

### Steps to reproduce the bug

Steps to reproduce the error:
1. Create a test file called temp.spec.ts in the `taqueria/tests/e2e` directory and insert the following test code:
```
import { exec as exec1 } from 'child_process';
import util from 'util';
import fsPromises from 'fs/promises';
const exec = util.promisify(exec1);

const taqueriaProjectPath = 'e2e/init_POC';

describe('E2E Testing for taqueria project initialization', () => {
	test('initialize project', async () => {
        await exec(`taq init ${taqueriaProjectPath}`);
        const projectContents = await exec(`ls -al ${taqueriaProjectPath}`);
        console.log(projectContents)
        fsPromises.rm(taqueriaProjectPath, { recursive: true });

        expect(projectContents.stdout).toContain("package.json");
	});
})
```
2. Run the test from the taqueria repo root with the following command: `npm run test:e2e -w tests temp.spec.ts` 
3. The output should include `package.json` if it initializes the project as a NPM project successfully

### Relevant log output

```shell
When checking the output of the above test this is what is output:

    drwxrwxr-x 5 alexander alexander  4096 Jul 28 23:16 .
    drwxrwxr-x 5 alexander alexander  4096 Jul 28 23:16 ..
    drwxrwxr-x 2 alexander alexander  4096 Jul 28 23:16 artifacts
    drwxrwxr-x 2 alexander alexander  4096 Jul 28 23:16 contracts
    -rw-rw-r-- 1 alexander alexander 12613 Jul 28 23:16 quickstart.md
    drwxrwxr-x 2 alexander alexander  4096 Jul 28 23:16 .taq
```

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sinapsist** [comment]
Duplicate with https://github.com/ecadlabs/taqueria/issues/939
