### ISSUE TITLE
Install Taqueria from VS Code Extension

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#106]
As a Taqueria VS Code extension user I want to install the Taqueria application from the extension so that I do not have to separately install Taqueria for the VS Code extension to work.

**Acceptance Criteria**
- [x] User adds extension to VS Code, extension interrogates whether Taqueria is installed
- [x] If not installed prompt user to install Taqueria
- [ ] Install Taqueria

**Comment by AlirezaHaghshenas** [comment]
@russellmorton The first two items of this issue are now implemented.
Should we plan the third one? It might need platform-specific implementation, and in general is not a few hour task.

**Comment by MichalLytek** [comment]
@hu3man is the auto install taq binary feature cancelled?
