### ISSUE TITLE
Check TVsCE dependencies and enable user to take action

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1072]
- [x] Check `taq` version
- [x] NPM version
- [x] Node version
- [ ] docker version
- [ ] TVsCE version (we can check the latest version from VsCode extensions' marketplace)
- [ ] compare all versions against a minimum required version
- [ ] inform the user and provide links to update (at least for Taqueria)

**Comment by hu3man** [comment]
@AlirezaHaghshenas, what's the status of this and is it an Epic?

**Comment by AlirezaHaghshenas** [comment]
Sorry to reply late @hu3man 

Because of a comment from @jevonearth, we decided to only check the things that `taq` cannot check: `node` and `taq`.

For the rest of dependencies, we wait for a health check implementation in the CLI, then invoke that.

Does this sound good to you?
If so, I guess #106 is the part that allows the user to handle a missing/outdated `taq`. For node, I can add a link.
