### ISSUE TITLE
Remove commands that focus specific treeviews

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1086]

**Comment by AlirezaHaghshenas** [comment]
According to Eric Amodio (CTO @ GitKraken. Creator of GitLens, RemoteHub, Find Related Files, Restore Editors, etc. Prev VS Code dev @ Microsoft):

> I don't think there is a way to hide them

@russellmorton

**Comment by russellmorton** [comment]
Closing, not currently possible.
