### ISSUE TITLE
With the scaffold "Demo", the sandbox's container name does not follow the convention

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1089]
For this reason, the TVsCE cannot detect the sandbox as running

**Comment by russellmorton** [comment]
What needs to be updated on this?

**Comment by AlirezaHaghshenas** [comment]
@mweichert @jevonearth The `pacjage-lock.json` has:

```json
    "node_modules/@taqueria/plugin-flextesa": {
      "version": "0.6.5",
      "resolved": "https://registry.npmjs.org/@taqueria/plugin-flextesa/-/plugin-flextesa-0.6.5.tgz",
      "integrity": "sha512-Fxr2b9JPVENO+QSiZy27iaEPIoe+8yKaDpybTeJh0Lgx39K7g+LmWmGfAC6k1EEvw1s7Me/XBCbhRzXNaeovkA==",
      "dev": true,
      "dependencies": {
        "@taqueria/node-sdk": "^0.6.2",
        "async-retry": "^1.3.3",
        "fast-glob": "^3.2.11"
      }
    },
```

Now the most recent version of the same package is `0.12.0`. This version mismatch between the taq CLI, TVsCE, and the plugin can cause more problems in the future.

This is while in `package.json`:

```json
  "devDependencies": {
    "@taqueria/plugin-contract-types": "latest",
    "@taqueria/plugin-flextesa": "latest",
    "@taqueria/plugin-ligo": "latest",
    "@taqueria/plugin-taquito": "latest",
    "@taqueria/plugin-tezos-client": "latest"
  },
```

Should we remove `package-lock.json` from scaffolds?

While there is a chance that new version of plugins break a scaffold, in my opinion, version pinning can cause much more complex issues.

**Comment by AlirezaHaghshenas** [comment]
> I am a fan of removing `package-lock.json`, but I know @mweichert doesn't like that approach
> 
> We refactored to use `@latest` rather than pinning to reduce the maintenance burden however we often need to make other updates to scaffolds upon release, so it may be better for stability to go back to that approach

Agree `package-lock.json` provides a lot of benefits for reproducible builds to projects that use CI/CD.
For our scaffolds, I believe it causes more harm than heal.

**Comment by hu3man** [comment]
@mweichert, pinging you again here

**Comment by sinapsist** [comment]
https://taqueria.io/docs/scaffolds/scaffold-basics/
The list of scaffold projects is here, except quickstart - it will be removed.
