### ISSUE TITLE
Visualise the relevant state of Sandbox in TVsCE

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1103]
- [ ] A less general and more specialised GUI than what indexers like TzKt provide
- [ ] Implicit Accounts
- [ ] Originated Accounts
- [ ] Operations of accounts (Hash + A summary, like: "Bob sent 10 Tz to Alice")
- [ ] See entrypoints and ability to invoke them (GUI to set parameters)
- [ ] For non-local operations, link to a public indexer
- [ ] After sandbox baking is implemented, insight into that (like the current block level)

**Comment by hu3man** [comment]
Is this a duplicate ticket to #1120 @AlirezaHaghshenas ?

**Comment by AlirezaHaghshenas** [comment]
This was the epic that #1120 was part of. That one is just the first step.

**Comment by hu3man** [comment]
Closing: handling in #1160
