### ISSUE TITLE
[Bug]: missing script start in taco-shop scaffold

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#1112]
https://github.com/ecadlabs/taqueria-scaffold-taco-shop/issues/6

**Comment by alexzbusko** [comment]
@hu3man I think this might just be a case of user error for this issue. I was just looking at the taco-shop readme and the `npm run start` script exists in the `app` directory. In the later parts of the readme it's mentioned that this is the command to use to start the dApp

**Comment by hu3man** [comment]
Really appreciate you looking into this @alexzbusko! 

I think I was also reading this ticket wrong 😅. Manually starting the project is the intended behaviour

Closing!
