### ISSUE TITLE
Detection of taq binary and node can be flaky on Win+WSL in some conditions

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1118]
Reported by @alexzbusko 

I was unable to reproduce this. More information:

- On Alex's computer, when he renames his taq binaries, TVsCE still finds the taq binary, but when running a command, the command fails complaining that taq was not found. So there should be two different mechanisms for finding taq and running commands. Consistency here can help
- He uses nvm inside WSL. When changing node version, to an old version, the check still passes.

**Comment by hu3man** [comment]
This doesn't warrant further investigation at this time
