### ISSUE TITLE
[Bug]: generating types from a contract with unique method is failing

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#1128]
### What happened?

In michelson, when a contract as a unique entrypoint, we need to use "default" method.

When taqueria plugin generates the *.types.ts file , the type "Methods" is empty

```typescript
import { ContractAbstractionFromContractType, WalletContractAbstractionFromContractType } from './type-utils';
import { address } from './type-aliases';

type Storage = Array<address>;

type Methods = {
    
};

type MethodsObject = {
    
};

type contractTypes = { methods: Methods, methodsObject: MethodsObject, storage: Storage, code: { __type: 'PokeGameCode', protocol: string, code: object[] } };
export type PokeGameContractType = ContractAbstractionFromContractType<contractTypes>;
export type PokeGameWalletType = WalletContractAbstractionFromContractType<contractTypes>;
```

I expect to have "default" method here

In my previous code, this below was working

![image](https://user-images.githubusercontent.com/2536368/185161269-03a20632-188e-4475-8f82-49a814590aae.png)

### What should have happened?

when there is a unique function, "default" method should be created

### Steps to reproduce the bug

create a smartcontract with unique entrypoint
generate the types
try to see if default method is created

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@mweichert, please review

**Comment by ricklove** [comment]
Checking on this now - It seems this was handled previously...

**Comment by ricklove** [comment]
It appears this is working as expected. I added a test here to verify it: https://github.com/ecadlabs/taqueria/pull/1142

**Comment by zamrokk** [comment]
{ parameter unit ;
  storage (set address) ;
  code { CDR ; SOURCE ; PUSH bool True ; SWAP ; UPDATE ; NIL operation ; PAIR } }

**Comment by zamrokk** [comment]
Bug is still on v0.18

**Comment by zamrokk** [comment]
^ @ricklove

**Comment by ricklove** [comment]
Thanks for the example @zamrokk I'll take a look

**Comment by michaelkernaghan** [comment]
This bug still exists and is still something that requires an extra step, and the existence of the bug, for demos.

**Comment by hu3man** [comment]
@ricklove, do you have any additional details on this?

**Comment by ricklove** [comment]
No additional info, but will need to add the example above in the tests

**Comment by zamrokk** [comment]
Yep, I thought it was easy to resolve. I confirm it is still present on last release

**Comment by hu3man** [comment]
@zamrokk, is this issue still present?

**Comment by zamrokk** [comment]
Still here on v0.28

![image](https://user-images.githubusercontent.com/2536368/220865409-11766693-708c-4f2e-b769-295544265ea1.png)

**Comment by mweichert** [comment]
Fixed in v0.28.6.

**Comment by zamrokk** [comment]
o.O

I have upgraded to taq&plugin v0.28.6

Still same generated file

`
import { ContractAbstractionFromContractType, WalletContractAbstractionFromContractType } from './type-utils';
import { address } from './type-aliases';

export type Storage = Array<address>;

type Methods = {
    
};

type MethodsObject = {
    
};

type contractTypes = { methods: Methods, methodsObject: MethodsObject, storage: Storage, code: { __type: 'PokeGameCode', protocol: string, code: object[] } };
export type PokeGameContractType = ContractAbstractionFromContractType<contractTypes>;
export type PokeGameWalletType = WalletContractAbstractionFromContractType<contractTypes>;
`


What I run :
```

taq generate types ./app/src
generateTypes { typescriptDir: './app/src' }
Generating Types: /home/zamrokk/training-dapp-1/solution/artifacts => /home/zamrokk/training-dapp-1/solution/app/src
Contracts Found: 
        - /home/zamrokk/training-dapp-1/solution/artifacts/pokeGame.tz
Processing /pokeGame.tz...
Unknown method: unit {
  node: { prim: 'unit', [Symbol(source_reference)]: { first: 12, last: 16 } },
  args: undefined
}
pokeGame.tz: Types generated
```


From dapp-1 tutorial (https://github.com/marigold-dev/training-dapp-1)

**Comment by zamrokk** [comment]
Maybe is because we don't have one 1 entrypoint, but here also the parameter is of type unit. 
Maybe is what the logs is showing and it is not covered by the code :/

**Comment by zamrokk** [comment]
@mweichert  ^

**Comment by zamrokk** [comment]
@ricklove  ^
