### ISSUE TITLE
[dev-task]: Add ligo run dry-run to ligo plugin

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#1129]
### Describe the feature you would like

it is not possible today to run a dry-run with ligo plugin

### Is this feature solving a problem?

debugging quickly a ligo smart contract with no infrastructure

### Please share any additional details you have?

I would like to have a new command : 

```
taq dry-run pokeGame.jsligo 'Poke()' 'Set.empty as set<address>' 
```

usage : taq dry-run <source_file> <entrypoint> <initial_storage>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zamrokk** [comment]
is "taq simulate"  a bit close to "ligo dry-run" in a way  ?

**Comment by hu3man** [comment]
@jchenche, can you please have a look and see how much work this would be?

**Comment by jchenche** [comment]
@zamrokk yep simulate is basically `tezos-client run` which is pretty similar to `ligo dry-run` I believe

**Comment by hu3man** [comment]
@jchenche, let's do this as part of the compiler improvement work

**Comment by hu3man** [comment]
Handling in #1161
