### ISSUE TITLE
[Feature]: list-accounts task should also return users from a real testnet

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#1130]
### Describe the feature you would like

today taq list accounts only works for the flextesa sandbox, I would like to list my users if I use a real testnet
For example, if the tezos-client plugin is installed, then it is possible to list all user local aliases

### Is this feature solving a problem?

not possible to check if some user exist on a real testnet, not flextesa

### Please share any additional details you have?

taq list accounts -n "jakartanet"            //should return known user alias with its balances         (i.e   --network)
taq list accounts -s "local"                     // still return the users from flextesa                    (i.e    --sandbox)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@mweichert, will discuss this ticket later this week but wanted you to have a look and think first

**Comment by hu3man** [comment]
Pulling this feature request into Productboard for long-term planning
