### ISSUE TITLE
🚧 Dev ➾ Be able to do a simple Tezos transfer

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#1131]
### Describe the feature you would like

we have the tezos CLI but not the command "transfer"

### Is this feature solving a problem?

not possible to interact to a smart contract after a deployment to fast check that an endpoint is reached 

### Please share any additional details you have?

taq transfer <QUANTITY> from <USER> to <CONTRACT> -e <ENVIRONMENT> 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Thanks for reporting, we'll prioritize this one

**Comment by hu3man** [comment]
@jchenche, please estimate this one

**Comment by hu3man** [comment]
@zamrokk, are there any other tezos-client commands you would like to see in Taqueria?

**Comment by zamrokk** [comment]
Not at the moment

Thanks

**Comment by hu3man** [comment]
This will be implemented in #1137. Thanks for the request @zamrokk!
