### ISSUE TITLE
🐛 Bug ➾ `taq pin` commands returning "command failed" instead of outputting to stderr when running automated tests

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#1188]
### 🆘 What happened?

When running automated tests for the pin functionality instead of returning the errors on stderr the commands will just fail and cause the test to exit. This is bad news for testability since the right thing is happening but the return code is causing the tests to fail or something like that. The `publish` command does this so I am just wondering what is different about the `pin` command

Steps to reproduce:
1. Checkout the branch `feature-ipfs-pinata-tests`
2. Build all the required stuff with `npm run build-all`
3. Run the tests existing from the repo root with pinning functionality with `npm run test:e2e -w tests taqueria-plugin-ipfs-pinata.spec.ts`

Expected outcome:
The tests correctly assert based on stderr when a problem occurs

Actual outcome:
The tests exit with "command failed" when trying to run a pin command

### 🪵 Relevant log output

```shell
$ npm run test:e2e -w tests taqueria-plugin-ipfs-pinata.spec.ts

> @taqueria/tests@0.12.0 test:e2e
> TEST=true jest --config jest.config.e2e.ts "taqueria-plugin-ipfs-pinata.spec.ts"

 FAIL  e2e/taqueria-plugin-ipfs-pinata.spec.ts (30.068 s)
  e2e testing for the IPFS Pinata plugin with no JWT
    ✓ ipfs pinata plugin should show the correct help contents (519 ms)
    ✓ ipfs pinata plugin should show the correct help contents for publish (549 ms)
    ✓ ipfs pinata plugin should show the correct help contents for pin (554 ms)
    ✓ ipfs pinata plugin should warn for publish if no env jwt token exists (898 ms)
    ✕ ipfs pinata plugin should warn for pin if no env jwt token exists (991 ms)
  E2E Testing for the taqueria ipfs pinata plugin
    ✓ ipfs pinata plugin should warn if no file specified for publish (1113 ms)
    ✕ ipfs pinata plugin should warn if no filehash specified for pin (1144 ms)
    ✓ publish a single file to ipfs and get back the expected cid (1696 ms)
    ✓ publish a directory to ipfs and get back the expected cid for each file (1964 ms)
    ✓ pin using an ipfs hash (1393 ms)

  ● e2e testing for the IPFS Pinata plugin with no JWT › ipfs pinata plugin should warn for pin if no env jwt token exists

    Command failed: taq pin QmZcEXgfE9K4zFVkTrqW5x4skvEqpNajZzvb7frrWnkQa5
    The 'credentials.pinataJwtToken' was not found in config



  ● E2E Testing for the taqueria ipfs pinata plugin › ipfs pinata plugin should warn if no filehash specified for pin

    Command failed: taq pin
    ipfs hash was not provided



Test Suites: 1 failed, 1 total
Tests:       2 failed, 8 passed, 10 total
Snapshots:   0 total
Time:        30.228 s
Ran all test suites matching /taqueria-plugin-ipfs-pinata.spec.ts/i.
npm ERR! Lifecycle script `test:e2e` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @taqueria/tests@0.12.0 
npm ERR!   at location: /home/alexander/taqueria/tests
```

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

Every time

### 💻 Operating System

Linux

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

dev-893-ipfs-pinata-pin-task

### 🌿 Node.js Version

v16.16.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Hey @ricklove, hoping you can have a quick look at this when you're available

**Comment by michaelkernaghan** [comment]
no longer reproducible
