### ISSUE TITLE
🐛 Bug ➾ Metadata plugin returns error when running `taq generate-metadata`

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1191]
### 🆘 What happened?

While testing the Metadata plugin, I ran the command `taq generate-metadata` (rather than `taq generate metadata`). This returns an error as seen below

### 🪵 Relevant log output

```shell
❯ taq generate-metadata        
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
taq [command]

Commands:
  taq init [projectDir]                     Initialize a new project
  taq opt-in                                Opt-in to sharing anonymous usage an
                                            alytics
  taq opt-out                               Opt-out of sharing anonymous usage a
                                            nalytics
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold

Options:
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]
  -p, --projectDir  Path to your project directory               [default: "./"]
  -e, --env         Specify an environment configuration

Taqueria is currently in BETA. You've been warned. :)

The @taqueria/plugin-metadata plugin experienced an error when getting information about the @taqueria/plugin-metadata plugin.
```

### ⏱️ Prevalance

Every time

### 💻 Operating System

MacOS

### 🕸️ System Architecture

arm64 (M1 Macs)

### 🌮 Taqueria Version

dev-main

### 🌿 Node.js Version

16.16.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Note, once this error occurs, the metadata plugin will not respond to `taq generate metadata`

**Comment by sinapsist** [comment]
@hu3man I cannot reproduce this bug
<img width="825" alt="image" src="https://user-images.githubusercontent.com/10706087/187444783-1d9ada70-4afd-4634-a93a-5e7bb6938f5c.png">

**Comment by hu3man** [comment]
@sinapsist , It looks like the plugin isn't installed in the screenshot above

The steps I took were:
- Checkout metadata branch
- `npm run build-all`
- `taq init iii`
- `cd iii`
- `taq install ../taqueria-plugin-metadata`
- `taq generate-project-metadata` -> follow steps to completion
- `taq generate-metadata`
