### ISSUE TITLE
🚧 Dev ➾ Update and refactor the GitHub action for the latest LIGO plugin changes

### ISSUE THREAD

**Issue by GImbrailo** [ecadlabs/taqueria#1194]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation
- [ ] 🏁 Test Plan Executed
- [ ] 🛩️ Documentation Updated
- [ ] 🏟️ Peer / User Reviewed
- [ ] 🏆 Validated and Accepted

### ✅ To Do

- [x] Update the GitHub action workflows

### 🧰 Work Description

With LIGO plugin no longer requiring contracts to be registered, the GitHub action inputs and `entrypoint.sh` file need to reflect these changes.

### ⚖️ Acceptance Criteria

✨ Features: 
- [ ] After the next final release (most likely v0.14.0) the Github action must be able to compile a contract using the filename
- [ ] The GitHub action must no longer require or expect contracts to be registered
 
 📚 Documentation: 
- [x] Update the `taqueria-github-action` repository README
- [x] Update the website documentation to reflect the same changes
 

### 🎢 Test Plan

There are test workflows and projects, and all testing is done in the `taqueria-github-action` repository

### 🎆 Release Notes

There are no release notes that need to be added other than the updates to the documentation listed above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Thanks for filing @GImbrailo!

Moving to the dev board

**Comment by hu3man** [comment]
Note: the taquito plugin also needs a filename passed to the deploy command. It may be worth exploring the optional parameter --storage (I think...) which is a path to a storage file and is required if the user is not using the new naming convention

**Comment by GImbrailo** [comment]
@hu3man this work was completed and released in `v0.6.1` of the github action

**Comment by hu3man** [comment]
Complete
