### ISSUE TITLE
🐛 Bug ➾ Taqueria has hardcoded plugin entry to index.js 

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taqueria#1201]
### 🆘 What happened?

When Taqueria loads a plugin, it always goes to `node_modules/foo-plugin/index.js`, ignoring `main`/`module` path specified in `node_modules/foo-plugin/package.json`.

I think it is hardcoded in ` getPluginExe(...)` in [plugin.ts](https://github.com/ecadlabs/taqueria/blob/505da3937b853b2ead866dfb58d0b1762d8615eb/plugins.ts#L136-L142).

### 🪵 Relevant log output

```shell
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module '/mnt/d/Downloads/taq-test/node_modules/@tezos-dappetizer/taqueria/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Thanks for reporting this @psmolinsky! 

Our team will be investigating this shortly

**Comment by hu3man** [comment]
@mweichert, thoughts on this?

**Comment by psmolinsky** [comment]
Why have you closed this bug? Can you explain please? Plugin does not work as a regular NPM module so it is a serious issue.
