### ISSUE TITLE
🐛 Bug ➾ Rapidly starting multiple sandboxes can fail because of port collision

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1203]
### 🆘 What happened?

1. Suppose we want to run multiple taq start sanndbox commands on different sandboxes (or in different projects) and their ports are all set to 20000
2. If we do them on the same time (or in very rapid sequence), the logic that tests port 20000 will succeed for all of them, because no container has started yet
3. Then they all proceed to start their containers on port 20000, and only one of them will succeed, the rest will fail.

This especially happens in CI e2e tests.  
The same thing would succeed if the start commands were separate in time by a few hundred milliseconds. For now, Ivan wants to limit the number of parallel e2e tests to 1, but this will make things super slow.

### 🐘 How impactful is this bug?

🤔 Notable but managable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sinapsist** [comment]
https://github.com/ecadlabs/taqueria/pull/1232
