### ISSUE TITLE
🚧 Dev ➾ Docusaurus Fixes from Michael K

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1208]
### 🚥 Definition of Done

- [x] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation
- [ ] 🏁 Test Plan Executed
- [ ] 🛩️ Documentation Updated
- [ ] 🏟️ Peer / User Reviewed
- [ ] 🏆 Validated and Accepted

### 🔭 Scope

🏎️ In Scope: 
- Implementing fixes mentioned
- Fixing any other issues noticed while implementing this ticket
 
 🙅‍♂️ Out of Scope: 
- ... 
 
 

### 🧰 Work Description

@michaelkernaghan  had gone through our Docusaurus docs and identified some issues that need fixing

The thread can be found here: https://ecadlabs.slack.com/archives/C021J32T05B/p1657914143071919

Please get his help to review any docs if anything get's merged while Houston is away

### ⚖️ Acceptance Criteria

 📚 Documentation: 
- [ ] Update all relevant documentation with fixes
- [ ] 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexzbusko** [comment]
Looked through thread and it looks like all the things Michael has pointed out have been fixed/are no longer valid
