### ISSUE TITLE
🚧 Dev ➾ Update Docs For Recent Changes to Dev WF

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1210]
### 🚥 Definition of Done

- [X] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation
- [ ] 🏁 Test Plan Executed
- [x] 🛩️ Documentation Updated
- [ ] 🏟️ Peer / User Reviewed
- [ ] 🏆 Validated and Accepted

### 🔭 Scope

🏎️ In Scope: 
- Updating Ligo and Taquito plugin docs
- Creating a new page under `Feature` explaining the naming system, linking behaviour, and how storage/param in Ligo works in Taqueria
- Updating quickstart
 
 🙅‍♂️ Out of Scope: 
- Thorough review of docs (Ivan will cover in manual doc review)
 
 

### ⚖️ Acceptance Criteria

 📚 Documentation: 
- [x] Taquito Plugin doc `_readme.eta` updated
- [x] Ligo Plugin doc `_readme.eta` updated
- [x] Content covering naming convention
- [x] Content covering storage definition in ligo and example of e2e use (compose, compile, deploy)
- [x] Content covering parameter definition in ligo (and use)
- [x] A new Docusaurus page under Libraries for new package
- [x] A new Docusaurus page under Features that explains aliases and shows how to get hot-reload working

### 🎢 Test Plan

Involve @sinapsist for manual testing and to make sure the rest of docs can be updated with appropriate changes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@jchenche, please update this ticket with the current status

**Comment by jchenche** [comment]
ohh this is done yeah @hu3man

**Comment by hu3man** [comment]
Awesome work on this @jchenche, had a read through and the content is great!
