### ISSUE TITLE
🐛 Bug ➾ env is set to 'development' in parsed config object implicitly

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#1223]
### 🆘 What happened?

Add `console.error(parsedArgs)` 2 lines below `export const originate = <T>(parsedArgs: Opts) => {` then run `taq deploy <filename>` and you will see this (note `  env: 'development',` below):

```javascript
{
  _: [],
  projectDir: '/Users/jimmychenchen/Desktop/dapp',
  maxConcurrency: 10,
  debug: true,
  disableState: false,
  logPluginRequests: true,
  fromVsCode: true,
  version: false,
  build: false,
  help: false,
  yes: true,
  env: 'development',
  setBuild: '48b0cda5',
  setVersion: 'dev-1200-taq-api-for-dapp-JCC',
  taqRun: 'proxy',
  config: {
    language: 'en',
    contractsDir: 'contracts',
    artifactsDir: 'artifacts',
    network: { ghostnet: [Object] },
    sandbox: { local: [Object] },
    environment: { default: 'testing', development: [Object], testing: [Object] },
    accounts: {
      bob: '3_000_000_000',
      alice: '3_000_000_000',
      john: '3_000_000_000',
      jane: '3_000_000_000',
      joe: '3_000_000_000'
    },
    plugins: [ [Object], [Object], [Object], [Object] ],
    projectDir: '/Users/jimmychenchen/Desktop/dapp',
    configFile: '/Users/jimmychenchen/Desktop/dapp/.taq/config.json',
    hash: '14cf3fe4e96f9cded87f45db91ad554aa81084a1addd2671842909636d5ebd38'
  },
  task: 'deploy',
  i18n: '{}',
  envVars: '{}',
  lock: './deno-lock.json',
  d: 'false',
  p: './',
  y: 'false',
  contract: 'hello-tacos.tz',
  '$0': 'node_modules/@taqueria/plugin-taquito/index.js'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@mweichert @ricklove, could you take a look at this?

**Comment by mweichert** [comment]
So I've taken a look at this, and we need a type, such as PluginRequestArgs, that encapsulates the config as part of the args itself, that can reflect whether an environment was provided as an argument to the CLI, or whether a default environment has been set in the config.

**Comment by mweichert** [comment]
I was working on this, but had to abandon the effort because the effort intersects too much with https://github.com/ecadlabs/taqueria/issues/1342

We have different types of SanitizedArgs depending on whether its one of the built-in tasks or one provided by a plugin.

**Comment by jchenche** [comment]
Issue stems from here:
```
env: z.union([z.literal('production'), z.literal('testing'), z.literal('development'), z.string().nonempty()])
		.default('development'),
```
