### ISSUE TITLE
🐛 Bug ➾ Taqueria is Unable to Reference a Taq'ified Project When CWD is not in the Directory that Contains `.taq`

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taqueria#1249]
### 🆘 What happened?

Run `taq` in a directory where no `.taq` or `.taq/config.json` exists.

The error message `Your config.json file is invalid` is not a good one for this situation.

Required AC:
- [ ] When it can't find the config file in path x, it should tell the user "I can't find your config file in path x"

Optional AC:
- [ ] If the user's CWD is in a subdirectory of a Taqueria project, Taqueria should be able to traverse the FS to implicitly target the correct directory

### 🌮 Taqueria Version

v0.18.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Linked to #1315

**Comment by jevonearth** [comment]
Based on standup;

@mweichert says that implementation is done, but an e2e test is failing. @michaelkernaghan and @MichalLytek will pair to get to the bottom of the failing test.

**Comment by mweichert** [comment]
E2E tests are passing and this is ready for review.
