### ISSUE TITLE
🚧 Dev ➾ Create E2E tests for transfer/call command

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#1257]
### 🚥 Definition of Done

- [X] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation
- [ ] 🏁 Test Plan Executed
- [ ] 🛩️ Documentation Updated
- [ ] 🏟️ Peer / User Reviewed
- [ ] 🏆 Validated and Accepted

### ✅ To Do

- [ ] Investigate current state of e2e tests
- [ ] Create missing e2e tests for new transfer/call 

### 🔭 Scope

🏎️ In Scope: 
- ... 
 
 🙅‍♂️ Out of Scope: 
- ... 
 
 

### ⚖️ Acceptance Criteria

✨ Features: 
- [ ] ... 
 
 📚 Documentation: 
- [ ] ... 
 

### 🎢 Test Plan

Tests should cover next areas
- Transfer from the account (Bob) to account Alice
- Transfer from contract to contract
- Transfer from the account to the contract (need to check if it is possible)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@jchenche @sinapsist , is this ticket still relavent? I thought I saw tests for this get merged already

**Comment by hu3man** [comment]
Closing: covered in #1441
