### ISSUE TITLE
🐛 Bug ➾ The compile and Originate commands are failing when invokded from command pallet

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1267]
### 🆘 What happened?

The CLI has change the implementation of these commands to require the file name. Previously it was optional.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Is this not resolved with your new PR @AlirezaHaghshenas ?

**Comment by AlirezaHaghshenas** [comment]
This should have been closed automatically
