### ISSUE TITLE
🚧 Dev ➾ Invistigate a way to refactor e2e test to use different ports to reduce overlap during running in the pipeline

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#1270]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation
- [ ] 🏁 Test Plan Executed
- [ ] 🛩️ Documentation Updated
- [ ] 🏟️ Peer / User Reviewed
- [ ] 🏆 Validated and Accepted

### ✅ To Do

- Refactor `config.json` files for e2e tests to reduce the number of overlaps and make tests more robust.

### 🔭 Scope

🏎️ In Scope: 
- ... 
 
 🙅‍♂️ Out of Scope: 
- ... 
 
 

### ⚖️ Acceptance Criteria

✨ Features: 
- [ ] ... 
 
 📚 Documentation: 
- [ ] ... 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
I think this has been mostly fixed in other PR's. Feel free to close if it's not relevant @alexzbusko!
