### ISSUE TITLE
🌋 E|F ➾ Generate, Fund and List Accounts

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1279]
### 🚥 Status

- [x] 🔮 Product/Feature Design
- [ ] ✍🏻 Architecture/Implementation Planning
- [ ] 🏗️ Under Construction
- [ ] ⛳ Feature Complete
- [ ] ⛵ GTM / Release

### 📐 Feature Description

This epic tracks the work required to implement account generation and funding per environment

### 🔭 Scope

🏎️ In Scope: 
- ... 
 
 🙅‍♂️ Out of Scope: 
- ... 
 
 

### ⚖️ Acceptance Criteria

✨ Features: 
- [ ] ... 
 
 📚 Docs: 
- [ ] ... 

### 🔗  Related Issues and Subtasks

- #1277 
- #1306 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jevonearth** [comment]
Here's some "pseudo" json we used to model some ideas. It's not a specification. This file suggests that we store secret key material in the config, which we should not do, and if we do, it's only as a stop-gap measure.

![image](https://user-images.githubusercontent.com/1114943/192622409-0321c6f3-db6f-46fc-9dfe-c213fda2faa2.png)

**Comment by hu3man** [comment]
Closing: complete
