### ISSUE TITLE
TASK: Implement Scaffolding

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#128]
### Description

As a user, I want to initialize a new project using the smart contract language, and, optionally, a web framework of my choice.

### Design notes

`taq scaffold [alias|uri]`

#### Alias examples

The following respecitve commands would scaffold a project with a basic smart contract, along with (optionally) tests in the SC's language. A deployment script and example integration test will also be generated by the scaffold action.

`taq scaffold ligo`
`taq scaffold smartpy`

#### URI example

A third party can make a scaffold and push it to a git server. 

Any user of `taq` should be able to use that scaffold by running the command;

`taq scaffold https://github.com/example/tezos-ligo-and-react-nft-market`

Which would give the user a scaffold-ed project with ligo NFT market place contracts, a started dapp, deployment and test scripts.

### Acceptance Criteria

- [ ] `quick-start` repo is created and can be cloned
- [ ] `quick-start` is the default github repo
- [ ] `quick-start` is the default target directory

**Comment by ricklove** [comment]
@mweichert I think the [type] argument is beyond the scope of the most basic implementation. For the minimal implementation, it just needs the git url and target directory.
