### ISSUE TITLE
🐛 Bug ➾ Contract Types Should Ignore *.default_storage.tz and parameters.tz files

### ISSUE THREAD

**Issue by ricklove** [ecadlabs/taqueria#1284]
### 🆘 What happened?

contract types includes the *.default_storage.tz file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jchenche** [comment]
@ricklove 

Hi Rick, it should also ignore `*.storage.*.tz` and `*.parameter.*.tz` files too. They are both generated and put into the `/artifacts` directory.

**Comment by jchenche** [comment]
And `*.expression.*.tz` as well
