### ISSUE TITLE
🚧 Dev ➾ Fix vsce workflow to correctly publish the extension for prerelease and release

### ISSUE THREAD

**Issue by GImbrailo** [ecadlabs/taqueria#1289]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation
- [ ] 🏁 Test Plan Executed
- [ ] 🛩️ Documentation Updated
- [ ] 🏟️ Peer / User Reviewed
- [ ] 🏆 Validated and Accepted

### ✅ To Do

- [ ] Update the `vscode-extension.yml` workflow and fix the condition on L96

### 🧰 Work Description

Currently there is an issue with the workflow where the extension does not get published when we do a prerelease. This is because of the condition that checks if the event is a publish event. When we do a prerelease the event is a `push.tag` event and not a publish.

### ⚖️ Acceptance Criteria

- [ ] The extension is published when we do a prerelease

### 🦄 Sizing

1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Done!
