### ISSUE TITLE
Apple Codesigning for the `taq` binary

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taqueria#129]
### Description

Mac OS requires that executable programs be signed using an Apple ID developer account

- [x] Set up Apple ID developer account
- [x] Verify with Apple
- [x] Generate CSR
- [x] Submit CSR
- [ ] Sign binary **Blocked** Deno binaries fail Appls validation. Blocked by issue: https://github.com/denoland/deno/issues/11154

#### Acceptance Criteria
- [ ] A signed binary can be downloaded, executable bit set `chmod +x taq`, and the binary should run without any prompts or intervention

**Comment by i3games** [comment]
You should also update the documentation - remove step 4 on https://taqueria.io/docs/getting-started/installation/

**Comment by i3games** [comment]
> > You should also update the documentation - remove step 4 on https://taqueria.io/docs/getting-started/installation/
> 
> Hey @i3games, thanks for trying out Taqueria! Mac users will still need to disable Gatekeeper with the current versions of Taqueria. Once we move to have Taqueria installed via an installer or package managers, we will update the website.
> 
> Issue #198 tracks this work if you are interested in following along.

I did not have to disable Gatekeeper to run the CLI and I double checked Gatekeeper is active on my machine.
