### ISSUE TITLE
🐛 Bug ➾ plugin-contract-types : Module '"./type-aliases"' has no exported member 'lambda'.

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#1292]
### 🆘 What happened?

![image](https://user-images.githubusercontent.com/2536368/193026731-27e3a6f1-39ba-4c92-9a86-8727c579fb1c.png)

When generating classes from a smartcontract storage containing a lambda field :  

- on the generated file pokeGame.types.ts : lambda is correctly imported but not found
- on the generated file type-aliases.ts : lamba is not declared

during compilation, it fails with image above

### 🪵 Relevant log output

```shell
ERROR in src/pokeGame.types.ts:3:19
TS2305: Module '"./type-aliases"' has no exported member 'lambda'.
    1 |
    2 | import { ContractAbstractionFromContractType, WalletContractAbstractionFromContractType } from './type-utils';
  > 3 | import { address, lambda, MMap, nat, ticket } from './type-aliases';
      |                   ^^^^^^
    4 |
    5 | export type Storage = {
    6 |     feedback: string;
```

### 🐘 How impactful is this bug?

🚒 Showstopper

### 🌮 Taqueria Version

v0.19.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Thanks for reporting @zamrokk! 

Looks like we need to add another type. @ricklove or @mweichert, please provide an estimate and any context on this issue

**Comment by zamrokk** [comment]
I saw that normally you extract of types and make a big "Storage" type with primitive types. Just this time for function definition, there is no specific primitive type "lambda" for it, instead, it a function definition you have to translate from jsligo to typescript function definition and replace it everywhere it is used

**Comment by sinapsist** [comment]
@zamrokk Can you, please, provide the contract file if it is possible? I tried different contracts and cannot see the issue.

**Comment by zamrokk** [comment]
Good training n° 4   =) 

https://github.com/marigold-dev/training-dapp-4

Here you have complete example tutorial + workaround

**Comment by hu3man** [comment]
@jchenche @mweichert , given the visibility of this error can you please investigate?

**Comment by jchenche** [comment]
The pokeGame.types.ts file I got from `taq generate types` doesn't mention "lambda"

**Comment by zamrokk** [comment]
you should have a a part of the training where a lambda is declared. Do run the final solution

**Comment by jchenche** [comment]
![Screen Shot 2022-10-13 at 21 28 39](https://user-images.githubusercontent.com/30018387/195762581-ea1c41f7-8ac7-4812-8c60-b226dc4f38a2.png)

@zamrokk they can't be rendered on safari. but on chrome it's fine. just wanted to let you know

**Comment by zamrokk** [comment]
is typescript code section on markdown :/  Maybe there is an issue with Safari and github markdown 

Erk

Thank  for the report

**Comment by AlirezaHaghshenas** [comment]
I'm working on this.
