### ISSUE TITLE
🐛 Bug ➾ taq compile parameters, output file is different from the storage default_storage

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#1293]
### 🆘 What happened?

Documentation here : https://1166-ligo-native-test-jcc.taqueria.pages.dev/docs/plugins/plugin-ligo/

```
taq compile hello.storages.mligo will compile each definition in hello.storages.mligo and will produce a Michelson .tz file that contains the storage value, as a Michelson expression, for each of them. If the name of a variable is storage1, then its emitted Michelson file will be named hello.storage.storage1.tz. For taq compile hello.parameters.mligo, the name will be hello.parameter.param1.tz if there's a variable named param1 defined in hello.parameters.mligo.

Furthermore, the first variable definition in hello.storages.mligo will be treated as the default storage and will produce a Michelson file named hello.default_storage.tz instead. The deploy task from the Taquito plugin will take advantage of this. Go to that plugin documentation to learn how.
```

Here my files

![image](https://user-images.githubusercontent.com/2536368/193032770-51b0d557-25f9-4a21-874c-f3d2293e8320.png)

Content of files :

for parameter
```
#include "pokeGame.jsligo"
const default_parameter = UpdateFeedbackFunction((oracleAddress : address) : string => "YEAH!!!");
```

for storage
```
#include "pokeGame.jsligo"
const default_storage = {
    pokeTraces : Map.empty as map<address, pokeMessage>,
    feedback : "kiss",
    ticketOwnership : Map.empty as map<address,ticket<string>>,  //ticket of claims
    feedbackFunction : ((oracleAddress : address) : string => { return match( Tezos.call_view("feedback", unit, oracleAddress) as option<string> , { Some : (feedback : string) => feedback,  None : () => failwith("Cannot find view feedback on given oracle address")  }); })
};
```

conclusion, so for default storage , the output is `<>.default_storage.tz ` , but for default parameter is `<>.parameter.default_parameter.tz `

Normal that is slightly different pattern ?

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### 🌮 Taqueria Version

v0.19.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Thanks for reporting @zamrokk!

@jchenche, do you know if this was intentional and what do you think the correct behaviour should be?

**Comment by jchenche** [comment]
@zamrokk how was `<>.parameter.default_parameter.tz` generated? There is no such naming pattern for parameters as of the current design of out LIGO plugin. Only storage have defaults.

**Comment by jchenche** [comment]
@zamrokk ohhh never mind, since you named it `default_parameter`, the artifacts shows this name. This is expected yes.
