### ISSUE TITLE
Dev ➾ Abstract Model for environments/networks/accounts

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#1307]
Scope:
- [ ] Abstract model

# Environments, Networks, and Accounts - An Abstract Model

The initial abstract model is rather simple:

An environment is an execution context for a task invocation.
A sandbox or network is a target for task invocation.

For the purpose of this document, the following applies:
- the terms _execution context_ and _environment_ are interchangable
- the terms _target_, _sandbox_, or _network_ are interchangable

Environments are used for the following reasons:
- Task invocation results in state machine transitions.
- An execution context provides a means for providing an initial state as input
- An execution context provides a boundary between the different state representations and updates incurred from task invocations

*IMPORTANT: state is to be captured and persisted to environment-specific stores.*

#### Example

When originating a contract, the following is required:
- A target. The task needs to know what sandbox or network the contract should be deployed to
- Initial storage. This is environment-specific configuration needed to originate the contract
- State. An origination results in an output that will need be to be persisted, the contract address

##### Prototypical Example

Below is a prototypical example to showcase how the abstract model supports the concrete problems we need to solve:

> I, as a dApp developer, want to offer a means for my users to swap from one token to another. In this particular case, I won't be implementing an automated market-maker, but instead rely on an external service via an Oracle contract to reference the exchange rate between tokens.

To build this, the developer would need to:
1. Build and originate an Oracle contract
1. Build the swap contract
1. The swap contract will post queries to the Oracle contract, and receive replies via the Oracle contract.
1. Test and verify that only the admin or operator roles can adjust the token pairs and oracle contract.

In our environment, we'll do the following:
- Target a sandbox configuration.
- Provide initial storage for our Oracle contract: a string like "XTZ/USDC" to represent the token pair we want exchange rates for
- Provide initial storage for our Swap contract: a record that looks like the following:

```json
{
    oracleAddress: "KT1....",
}
```

> This is a simple example, and in production, data structure for the initial storage for each contract would be more sophisticated. However, although simplified, this example can validate (or invalidate) the abstract model as defined above.

*IMPORTANT: More than one developer could be working on this project.*

We will reference this prototypical example in the problem domain below.

## Current Data Model

```mermaid
classDiagram
    direction LR
    
    Environment "*" --> "*" NetworkConfig
    Environment "*" --> "*" SandboxConfig
    SandboxConfig "1" --> "*" SandboxAccountConfig
   
    class Environment {
        +NetworkIdentity[] networks
        +SandboxIdentity[] sandboxes
        +Alias[] aliases
        +Record~ContractIdentifier, Storage~ storage
    }

    class NetworkConfig{
        +string label
        +string rpcUrl
        +string protocol
    }

    class SandboxConfig {
        +string label
        +string rpcUrl
        +string protocol
        +PluginIdentifier plugin
        +Record~AccountIdentifier, SandboxAccountConfig~ accounts
    }

    class SandboxAccountConfig {
        +string encryptedKey
        +string publicKey
        +string publicKeyHash
    }

    class Config {
       +Record~NetworkIdentity, NetworkConfig~ network
       +Record~SandboxIdentity, SandboxConfig~ sandbox
       +Record~EnvironmentIdentity, EnvironmentConfig~ environment
       +Record~AccountIdentity, balance~ accounts
    }
```

#### Problem 1: Many-to-Many relationship between an environment and target

Tasks use an environment to reference pre-configured targets. In the current design, an environment is modelled to support one or more targets.

However, this model has the following problems:

1. The data structure for state becomes complex, as the state between each target in the environment differs
1. There's a violation between the abstract model and the data model - an environment's purpose is to provide boundaries for different state updates and representations. However, the current data model mixes the state between targets and environments.

##### Validating the problem

Reviewing our prototypical example, if we were to deploy a contract in an environment having two targets, such as a sandbox and a network, each target will have its own state representation. _The contract addresses_ will differ depending which target we examine. The current model for an environment creates a boundary for state between different environments, but _NOT_ between different _targets_ in the _same_ environment.

##### Proposed Solution

We adjust the environment model to only have a single target. The target can be _either_ a sandbox or network.
In otherwords, we adjust the relationship between an environment and a target to be 1-to-1 instead of many-to-many.

##### Validating the solution

In our prototypical example, to deploy to two different targets, such as a sandbox and network, we would require an environment per target. After deploying to each, a proper state boundary would be provided by each environment to dissociate the contract addresses for each target.

#### Problem X: Inability to target mainnet, or distinguish one type of network from another.

Our current design has the following limitations:
- We cannot distinguish a public testnet provided by teztnets.xyz from another provided by SmartPy.
- We cannot distinguish a public testnet from a private testnet
- We cannot target mainnet

The problem caused by the inability to deploy to mainnet is obvious, and therefore doesn't need any more explanation.

The inability to distinguish one type of network from another causes problems as we would like to provide assistance and instructions for funding accounts, but as each network has its own requirements for funding, we cannot provide target-specific information.

##### Validating the problem

Using our prototypical example, it's safe to assume that eventually the end-developer will need to deploy to mainnet. We lack this capability at the moment.

Again, using our prototypical example, its possible that the end-developer will want to target:
- A public testnet other than one provided by teztnets.xyz, such as one from SmartPy
- A private network, whether it be a testnet, permissioned network, or private mainnet (such as DCP).

##### Proposed Solution

We should make our network configuration more generic, and not specific to teztnets.xyz.

Plugins should be responsible for distinguishing one network from another, and facilitate the process of funding accounts on the networks of their concern.

For instance:
- A teztnets plugin should identify that a task is being invoked against an environment that is targeting a network of the plugin's concern, and do any necessary prompting and processing required for funding the accounts.
- A DCP plugin could be developed to do the same when the environment is targeting one of their testnets
- The SmartPy plugin could be adjusted to the same when an environment is targeting their testnet

In doing so, we can keep a generalization for the concept of a network.

To facilitate this, when a plugin defines a task, a task needs to be flagged as one that emits Tezos operations.

Additionally, the hook construct would be required, as we currently have no means of triggering logic from one plugin when a task from another plugin is being invoked.

###### Validating the solution

Using our prototypical example, the end-developer will need to target a network when originating their contracts, and the target network could have different funding requirements:
- If targeting teztnets.xyz then our teztnets plugin would intercept task invocation (for tasks that have been flagged to emit Tezos operations), check whether funding is required, and interrupt the handling of the task to provide instructions for funding their root account via the appropriate faucet. The teztnets plugin could identity whether the current target is a testnet provided by teztnets.xyz, as well as determine what faucet to use, by cross-examining the RPC url of the target in the network configuration against the RPC urls from https://teztnets.xyz/teztnets.json
- If targeting the DCP testnet, the DCP plugin would do much the same, but be aware of what RPC urls are those for DCP testnets, and too know what link to provide for faucet urls.

#### Problem X: Account management creating unnecessary processing and cognitive overhead, while also impeding the common development cycle

Each time a sandbox is started, we examine the declared accounts and instantiate accounts to reflect that for the sandbox about to start. That's a good but we could do better:
- We're instantiating accounts (that is, generating a new secret key) for each start of a sandbox, despite this account instantiating only strictly required once. This results in additional processing/computation time, and the end-developer might be confused why their keys are changing.
- The list of declared accounts should reflect and respect the accounts in the end-developer's Beacon wallet.

##### Validating the problem

Using our prototypical example, we can assume that the developer would wish to do the following, most likely in sequence:
1. Originate the contracts to a sandbox.
1. Run unit tests for the contract (perhaps using LIGO's test framework)
1. Run automated integration tests against the sandbox.
1. Originate the contracts to a testnet.
1. Run automated integration tests against the testnet.
1. Manually test their dApp to ensure that contract entrypoints are working properly
1. Originate the contracts to mainnet.

*Additionally, Taqueria should facilitate the common development cycle (develop, deploy, verify) without additional cognitive overhead.*

At some time in the development cycle, its highly likely that the end-developer will want to test the entrypoints of their contracts manually by interacting with a browser and Beacon wallet. They might not do that immediately, but again, its highly likely that within the development cycle that end-developer will want to manually verify that their contract is working as designed by invoking endpoints with Taquito and a Beacon wallet.

Due to some issues with the current design, this is what that process would look like:
1. The developer review and updates the configuration for the declared accounts.
1. The sandbox is started, which instantiates the declared accounts.
1. The developer needs to open their Beacon wallet, such as Temple, and manually add each instantiated account to their wallet. This is a somewhat tedious process, as it requires multiple steps and the end-developer has to keep referencing the .taq/config.json file to copy/paste each secret key as they add each account to their wallet.

That last step could (and should) be optimized, as Taqueria is adding work for the end-developer that isn't necessary.

##### Proposed Solution

> We should adjust when and how the declared account configuration is generated.

After a project is initialized, we shouldn't include the declared accounts configuration. Instead, we should prompt the user for permission to connect to their Beacon wallet. We can then the list the accounts configured in their wallet and prompt them to set balances for the account. See (here)[https://github.com/ecadlabs/taqueria/issues/1172#issuecomment-1265733052] for more details.

> We can also provide a note to the end-developer, _Need more accounts? Add them to your wallet and select *Refresh accounts*_.

With this proposed adjustment in place:
- The end-developer has fewer steps when interacting with a Beacon wallet. There's no need to look at the config.json file.
- When adding accounts, the end-developer conducts this using a tool that they're already familiar with - their wallet
- Whether targeting a sandbox or testnet, the process is the same - 

#### Problem X: Declared accounts and multiple developers per project

> This is a theorized problem, and hasn't been validated against a prototypical example yet.

When a sandbox is starting, it references the list of declared accounts and balances. As this declaration is global to a project, its effectively shared between different developer workstations.

##### Validating the problem

Can we think of a prototypical example where this breaks down?

##### Proposed Solution

As this seems to be less likely of a problem, a simple and generic solution might be to introduce a new classification of configuration - overrides.

> KNOW YOUR TERMS: Taqueria has two types of configuration: project configuration (.taq/config.json) and global configuration ($HOME/.taq/settings.json). The global configuration provides default settings for all projects, whereas the project configuration provides settings that are project-specific.

E.g.

In $HOME/.taq, we introduce a new file called _custom.json_. Internally, when Taqueria is building the Config data model in memory, it does so by:

1. Loading the global configuration ($HOME/.taq/settings.json)
2. Loading the project configuration ($PROJECT_DIR/.taq/config.json)
3. Loading the overrides configuration

In each step, the configuration is merged, with key/values already loaded being overwritten by a later step.

To implement this, we would probably need to also add a new field to each project configuration - the name of the project. That way in the overrides configuration, we could specify a per-project override.

**Comment by mweichert** [comment]
Just a note, I'll be taking the markdown from the issue description above and generating a PDF that will have better formatting. Github's rendering of this markdown isn't quite as good as other solutions just yet.

**Comment by hu3man** [comment]
Awesome!

We should probably add the markdown to a page in the `/design-docs` folder

**Comment by jevonearth** [comment]
---
In section _Problem X: Inability to target mainnet, or distinguish one type of network from another._
> We cannot distinguish a public testnet provided by teztnets.xyz from another provided by SmartPy.
 
I think you are referring to RPC nodes here, which are points of access to a given network. It's ambiguous as worded.

---
> Using our prototypical example, it's safe to assume that eventually the end-developer will need to deploy to mainnet. We lack this capability at the moment.

I don't think this capability is missing, but the means to do it are not what we would call good security practices. I can still make an account for mainnet, fund it, use the `sk` in the project, and use taq to deploy contracts to mainnet.

---

We need to dig into the role of implicit accounts as secrets in a project V's wallets accessible via Beacon. I think they have distinct roles/purposes. Let's discuss this, so we avoid conflating these.

---

> Problem X: Declared accounts and multiple developers per project
> This is a theorized problem, and hasn't been validated against a prototypical example yet.

I have seen this problem manifest in practice with sample apps running on testnets(before taqueria's time), so I don't believe it to be theoretical. Using the same secrets on sandboxes (which I believe we share the assumption that a sandbox has one user at a time) is likely _okay_, but what's the advantage of having different behaviour on sandboxes V's on networks?

**Comment by hu3man** [comment]
Feature complete
