### ISSUE TITLE
🚧 Dev ➾ Add Contract Types Plugin to Taco-Shop

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1327]
### 🔗 Epic|Feature Link

#1215 

### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation (PR merged)
- [ ] ✍️ Release Notes Added
- [ ] 🏆 Product Acceptance

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] dApp has contract types plugin pre-installed and generates types during setup script
- [ ] dApp consumes generated types in calls to Taquito
- [ ] Documentation is written to illustrate how this is used and how it benefits the dev
- [ ] Helpful and informative code comments included to help developers at the touch point
 
 📐 Non-Functional: 
- [ ] ... 
 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### 🧰 Work Description

The quickstart scaffold is being deprecated to reduce the maintenance burden on the team. The main thing this scaffold illustrated was the use of the contract types plugin. We need to add this to the taco-shop scaffold in order to replace this demonstration  

### 🦄 Sizing

2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Hey @claudebarde, is this something you would be interested in taking on to get some more experience with the contract-types plugin?

**Comment by claudebarde** [comment]
Hey @hu3man, sure, I will be doing some work this week on some other issues related to Taqueria, I will add this one, thanks!

**Comment by hu3man** [comment]
Awesome, thanks @claudebarde !

**Comment by mweichert** [comment]
Done
