### ISSUE TITLE
🚧 Dev ➾ The ability to pin to a specific version of Ligo

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1343]
### 🔗 Epic|Feature Link

#1166

### 🚥 Definition of Done

- [x] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation (PR merged)
- [ ] ✍️ Release Notes Added
- [ ] 🏆 Product Acceptance

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] User can specify a Ligo version in config.json that the Ligo plugin will respect and use
- [ ] `taq originate` has an optional flag where a user can provide a target version
- [ ] The ligo plugin must provide a means to output the current version of Ligo being used
- [ ] The order of precedence is: CLI Argument > `config.json` version pin, > fallback to @latest

 📐 Non-Functional: 
- [ ] ... 
 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### 🧰 Work Description

This ticket covers the work involved in making the Ligo plugin able to use a specific version of Ligo. This is a request from the Ligo team and is something that can help users with version consistency since  Taqueria defaults to @latest. The user should be able to specify an optional property in `config.json` where they can declare a specific version of Ligo. The `taq compile` task should also have an optional flag which takes a version

The plugin should detect if the current version of Ligo being used is correct and if not, retrieve the correct image and use that underlying docker container 

### 🦄 Sizing

5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zamrokk** [comment]
Hi , I tried last 0.23.0-rc.2 version with

`LIGO_DOCKER_IMAGE=ligolang/ligo:0.54.1 taq compile pokeGame.jsligo`

It is fetching always ligo:0.51.0

Is it the good way to do it ?

thanks

**Comment by jchenche** [comment]
Not sure if that release includes that feature 🤔

**Comment by zamrokk** [comment]
might be why XD

**Comment by hu3man** [comment]
Closing: handled by docker image override

**Comment by zamrokk** [comment]
which taq version ?

**Comment by jchenche** [comment]
@zamrokk upcoming release I believe.

@hu3man right?
