### ISSUE TITLE
🚧 Dev ➾ Remove Deprecated Scaffolds from VScE

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1349]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation (PR merged)
- [ ] ✍️ Release Notes Added
- [ ] 🏆 Product Acceptance

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] Only the following scaffolds appear in VScE: Taco-Shop, NFT-Scaffold
 
 📐 Non-Functional: 
- [ ] ... 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### 🧰 Work Description

We have deprecated several scaffolds to reduce the maintenance burden and we need to remove the old ones from VScE

### 🦄 Sizing

0.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlirezaHaghshenas** [comment]
@hu3man 
Which ones should I keep?

**Comment by hu3man** [comment]
Just `nft-scaffold` and `taco-shop`
