### ISSUE TITLE
🐛 Bug ➾ tezos-client needs to be targeting a new network

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#1375]
### 🆘 What happened?

Right now, tezos-client tasks (typecheck and simulate) are targeting a Jakarta network. It should be targeting a new network.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
@jchenche @hu3man I think we'd be best to have this use a network or sandbox from the current env, and then if one doesn't exist, target ghostnet. Thoughts?

**Comment by hu3man** [comment]
I think that's that's appropriate behaviour @mweichert
