### ISSUE TITLE
🚧 Dev ➾ Marigold Ligo Training Poke Game

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1377]
### 🚥 Definition of Done

- [X] 🎯 Planning and Design
- [x] 🏎️ Dev Implementation (PR merged)
- [ ] 🏆 Product Acceptance

### ✅ To Do

- [x] Complete training using Taqueria CLI
- [x] Complete training using Taqueria VsCE

### ⚖️ Acceptance Criteria

✨ Functional: 
- [x] Complete the full tutorial
- [x] Friction log of issues encountered
- [ ] Post-completion review / ticket slicing
 
 📐 Non-Functional: 
- [ ] ... 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- Anything a user outside of ECAD labs could do without direct support
 
 

### 🧰 Work Description

To validate Taqueria in the context of the new Marigold Ligo training, team members will go through the course to learn where Taqueria is working and where it needs improvement

This ticket covers the work for @michaelkernaghan to explore the program and collect input on Taqueria with fresh eyes

### 🦄 Sizing

3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
Completed the review with the new Taqueria release 0.22.2
