### ISSUE TITLE
🐛 Bug ➾ Text output typo when starting a postgresql docker container (not "Staring", should be "Starting")

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1380]
### 🆘 What happened?

I followed the instructions in the docs for setting up the first project.  
I got the step:  taq start sandbox local
I noticed in the output from this command that it says "Staring PostgreSQL"
it should be "Starting," not "Staring."

Same with the rest of the console output:
Staring TzKt.Sync
75573ffd434ddb3407aaac6ab94e17f2ef1bcf1c68c8ae94c45928f0d13de336

Staring TzKt.Api
e09e65b98b9b314a159c9654cef9b09276bbc3c1ca17156d87fb13ca469e55e1

### 🪵 Relevant log output

```shell
Eve:~/myfirstproject/my-first-project$ taq start sandbox local
20000 is already in use, 20001 will be used for sandbox local instead and .taq/config.json will be updated to reflect this.
Booting sandbox...
Configuring sandbox...
Adding accounts...
Started local.
5432 is already in use, 5433 will be used for postgresql in local instead and .taq/config.json will be updated to reflect this.
5000 is already in use, 5001 will be used for TzKt API in local instead and .taq/config.json will be updated to reflect this.
Staring postgresql
4e1417862e233fed0da1861ce060d9758f5d7903f34af04eb683ee5e2427fb35

Staring TzKt.Sync
75573ffd434ddb3407aaac6ab94e17f2ef1bcf1c68c8ae94c45928f0d13de336

Staring TzKt.Api
e09e65b98b9b314a159c9654cef9b09276bbc3c1ca17156d87fb13ca469e55e1
```

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

maybe once

### 💻 Operating System

Linux

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.20.2

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Thanks @michaelkernaghan!

Please include a title to help identification on the board

**Comment by AlirezaHaghshenas** [comment]
Already fixed
