### ISSUE TITLE
🐛 Bug ➾ Typos on the v0.22.2 Release notes

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1420]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I went to https://taqueria.io/docs/release-notes/ to learn how to upgrade, and I found a few typos in the text.

- Is this a typo?  "Teztnet accounts"
- Assuming users know what  VsCE referes too
- typo "operation is submited to a"
- "Beacon Wallet" in one case but "Beacon wallet" elsewhere
- typo "determine the the sandbox label & RPC url"
- looks like a typo "uses a fixed stable of version of the"

### 🆘 Steps to Reproduce?

go to https://taqueria.io/docs/release-notes/ 

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

If they read the doc

### 💻 Operating System

Windows -> WSL

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

supposed to be 0.22.2 but shows v.0.20.2

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Thanks for raising these @michaelkernaghan. You can go ahead and open a PR to make the changes

**Comment by hu3man** [comment]
On the first point, we are using a Teztnets faucet which is why that spelling was used
