### ISSUE TITLE
🚧 Dev ➾ Provide a means of overriding all docker images

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#1425]
### 🚥 Definition of Done

- [x] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### ✅ To Do

- [ ] #1508
- [ ] Determine whether each plugin that uses a docker image should provide a "show-image-name" task.

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] Add a function to the Taqueria SDK like, `getDockerimage(imageName: string, envVarName: string)`
- [ ] Adjust ligo plugin to use this method
- [ ] Adjust archetype plugin to use this method
- [ ] While we're editing relevant code, we may as well adjust any image names to use the latest version tag of the docker image.

### 🔭 Scope

Associated ticket: https://github.com/ecadlabs/taqueria/issues/1425

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Is this something you can take on next sprint @mweichert ?

**Comment by jchenche** [comment]
Should I take on this?

**Comment by hu3man** [comment]
I think you are the best person to do this. We'll schedule it for an upcoming sprint. As discussed, this won't work for Flextesa so it's just the compilers

It also implicitly solves the Ligo ticket for pinning a particular version of Ligo #ligo #1343
