### ISSUE TITLE
🐛 Bug ➾ The hardcoded rpc address in the taqueria-scaffold-taco-shop scaffold needs to be changed to use an ecad server

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1432]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [x] ⚗️ Solution Identified and Designed 
- [x] 🧫 Dev Implementation of Fix
- [x] 🧪 Fix Tested and Validated
- [x] 🏆 PR Merged

### 🆘 What happened?

I was trying to use the taqueria-scaffold-taco-shop, and it had a problem connecting to "https://rpc.ghostnet.teztnets.xyz") because of a problem at the RPC end. But the demo should not use testnets.xyz, it should be using [ghostnet.ecadinfra.com](https://ghostnet.ecadinfra.com/)

### 🆘 Steps to Reproduce?

1. go to https://github.com/ecadlabs/taqueria-scaffold-taco-shop
2.  go to the section "Insert the Contract Address."
3. not in the code sample the rpcURL is "https://rpc.ghostnet.teztnets.xyz"
4. it should be changed to https://ghostnet.ecadinfra.com
5. similarly, inside the code, the address should also be changed in /app/src/App.tsx

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

if there is a problem with the rpc server 

### 💻 Operating System

Linux

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.22.0

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing: DONE!
