### ISSUE TITLE
🐛 Bug ➾ Readme for the scaffold taco shop example - need to remove the explanation of how tom make additional tacos

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1434]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

The readme example has the incorrect file for the purpose being demonstrated

### 🆘 Steps to Reproduce?

1. get and install the Taqueria Scaffold Taco Shop repo
2.  in the readme, note the example at "Make Tacos using the taq call command"
3.  the instruction `taq call hello-tacos --param hello-tacos.parameter.buySomeTacos.tz -e testing` is for buying Tacos, not for making them
4. the instruction needs to be changed to call for the correct param file.

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

If they read the doc

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.22.0

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
I removed the detail about how to make new tacos

**Comment by hu3man** [comment]
Closing: Done!
