### ISSUE TITLE
🐛 Bug ➾ in Scaffold Taco-Shop,  taq call hello-tacos --param .... does not add its contract to config if no -e flag used

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1435]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [x] ⚗️ Solution Identified and Designed 
- [x] 🧫 Dev Implementation of Fix
- [x] 🧪 Fix Tested and Validated
- [x] 🏆 PR Merged

### 🆘 What happened?

When you have both a development and a testing environment, the -e flag selects the correct env and uses the contract in the alias. But when no -e flag is used, a new contract is created, and its address is not added to the config.  It should default to the testing env, and I would expect it to use the contract in the alias there.

### 🆘 Steps to Reproduce?

0. ensure no taq local sandbox is running
1. taq scaffold https://github.com/ecadlabs/taqueria-scaffold-taco-shop taco-shop
2. cd taco-shop
3. look in the config.json, and an alias hello-tacos with the contract address has been added to the testing section
4. start the local sandbox
5. look in the config.json, and an alias hello-tacos with the contract address has been added to the development section
6. taq call hello-tacos --param hello-tacos.parameter.buySomeTacos.tz -e testing
7. an account was added to the config, and a request is given to the user to fund it.
8. fund the account
9. taq call hello-tacos --param hello-tacos.parameter.buySomeTacos.tz -e testing
10. the test succeeds using the contract in the alias in the testing environment
11. taq call hello-tacos --param hello-tacos.parameter.buySomeTacos.tz -e development
12. the test succeeds using the contract in the alias in the testing environment
13. taq call hello-tacos --param hello-tacos.parameter.buySomeTacos.tz      (no -e flag!)
14 test succeeds but uses a completely new contract b the dev env, and the new contract is not in the config.

![image](https://user-images.githubusercontent.com/78441942/199346533-1c9cc3e2-d708-4920-b810-788febfdb2a5.png)

### 🐘 How impactful is this bug?

not major but more than minor

### ⏱️ Prevalance

if they have more than one environment config

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.22.0

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Duplicate: #1223
