### ISSUE TITLE
🚧 Dev ➾ Add automated tests for the compile operations with LIGO/Archetype

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#1439]
### 🚥 Definition of Done

- [x] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### ✅ To Do

Create the following tests for the plugins:
LIGO:

- [x] Help content tests for the test and create tasks
- [ ] Generated contract has the correct file contents
- [ ] Help content test for creating contract with no name, as well as syntax options
- [ ] Creation of contract files with each supported syntax option

Archetype:

- [ ] Alias compilation tests (aliases: c, compile-archetype)
- [ ] That contract creation works and will create a file with the correct information
- [ ] Help menu for compile as well as create
- [ ] Error when missing/incorrect file extension is used

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] 
- [ ] 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Done
