### ISSUE TITLE
🐛 Bug ➾ NFT Scaffold Project instructions for Pinata key need additional clarification

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1440]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [x] ⚗️ Solution Identified and Designed 
- [x] 🧫 Dev Implementation of Fix
- [x] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I tried to use a key on Pinata, but it was not the JWT key, and I did not know. When I tried the key I thought was the one the docs referred to, I got errors.

We need to add a one-line clarification note to the instructions about disambiguating the JWT key from the API key for users who may be confused by this,

### 🆘 Steps to Reproduce?

In the Scaffold NFT instructions:
Scaffold and Initialize the Project
1. taq scaffold https://github.com/ecadlabs/taqueria-scaffold-nft nft-scaffold
2. cd nft-scaffold
3. npm run setup
4. cd taqueria
5. touch .env
6. Get your Pinata JWT token from your Pinata account
here should add clarification something like: 
"Please do not use a key listed on https://app.pinata.cloud/keys. Add a new key, and from the create dialogue, copy the JWT for the new key and use that"

### 🪵 Relevant log output

```shell
runTask: taq publish ./assets/
The 'credentials.pinataJwtToken' was not found in config
```

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

if they are new to Pinata

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.22.0

### 🌿 Node.js Version

v18.4.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Which PR is associated with this?

**Comment by michaelkernaghan** [comment]
the pr is in the repo for the NFT scaffold:
https://github.com/ecadlabs/taqueria-scaffold-nft/pulls
