### ISSUE TITLE
🐛 Bug ➾ typo 'udpate' in last step of NFT Scaffold. 

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1448]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

found a typo in the console log running apply in the NFT Scaffold

### 🆘 Steps to Reproduce?

1. taq scaffold https://github.com/ecadlabs/taqueria-scaffold-nft nft-scaffold
2. cd nft-scaffold
3. npm run setup
4. cd taqueria
5. touch .env
6. Get your Pinata JWT token from your Pinata account
7. Insert the JWT from Pinata into the .env file echo “pinataJwtToken=eyJhbGc…” >> .env
8. cd …
9. npm run start:taqueria:local
10. npm run apply
observe the last step of the console log says 'udpate' instead of the more usual 'update'. 
![image](https://user-images.githubusercontent.com/78441942/199876648-fc287bb2-c0b7-4a1b-b36f-be8b6971dcba.png)

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.22.0

### 🌿 Node.js Version

v18.4.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexzbusko** [comment]
Closed by https://github.com/ecadlabs/taqueria-scaffold-nft/pull/11
