### ISSUE TITLE
🐛 Bug ➾ Typo in the docs on the Scaffold Page

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1453]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [x] ⚗️ Solution Identified and Designed 
- [x] 🧫 Dev Implementation of Fix
- [x] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

the  last table on the scaffold page has a typo

### 🆘 Steps to Reproduce?

1, https://taqueria.io/docs/scaffolds/scaffold-basics/
2. scroll down to Available scaffolds
3. in the third cell of the bottom row, it says "A Taqueria project for developing NFT"
4. it should say "A Taqueria project for developing NFTs"

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

If they read the doc

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.22.0

### 🌿 Node.js Version

v18.4.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
fixed.

**Comment by hu3man** [comment]
Closing: DONE!
