### ISSUE TITLE
🐛 Bug ➾ Option for submitting yes to any prompt does not work for the opt-in/opt-out google analytics functionality

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#1455]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

When checking the options for `taq` commands there is a -y/--yes option which will answer yes to any prompts Taqueria should give you. It currently does not and the user still needs to input their decision into the command line

### 🆘 Steps to Reproduce?

1. Initialize a taqueria project with `taq init project`
2. Try to opt into analytics with `taq opt-in -y`

Expected Result:
User is opted into analytics collection

Actual Result:
User still needs to state they agree to share usage statistics

### 🪵 Relevant log output

```shell
$ taq opt-out --yes
Are you sure you want to turn off usage statistic reporting? (Y/n)
```

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

Every time

### 💻 Operating System

Linux

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

0.22.2

### 🌿 Node.js Version

v16.17.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Fixed.
