### ISSUE TITLE
💭 Idea ➾ Create a handy default `.gitignore` on `taq create`

### ISSUE THREAD

**Issue by egarson** [ecadlabs/taqueria#1458]
### 🔮 Title / Topic

Emit a `.gitignore` on `taq init`

### 💭 Details

After creating a new taqueria project with `taq init`, a common next step will be to `git init`.

Currently, there is no skeleton `.gitignore` created, so users need to create one manually and populate it with sensible defaults (e.g. `**/node_modules/`, temp files, etc). It would be easy and convenient to automate this for the user.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jchenche** [comment]
Thanks Edward! I suggested this a while ago.

**Comment by jchenche** [comment]
@hu3man thoughts?

**Comment by hu3man** [comment]
I think this is a great idea! Let's get a ticket opened for this and estimated @jchenche

**Comment by jchenche** [comment]
@hu3man https://github.com/ecadlabs/taqueria/issues/1461
