### ISSUE TITLE
🚧 Dev ➾ Create a .gitignore file filled with the right stuff to ignore upon `taq init`

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#1461]
Realizes the idea ticket here: https://github.com/ecadlabs/taqueria/issues/1458

### 🚥 Definition of Done

- [x] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### ⚖️ Acceptance Criteria

✨ Functional: 
- [x] A `.gitignore` file is created during `taq init` 
- [ ] Ignored files should mirror those in the scaffold projects (maybe not because they are too specific to each scaffold, namely tacoshop vs nft)

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by egarson** [comment]
Woops I missed this ^_^
