### ISSUE TITLE
🚧 Dev ➾ LIGO workflow UI touch ups relating to storage and parameter files

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#1465]
### 🚥 Definition of Done

- [x] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### ⚖️ Acceptance Criteria

✨ Functional: 
- [x] Rename `<CONTRACT>.storages.mligo` to `<CONTRACT>.storageList.mligo` and `<CONTRACT>.parameters.mligo` to `<CONTRACT>.parameterList.mligo`.
- [x] If the storage or parameter file doesn't exist for a contract upon compilation of the contract, create them and alert users that we've done so.

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
What’s the estimate for this?

**Comment by jchenche** [comment]
Within an hour or two probably

**Comment by jchenche** [comment]
Also want to create them if they don't exist 🤔
