### ISSUE TITLE
🐛 Bug ➾ Fail to start local sandbox

### ISSUE THREAD

**Issue by avysel** [ecadlabs/taqueria#1473]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I created my first Taqueria project with `taq init` then I installed some plugins:

```
taq install @taqueria/plugin-ligo
taq install @taqueria/plugin-flextesa 
```
I try to start the local sandbox with `taq start sandbox local`

I get the following error:

```
Booting sandbox...
Configuring sandbox...
Error: Command failed: sh -c "docker exec taq-flextesa-local-27b80 node index.js --sandbox local --configure"
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

{
  kind: 'E_EXEC',
  context: 'tezos-client --endpoint http://localhost:20000 config update',
  previous: Error: Command failed: flextesa_node_cors_origin='*' tezos-client --endpoint http://localhost:20000 config update
  qemu: uncaught target signal 11 (Segmentation fault) - core dumped
  
      at ChildProcess.exithandler (node:child_process:400:12)
      at ChildProcess.emit (node:events:513:28)
      at maybeClose (node:internal/child_process:1093:16)
      at Socket.<anonymous> (node:internal/child_process:451:11)
      at Socket.emit (node:events:513:28)
      at Pipe.<anonymous> (node:net:757:14) {
    code: null,
    killed: false,
    signal: 'SIGSEGV',
    cmd: "flextesa_node_cors_origin='*' tezos-client --endpoint http://localhost:20000 config update"
  }
}

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 255,
  killed: false,
  signal: null,
  cmd: 'sh -c "docker exec taq-flextesa-local-27b80 node index.js --sandbox local --configure"'
}
```

It stucks on `Configuring sandbox...` for many minutes, then error happens.
In the meanwhile, if I try `taq list accounts local` in another terminal, I get:
``` 
Command failed: sh -c "docker exec taq-flextesa-local-27b80 tezos-client get balance for bob"
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Command failed: sh -c "docker exec taq-flextesa-local-27b80 tezos-client get balance for alice"
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Command failed: sh -c "docker exec taq-flextesa-local-27b80 tezos-client get balance for john"
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Command failed: sh -c "docker exec taq-flextesa-local-27b80 tezos-client get balance for jane"
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Command failed: sh -c "docker exec taq-flextesa-local-27b80 tezos-client get balance for joe"
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

┌─────────┬─────────┬──────────────────────────────────────┐
│ Account │ Balance │ Address                              │
├─────────┼─────────┼──────────────────────────────────────┤
│ bob     │ Error   │ tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6 │
├─────────┼─────────┼──────────────────────────────────────┤
│ alice   │ Error   │ tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb │
├─────────┼─────────┼──────────────────────────────────────┤
│ john    │ Error   │ tz1Zwoh1QCVAvJ4sVTojMp9pLYp6Ji4NoZy6 │
├─────────┼─────────┼──────────────────────────────────────┤
│ jane    │ Error   │ tz1aHUAC4oviwJuZF1EvVSvFz7cu9KMNYBph │
├─────────┼─────────┼──────────────────────────────────────┤
│ joe     │ Error   │ tz1MVGjgD1YtAPwohsSfk8i3ZiT1yEGM2YXB │
└─────────┴─────────┴──────────────────────────────────────┘
```

### 🆘 Steps to Reproduce?

See above

### 💻 Operating System

MacOS

### 🕸️ System Architecture

arm64 (M1 Macs)

### 🌮 Taqueria Version

v0.22.2

### 🌿 Node.js Version

v16.18.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Hi @avysel, thanks for reporting this

Are you working with a new project, or one that was possibly created using an older version of Taqueria or it's plugins? If the plugins installed on that project are out of date, you can update them using:

```
plugins=$(jq -r '.plugins[].name' .taq/config.json) && echo $plugins | xargs -n 1 taq uninstall && echo $plugins | xargs -n 1 taq install
```

Another thing to check is what project the sandbox was started in. When you start a sandbox, it creates the required accounts and keys for that particular project in `config.json`. If you then try to use that running sandbox in another project, things will fail as the accounts on the sandbox are not relevant for the other project. In this case, simply stopping all running sandboxes, and then starting one again from the current project should help

Let us know if these suggestions resolve your issue. If not we can dive in further

Thanks!

**Comment by avysel** [comment]
It's a new project, and it's my first Taqueria project, so there is no older version or other project on my computer. 

I've run the command to update plugins, but I still have the problem

**Comment by jchenche** [comment]
@avysel do you have docker installed and running?

**Comment by avysel** [comment]
Yes, Docker is running. And a container with taq-flextesa-local-xxxxxxxxxx image is also running on port 20000

**Comment by jchenche** [comment]
@avysel cleaning the docker image might help. Try that and see. I recall having this issue and it was resolved by cleaning the image.

I am on MacOS arm64 M1 as well.

**Comment by hu3man** [comment]
Hi @avysel, Taqueria v0.24.1 has been released and has a new plugin `@taqueria/plugin-core` which has a new task `taq clean` which will clear stale images and state. You can find instructions for updating Taqueria on the release page: https://github.com/ecadlabs/taqueria/releases/tag/v0.24.1

**Comment by hu3man** [comment]
Thanks for the update @avysel, let us know how you make out with that

**Comment by avysel** [comment]
No problem any more after Taqueria reinstall

**Comment by mweichert** [comment]
Glad you were able to get this working, @avysel. 

Feel free to touch base if you run into any other issues.
