### ISSUE TITLE
Remove the quickstart.md file from the taq distribution🐛 Bug ➾ 

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1474]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [x] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

When you taq a project, taq deploys a "quickstart.m" file.

This can be unclear, as the user expects a file about their project, etc.

Please remove the file from the distribution. Scaffolds have their readmes so that nothing will be lost.

### 🆘 Steps to Reproduce?

1. $ cd  myAwesomeTezoProject
2. $ taq init
3.  observe a quickstart.md is added to the project root.

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.23.6-rc.1

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@jchenche @mweichert , can one of you please provide an estimate of how much work this would be?

**Comment by jchenche** [comment]
@hu3man pretty simple I think. It just amounts to removing a file from first glance.

**Comment by hu3man** [comment]
Great, I'll pull in as `low-hanging-fruit`
