### ISSUE TITLE
🐛 Bug ➾ taq compile does not traverse sub dirs in contract folder to find linked contracts.

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1484]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

Related to: #1462 

### 🆘 What happened?

I set up a project to use the nft assets contract set at:  https://github.com/oxheadalpha/smart-contracts/tree/master/nft_assets

When I asked taq to originate the contracts, it could not find the main contract I asked to compile

if run from the directory that has the file, taq fails to find some imports from other files.

### 🆘 Steps to Reproduce?

1. put this collection of files into the contracts dir in a taq project:  
![image](https://user-images.githubusercontent.com/78441942/201758048-acada7a9-cdf1-4f1b-a1c0-536ccf9cb1dc.png)
2. you will have to make dirs and copy folders from dirs as the repo uses symbolic links.
3. the new project should look like this: 
![image](https://user-images.githubusercontent.com/78441942/201758930-a18208b4-229f-4024-a35a-2dff9bd6c651.png)4. 
4. run:
taq originate fa2_nft_asset.mligo 
taqueria complains, suggesting a plugin is missing

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.23.6-rc.1

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Related to: #1462

**Comment by michaelkernaghan** [comment]
I'm going to close this pending further research. I may have made an error in the setup.

I have redone the repo as flat files all on the same level, and it gets a Michelson comb missing error, which is likely nothing to do with taq,

If this is still a problem, I'll post another issue.
