### ISSUE TITLE
🐛 Bug ➾ taq v0.24.1 including ligo v0.55 where test framework points to lima protocol

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#1498]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Hi,

last version of ligo v0.55 uses lima protocol for its test framework
It means that ligo tests should be on lima syntax, and so the source code should be also on lima protocol.

I discussed here internally, and there is no possibility to have Test lib on multi protocols (like the compilation does). So ligo team will have to specify which ligo binary refers to which Tezos protocol (for this reason). We are trying to find another elegant fix but it is still in discussion (thinking about LTS, stable and pre release tags, indicating the target protocol,etc ...)

What it means is that current developers will not be able to deploy code on ghostnet/mainnet using ligo 0.55 (if syntax is different from lima, there is a bug I found today on ticket creation drift) becaus it is still on K protocol.

I would recommend for now for taqueria ligo plugiin to point to ligo v0.54.1 (where test framework in on K protocol)

ps : this is kinda reason why we should be able to install a specific binary of ligo :/ , in my case, I am testing some feature on n+1 protocol and I need to download the correct ligo binary for it

### 🆘 Steps to Reproduce?

run my training n°3 with taqueria 0.24.1, it will fail due to this

### 🐘 How impactful is this bug?

🚒 Showstopper

### 🌮 Taqueria Version

0.24.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@jchenche , please have a look at this

**Comment by hu3man** [comment]
Closing: fixed in Taqueria v0.24.2
