### ISSUE TITLE
🐛 Bug ➾ Plugin gets invalid name if Plugin.create(...) not in root dir

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taqueria#1512]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

If `Plugin.create(...)` is called in sub-directory (not root plugin directory) then the plugin gets some random name when installed using `taq`.

This is most likely because of stack [trace parsing when loading a plugin](https://github.com/ecadlabs/taqueria/blob/3460d4c99139e2c4477047f81b8e7d8f1f2e060d/taqueria-sdk/index.ts#L598-L613)

### 🆘 Steps to Reproduce?

1. Create a plugin `foobar`.
2. Create its `index.js` with code: `require('./dist/plugin-def.js');`
3. Create `dist/plugin-def.js` and define your plugin there using taqueria node SDK.
4. Publish it to NPM repo.
5. When you `taq install foobar`, the name `foobar` will be ignored and random name will be assigned.

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### 💻 Operating System

Windows -> WSL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@mweichert, can you have a look and add some context here?

**Comment by mweichert** [comment]
@psmolinsky 

In the arguments to `Plugin.create` you can include a name field: `Plugin.create({name: "npm package name goes here"})`.

If you leave out the `name` property then we will try to find the package.json file associated with your plugin and infer it from there, but that only works if the Plugin.create call is called from within a file located in the root of your NPM package.
