### ISSUE TITLE
🚧 Dev ➾ Improvements to TVsCE

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1552]
### 🚥 Definition of Done

- [x] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

In preparation for the demo, I identified a few small features that can make the DX (and the demo) much better. There is also a concurrency bug that can really hurt UX.

### ✅ To Do

- [x] Open contracts when user double-clicks on a contract in Taq sidebar
- [x] Same as above for artifacts
- [x] Fix the bug: If the user clicks on an action on an item in Sanboxes treeview (invoke entrypoint, or show details) and the VsCode is in the process of refreshing the treeview, bad behavior is observed. Depending on how slow the computer is, this can happen in one out of three clicks, which is annoying (#1268 )

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] 
- [ ] 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Linking to the bug ticket and moving to the Eng Backlog
