### ISSUE TITLE
🌋 E|F ➾ Implement Google Analytics for VSCE events ex-CLI

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1553]
### 🚥 Status

- [x] 🔮 Product/Feature Design
- [x] ✍🏻 Architecture/Implementation Planning
- [x] 🏗️ Under Construction
- [x] ⛳ Feature Complete
- [ ] ⛵ GTM / Release

### ✅ To Do

- [ ] Collect analytics for events in the TVsCE that do not call the CLI
     - [ ] When the extension loads
     - [ ] When a project is opened
     - [ ] When a micheline editor is opened
- [ ] (OPTIONAL) Ability to correlate a single user interaction in TVsCE and the CLI: for instance, if the user selects to `compile contract (choose file`, and cancels out of this, we have no CLI event, so ideally a TVsCE event should be logged. But then if they complete the task, we have two separate events. The ability to correlate these GA should have a way to track multiple stages of the same interaction, maybe with a uuid.

### 📐 Feature Description

TVsCE can be installed in a machine that does not (yet) have taq cli.
Also, some of interactions inside TVsCE do not call the CLI.

For these, having independent GA events can help measuring user engagement.

### ⚖️ Acceptance Criteria

✨ Features :
- A field indicating if the task was invoked via VsCE
- GA Events send on UI events for GA (essentially tracking the usage of the GUI)
- A field which indicates if a CLI task was invoked via VsCE (command pallet)
-An error event with a payload containing non-identifiable, error-related fields that could be used to group and sort errors by type/class, and frequency

### 🔭 Scope

🏎️ In Scope: 
- Updating the Taqueria codebase to send the new fields (CLI and VsCE)
- Updating GA to handle the new data points 

 🙅‍♂️ Out of Scope: 
- Additional 3rd party tools (Jupityr notebooks, Sentry, BugSnag, etc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Done
