### ISSUE TITLE
🌋 E|F ➾ Build out Deno Unit testing to achieve better coverage of the codebase

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1561]
### 🚥 Status

- [ ] 🔮 Product/Feature Design
- [ ] ✍🏻 Architecture/Implementation Planning
- [ ] 🏗️ Under Construction
- [ ] ⛳ Feature Complete
- [ ] ⛵ GTM / Release

### 📐 Feature Description

Whereas:

1. Taqueria uses Deno, and Deno has full unit test support, including Sinon for mocking. ([Testing | Manual | Deno](https://deno.land/manual@v1.28.2/basics/testing)) as well as a debugger (https://deno.land/manual@v1.9.2/getting_started/debugging_your_code)
2. The current E2E regime does not scale ( see #1555), and we can resolve much of the duplication by moving some testing to unit tests
3. Devs need a more concise and comprehensive pre-commit test suite.
4. Turn around time for corrections to the test suite in the CICD needs to be improved.
5. Deno only speaks Uint8arrays. We need to test the translation from these to output text to relieve having to match expected outputs comprehensively.
6. Present unit test coverage is not enough to be able to support a badge on the repo( see attached coverage report)

7. It needs to be more apparent why there are two test runners.
	- Have to support both
	- Have to explain how to use each
	- Have to test both
	- Can all the testing be done with Deno, and can Jest be dropped?
	
8. A reviewer from the Tezos Foundation was concerned about the tests in Taquito and asked for specific changes, which we carried out. It is a good bet a similar reviewer will not be impressed by the paucity of unit tests,

Be it resolved that:

	We expand the Unit Test Suite for Taquieria to get good coverage of functions and exceptions more quickly, and we use Jest.

### 🚩 Problem or Use Case

See statement of whereas above.

See coverage report. Unzip the archive and click index.html to open the report in a browser.

[taqueria_coverage_html.zip](https://github.com/ecadlabs/taqueria/files/10114381/taqueria_coverage_html.zip)

### ⚖️ Acceptance Criteria

✨ Features: 
- [ ] ... 
 
 📚 Docs: 
- [ ] ... 

### 🔭 Scope

🏎️ In Scope: 
- ... 
 
 🙅‍♂️ Out of Scope: 
- ... 
 
 

### 🔗  Related Issues and Subtasks

[ ] #1578

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jchenche** [comment]
From our meeting, it seems that we've agreed to drop DENO and go full JEST, right? @egarson

**Comment by michaelkernaghan** [comment]
yeah should be ok to do so going forward.

**Comment by michaelkernaghan** [comment]
dropped
