### ISSUE TITLE
🚧 Dev ➾ Syntax highlighting of Michelson in VS Code

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1564]
### 🔗 Epic|Feature Link

https://github.com/ecadlabs/taqueria/issues/1495

### 🚥 Definition of Done

- [X] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

This ticket covers the work involved in developing a static grammar file generator and then integrating the grammar files into the Taqueria VsCE

### ✅ To Do

- [ ] Work with @AlirezaHaghshenas to integrate the language definition files into Taqueria VsCE (d: @archaephyrryx)

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] Implement full support for any tokens that are not a reserved word
- [x] Support for raw tokens
- [ ] Integration of definition files
- [ ] Generator script exists in an ECAD git repo and Taqueria team members are able to clone and run locally
- [ ] A system for generating definition files and integrating changes to Taqueria is developed and documented as part of release process

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- Lensing tooltips
- LSP server
- CI integration
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jevonearth** [comment]
Based on standup;

@AlirezaHaghshenas will split this ticket;
1. for merging the ecosystem def file (from BCD I believe)
2. For switching to our generated one when that is ready (from @archaephyrryx )

**Comment by AlirezaHaghshenas** [comment]
The remaining work moved to #1700 . Closing this as done.
