### ISSUE TITLE
🚧 Dev ➾ On compile, emit additional files only if a *main function* is present

### ISSUE THREAD

**Issue by egarson** [ecadlabs/taqueria#1572]
### 🧰 Work Description

When I compile an arbitrary file using taq compile xyz.mligo the tool emits xyz.{parameter,storage}List.mligo` (what I'll refer to as, "additional files").
It assumes that I'm writing a contract, for which yes I might like those additional files.
However, many contract projects use multiple files per "actual" contract, so all these extra files are slightly inconvenient while well-intentioned.

### ✅ To Do

Have `taq` scan for a *[main function](https://ligolang.org/docs/advanced/entrypoints-contracts/?lang=cameligo)*  within the compilation target, and if found only then produce the additional files.
The `ligo` tool provides a way to list the functions in a given source-file:
`ligo info list-declarations <file-name.mligo>`
If `main` is listed therein, at that point `taq` should generate the additional files.

### ⚖️ Acceptance Criteria

Compiling arbitrary files does not produce the additional files.
Compiling any file with a main function produces the additional files.

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Innkst** [comment]
We can't use the function from ligo to check if there is "main" function or the substitute.
Right now, it works with 'main' though.
