### ISSUE TITLE
🐛 Bug ➾ cannot uninstall ligo plugin without error 

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1574]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

tried to uninstall the ligo plugin and it gives error
"The @taqueria/plugin-ligo plugin experienced an error when getting information about the @taqueria/plugin-ligo plugin."

Lack of self-awareness?

### 🆘 Steps to Reproduce?

1.   taq install @taqueria/plugin-ligo
2.  verify it installed ok
3.   taq uninstall @taqueria/plugin-ligo
4.  "The @taqueria/plugin-ligo plugin experienced an error when getting information about the @taqueria/plugin-ligo plugin."

### 🐘 How impactful is this bug?

🤯 Major disruption

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.24.2

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing: edge case
