### ISSUE TITLE
🐛 Bug ➾ rewrite tests in taqueria-cli-permissions.spec.ts to use cli-test-library

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1593]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Moving on to the following test file to update.

### 🆘 Steps to Reproduce?

this is not a bug, it is some work, but not a dev task.

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

tests need upgrades

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.24.2

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing in favour of dev task
