### ISSUE TITLE
🚧 Dev ➾ Deprecate the core plugin

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#1594]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

With the completion of refactoring internal tasks nearly ready (https://github.com/ecadlabs/taqueria/issues/1342), I'm wondering if we should nix the core plugin.

I think that the core plugin might cause more headaches than solve problems:

- It's slowing down taq init, as we're fetching the package from the network. This adds unnecessary latency.
- It causes problems with refactors and scaffolds. Any time we make a change to the codebase that could break the core plugin, such as a rename a method in the SDK, we cannot use taq init to create a project without manually reinstalling the core plugin from your local Taqueria git clone.
- It's something we will always have to be concerned about with upgrades. For instance, when we release the prerelease-0.25.0 branch, we will need to add instructions for users to update their core plugin any time they taq init a new project. We'll also need to provide instructions to update all plugins for any existing Taqueria project.

I think now is the time to do this, as it will be a lot more difficult to change later on.

### ✅ To Do

- [ ]  Move the _clean_ task to an internal task
- [ ] Add a means of blacklisting plugins. Blacklisted plugins aren't loaded.
- [ ] Add a line to the execution pipeline which detects the core plugin and removes it when taq is executed. We can leave this line intact for a year or so and then remove it.

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ]  _clean_ task is only exposed once, regardless of whether the core plugin is present
- [ ] if taq is invoked in a project that has the core plugin installed, its automatically removed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jchenche** [comment]
I think it doesn’t make sense to nix the core plugin. Whatever problem you mentioned are shared by both the core plugin and other plugins. The only difference is that the core plugin gets installed automatically on `taq init`. It should be treated like other plugins. So if we are sticking with having separate plugins outside of the TAQ binary, we should keep it, and if we take Ali’s suggestion of moving all plugin functionalities to the TAQ binary, we should nix all of them.

I believe the benefit of this separation outweighs the additional latency of `taq init`. It keeps the TAQ binary more like a pure task runner.

IMO, it only makes sense to either nix all plugins if and when we take Ali's approach or nix none of them. @AlirezaHaghshenas @mweichert @egarson

**Comment by AlirezaHaghshenas** [comment]
I'm always in favor of simplicity:
Support plugins, but ship all ECAD code in one binary, create a **separate** repo that has a sample plugin.
Benefits:

- Far less code for us to develop and maintain
- Faster build times
- Faster tests (no need to install plugins)
- Fewer version incompatibility problems (in tests and for actual users)
- Easier usage for users
- Among others
I can think of no major drawback
