### ISSUE TITLE
🚧 Dev ➾ Refactor NFT-Scaffold 

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1617]
### 🚥 Definition of Done

- [X] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

In order to make the NFT-Scaffold representative of the current functionality of Taqueria and to demonstrate best practices in dApp development. Currently, it includes a lot of custom code that calls the existing and unfinished provisions and state features. This does not represent what a user could reasonably edit to modify the scaffold for their own usage and we need to refactor it to use only released Taqueria features

There is also the issue where there is a separate `/taqueria` dir which is incongruent logically, and does not represent the best practices for Taqueria

### ✅ To Do

- [ ] Determine a viable approach for solving the NPM issue that prevents `create-react-app` from being used with a root `.taq` folder (d: @mweichert s: @AlirezaHaghshenas @egarson)
- [ ] 

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] A single `.taq` folder exists in the root of the project
- [ ] All code in the project uses only features currently available in Taqueria (remove all provisions/state code)
- [ ] Scripts that call relevant Taqueria tasks to set up the project are added
- [ ] A SmartPy contract with SmartPy native tests is added to the project
- [ ] Token indexing via VsCE is implemented
- [ ] Aliasing for RPC, Account/contract addresses, Network type, and all other config values are passed to the dApp via `@taqueria/toolkit`

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- Work on taco-shop
- 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by egarson** [comment]
Doing an `npx create-react-app <pwd>` results in, `Either try using a new directory name, or remove the files listed above`. 
The "files listed above" are not removable, so I closing this for now.
