### ISSUE TITLE
🚧 Dev ➾ Rework test used to verify that `generate types` output is correct/expected

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#1625]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

The following tests was skipped as the contract referenced (timelock.tz) uses a deprecated michelson instruction, OPEN_CHEST:

```
// Skipping for now due to OPEN_CHEST being a deprecated instruction in Michelson, but used in the timelock contract.
	test.skip(
		'Verify that users can properly use the generated types (involves origination to a testnet and calling an entrypoint, which will take a while)',
		async () => {
			await exec(`cp e2e/data/increment.tz ${taqueriaProjectPath}/artifacts`);
			await exec(`taq generate types`, { cwd: `${taqueriaProjectPath}` });
			await exec(`cp e2e/data/timelock.ts ${taqueriaProjectPath}/types`);
			await exec(`cp e2e/data/tsconfig.timelock.json ${taqueriaProjectPath}/types`);
			await exec(`npm init -y`, { cwd: `./${taqueriaProjectPath}/types` });
			await exec(`npx tsc --project tsconfig.timelock.json`, { cwd: `./${taqueriaProjectPath}/types` });
			const { stdout, stderr } = await exec(`node timelock.js`, { cwd: `./${taqueriaProjectPath}/types` });
			expect(stdout).toBe('initialStorage: 00 , newStorage: 050080890f\n');
			expect(stderr).toBe('');
		},
	);
```

### ✅ To Do

One suggestion was to rewrite the test to use increment.tz instead.

### ⚖️ Acceptance Criteria

- Test is effective at determining whether `generates types` is generating the expected output

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
Moved this into E2E test review

**Comment by michaelkernaghan** [comment]
Verify it should have been closed by merge of PR  https://github.com/ecadlabs/taqueria/pull/1626
