### ISSUE TITLE
🐛 Bug ➾ E2E Test Bug:  remove node deprecation message in cicd output 

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1628]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

In a CICD run, the new package for managing cli test environments is throwing a deprecation notice: 
``` 
(node:5398) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
```
make this go away

### 🆘 Steps to Reproduce?

Run e2e tests  taqueria-cli-other-and-mixed-plugin-commands.spec.ts and observe the deprecation notice.

### 🪵 Relevant log output

```shell
(node:5398) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
```
```


### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.24.1

### 🌿 Node.js Version

v18.4.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
No longer relevant as test spec was removed. I searched and there are no more mentions of `.rmdir` in any of the test specs.
