### ISSUE TITLE
🐛 Bug ➾ calling `taq -p project-dir`  in project-dir gets error "Your config.json file is invalid"

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1634]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I was checking the behaviour described in #528, and I found that calling `taq -p project-dir`  in project-dir gets the error "Your config.json file is invalid."

### 🆘 Steps to Reproduce?

1. taq init test-project
2. cd test-project
3. taq -p test-project
4. ERROR: "Your config.json file is invalid."

### 🪵 Relevant log output

```
❯ taq -p test1
taq [command]

Commands:
  taq init [projectDir]                     Initialize a new project
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold
  taq opt-in                                Opt-in to sharing anonymous usage an
                                            alytics
  taq opt-out                               Opt-out of sharing anonymous usage a
                                            nalytics

Options:
  -p, --projectDir  Path to your project directory               [default: "./"]
  -e, --env         Specify an environment configuration
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]

Taqueria is currently in BETA. You've been warned. :)

Your config.json file is invalid
```

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

an edge case that proves a flaw

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

dev-main

### 🌿 Node.js Version

v17.9.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by egarson** [comment]
This defect also appears if you type `taq` (only) or `taq help`

**Comment by mweichert** [comment]
Cannot reproduce.
