### ISSUE TITLE
🐛 Dev Task ➾ Fix tests that assert contextual help is displayed

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1635]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

The existing E2E tests were managing to invoke contextual help while my simplified rewrite was not succeeding. It turns out that the contextual help only comes in stderr and won't appear if you use the --help flag with or without the --projectDir param. If I set the test to call 'taq originate', provoking an error by missing the parameter, I get contextual help. 

### 🆘 Steps to Reproduce?

1. taq init test-project
2. cd test-project
3. taq install @taqueria/taqueria-plugin-ligo@next
4. taq compile --help 
5. gets contextual help!
6. taq compile --help --p test-project
7. Does not show contextual help

### 🪵 Relevant log output

```shell
❯ taq compile --help -p test1
taq [command]

Commands:
  taq init [projectDir]                     Initialize a new project
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold
  taq opt-in                                Opt-in to sharing anonymous usage an
                                            alytics
  taq opt-out                               Opt-out of sharing anonymous usage a
                                            nalytics

Options:
  -p, --projectDir  Path to your project directory               [default: "./"]
  -e, --env         Specify an environment configuration
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]

Taqueria is currently in BETA. You've been warned. :)
```

### 🐘 How impactful is this bug?

🤯 Major disruption

### ⏱️ Prevalance

anyone looking for contextual help

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

dev-main

### 🌿 Node.js Version

v17.9.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
This is a roadblock to a large class of tests.

**Comment by michaelkernaghan** [comment]
seems to be a timing error in the tets.
The call for contextual help is made before the plugin loading is fully completed.

will redo tests to repair this.

**Comment by mweichert** [comment]
@michaelkernaghan and I hopped on a call and found that this was related to two things in the tests:
- The `--projectDir` flag needed to be removed, as the test was already executing within the `test-project` as its working directory
- We found that some time needs to elapse between a) installing a plugin, and b) executing a task provided by that plugin
