### ISSUE TITLE
🚧 Dev ➾ Conditional integration tests in CICD

### ISSUE THREAD

**Issue by GImbrailo** [ecadlabs/taqueria#1714]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [X] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

As a developer, I do not want integration tests to run in CICD on every push to the branch. Having a condition in the `testing` jobs to run integration tests when the branch name or commit message contains a specific string like `integration-tests` would be a good solution to this. 

### ✅ To Do

- [ ] Add a condition to the integration test job in CICD

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] Integration tests must be skipped in the absence of "integration-tests" in the commit message
- [ ] Integration tests should run if the commit message contains "integration-tests"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
I changed my mind about this one, and we will not be doing this anymore. Please close.

**Comment by michaelkernaghan** [comment]
no longer required, thanks
