### ISSUE TITLE
🐛 Bug ➾ Link to flextesa-plugin documentation is a 404

### ISSUE THREAD

**Issue by egarson** [ecadlabs/taqueria#1749]
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [x] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

"... the Flextesa documentation _here_" is a 404. It should point to the Flextesa plugin documentation.

This is on the https://taqueria.io/docs/config/networks/ page to be sure.

### 🆘 Steps to Reproduce?

Go to https://taqueria.io/docs/config/networks/ and click on the hyperlink describe above.

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Fixed.
