### ISSUE TITLE
🚧 Dev ➾ Refactor Taco-Shop Scaffold to Support New `config.json` Schema

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1753]
### 🚥 Definition of Done

- [X] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

With the major refactor to `config.json`, the `taco-shop` scaffold does not work with the current prerelease. In order to have a stable v0.26.0 release, this scaffold must be refactored to support the new schema and be tested with the prerelease versions of plugins

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] All files in `.taq` are of the new schema
- [ ] The scaffold works as expected with the prerelease binary and plugins
- [ ] Hot-reload works via aliases as expected (the alias for the environment defined as `defaultEnvironment` in `config.json`)
- [ ] dApp uses the RPC URL associated with the `defaultEnvironment`

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by egarson** [comment]
I may have inadvertently fixed this :laughing: - I am using the new schema successfully now after resolving a couple of hiccups.

**Comment by mweichert** [comment]
Done
