### ISSUE TITLE
🐛 Bug ➾ taqueria plugin task deploy will not work unless core-plugin is loaded.

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1776]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I want to deploy a contract using Taquito plugin, but unless I load the core plugin first it does not work. but this should not be required.

### 🆘 Steps to Reproduce?

1. set up a project -- taq init test-project, cd test-project, etc
2. set up contracts ready for Taquito plugin deploy - orginated .tz file in the artifacts folder
3. taq deploy hello-tacos.tz --storage anyContract.storage.tz -e testing  (for example)
4. get the error: '  'The @taqueria/plugin-core plugin experienced an error when getting information about the @taqueria/plugin-core plugin.''
5. install the core plugin
6. redo the call to deploy
7. it works now

### 🪵 Relevant log output

```shell
[
      'node:internal/modules/cjs/loader:936',
      'throw err;',
      '^',
      "Error: Cannot find module '{{base}}/test-project/node_modules/@taqueria/plugin-core/index.js'",
      'at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)',
      'at Function.Module._load (node:internal/modules/cjs/loader:778:27)',
      'at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)',
      'at node:internal/main/run_main_module:17:47 {',
      "code: 'MODULE_NOT_FOUND',",
      'requireStack: []',
      '}',
      'taq [command]',
      'Commands:',
      'taq init [projectDir]                     Initialize a new project',
      'taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad',
      'ectDir]                                   e scaffold',
      'taq opt-in                                Opt-in to sharing anonymous usage an',
      'alytics',
      'taq opt-out                               Opt-out of sharing anonymous usage a',
      'nalytics',
      'Options:',
      '-p, --projectDir  Path to your project directory               [default: "./"]',
      '-e, --env         Specify an environment configuration',
      '--version     Show version number                                [boolean]',
      '--build       Display build information about the current version[boolean]',
      'Please be advised that Taqueria is currently in BETA.',
      'The @taqueria/plugin-core plugin experienced an error when getting information about the @taqueria/plugin-core plugin.'
    ]
```

### 🐘 How impactful is this bug?

🤯 Major disruption

### ⏱️ Prevalance

everytime use taquito deploy

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

arm64 (M1 Macs)

### 🌮 Taqueria Version

dev/main

### 🌿 Node.js Version

v16.16.0

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jchenche** [comment]
@michaelkernaghan and I looked at it and the problem actually arose from the e2e test config files. Some of them are wrong because they include plugins such as CORE.
