### ISSUE TITLE
🐛 Bug ➾ "Yes to all" does not answer yes 

### ISSUE THREAD

**Issue by egarson** [ecadlabs/taqueria#1778]
### 🚥 Status (Internal Taqueria Team Use Only)

- [X] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Using the `--yes` flag does not appear to work:

➜  taqueria-scaffold-taco-shop ✗ taq opt-in
Help improve Taqueria by sharing anonymous usage statistics in accordance with the privacy policy? (Y/n) Y
You have successfully opted-in to sharing anonymous usage analytics
➜  taqueria-scaffold-taco-shop ✗ taq opt-in -Y
Help improve Taqueria by sharing anonymous usage statistics in accordance with the privacy policy? (Y/n)
You have successfully opted-in to sharing anonymous usage analytics
➜  taqueria-scaffold-taco-shop ✗ taq opt-in -y
Help improve Taqueria by sharing anonymous usage statistics in accordance with the privacy policy? (Y/n) Y
You have successfully opted-in to sharing anonymous usage analytics
➜  taqueria-scaffold-taco-shop ✗ taq opt-in --yes
Help improve Taqueria by sharing anonymous usage statistics in accordance with the privacy policy? (Y/n) Y
You have successfully opted-in to sharing anonymous usage analytics
➜  taqueria-scaffold-taco-shop ✗ taq opt-in --y
Help improve Taqueria by sharing anonymous usage statistics in accordance with the privacy policy? (Y/n) Y
You have successfully opted-in to sharing anonymous usage analytics

### 🆘 Steps to Reproduce?

As above.

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

Anytime you try to use -Y

### 💻 Operating System

None

### 🕸️ System Architecture

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Verified that this is fixed in 0.28.6.
