### ISSUE TITLE
🚧 Dev ➾ Adjust `compile-all` task to compile files using dependency graph to identify top-level files. Support @entry annotation

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#1864]
### 🚥 Definition of Done

- [X] 🎯 Planning and Design
- [X] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

The original `compile-all` task was designed to compile files that had a main function. However, it was not properly identifying the @entry annotations, which serve as the equivalent of a main function in LIGO smart contracts. Moreover, this approach led to some files with helper functions and modules being skipped during the compilation process, potentially causing issues in the overall smart contract functionality. The `compile-all` and `compile` tasks need to be updated accordingly to support the new `@entry` annotation.

In order to provide a more comprehensive compilation process and ensure that only the relevant contract files are compiled, we have extended the `compile-all` functionality to use a dependency graph and an adjusted criterion for identifying top-level files. This criterion includes checking for the presence of an @entry or main function in the file and ensuring that the file is not included by any other file.

The changes made include:

1. Iterating through all the files in the contracts directory.
1. Analyzing the #include directives for each file to determine its dependencies and checking if it contains an @entry or main function.
1. Building a dependency graph using this information, where each node represents a file, and the directed edges represent the dependencies between files.
1. Identifying the top-level files that contain an @entry or main function and are not included by any other file in the dependency graph.
1. Passing each top-level file to taq compile [sourceFile].
1. By using this adjusted approach, we can differentiate between contracts and modules, ensuring that only the correct files are compiled. This approach also takes into consideration the deliberate intent to compile only contracts and not helper functions.

Some considerations to keep in mind while implementing this approach are:

1. Ensuring that there are no circular dependencies in the graph. If a circular dependency is detected, the process should either stop and report an error or warn the user and continue with the other files.
1. Handling cases where a file is included multiple times by making sure the dependency graph doesn't have duplicate edges or nodes.
1. Resolving relative and absolute paths in #include directives to ensure the correct files are being included.

Overall, this approach is more robust in identifying top-level contract files, handling potential issues with file dependencies, and providing a more complete compilation process that covers all necessary contract files in the project directory. This ensures that only relevant contracts are compiled, resulting in a more robust and reliable smart contract implementation.

### ✅ To Do

- Adjust `compile` task
- Adjust `compile-all` task
- Write E2E tests

### ⚖️ Acceptance Criteria

- `compile-all` can find all top-level source files which are contracts based on their dependency graph and inclusion of an `@entry` annotation or `main` function.
- E2E tests assure that compile-all is working as it should

### 🔭 Scope

🙅‍♂️ Out of Scope: 
These changes are limited to the LIGO plugin
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zamrokk** [comment]
not sure is the output is what is expected

BEFORE

![image](https://github.com/ecadlabs/taqueria/assets/2536368/406226da-bc18-4d5e-8fd6-2abafd7a3191)


AFTER

![image](https://github.com/ecadlabs/taqueria/assets/2536368/4131d3ad-31dd-4efa-be7b-b06022f3ccb8)
