### ISSUE TITLE
🐛 Bug ➾ taqueria does not support LIGO Option.value, Option.is_none and maybe other functions

### ISSUE THREAD

**Issue by ztepler** [ecadlabs/taqueria#1868]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Assuming that I have the following contract written in JsLIGO, named `setter.jsligo` in the `contracts` directory:
```
type parameter =
    | ["Set", option<nat>]
    | ["Reset", unit];

const main = (action: parameter, _s: nat) : [list<operation>, nat] => [
    list([]),
    match(action, {
        Set: (amount: nat) => Option.value((42 as nat), amount),
        Reset: () => (0 as nat)
    })
];
```

When I try to compile contract by running command
```
taq compile setter.jsligo
```

I am getting the following error:
```
=== Error messages for setter.jsligo ===
File "contracts/setter.jsligo", line 8, characters 30-42:
  7 |     match(action, {
  8 |         Set: (amount: nat) => Option.value((42 as nat), amount),
  9 |         Reset: () => (0 as nat)

Variable "value" not found. 


===
┌───────────────┬──────────────┐
│ Contract      │ Artifact     │
├───────────────┼──────────────┤
│ setter.jsligo │ Not compiled │
└───────────────┴──────────────┘
```

### 🆘 Steps to Reproduce?

1)
```
taq init taq-option-bug-reproduce --workflow ligo
cd taq-option-bug-reproduce
```
2) create file `contracts/setter.jsligo` with following content:
```
type parameter =
    | ["Set", option<nat>]
    | ["Reset", unit];

const main = (action: parameter, _s: nat) : [list<operation>, nat] => [
    list([]),
    match(action, {
        Set: (amount: nat) => Option.value((42 as nat), amount),
        Reset: () => (0 as nat)
    })
];
```
3)
```
taq compile setter.jsligo
```

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

reproduces every time I run compile

### 💻 Operating System

Linux

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.28.5-rc

### 🌿 Node.js Version

v16.20.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ztepler** [comment]
Additional info: I am able to compile contract manually using ligo `0.63.2` with following command:
```
ligo compile contract contracts/setter.jsligo
```
To get the following Michelson code:
```
{ parameter (or (unit %reset) (option %set nat)) ;
  storage nat ;
  code { CAR ;
         IF_LEFT { DROP ; PUSH nat 0 } { IF_NONE { PUSH nat 42 } {} } ;
         NIL operation ;
         PAIR } }
```

**Comment by ztepler** [comment]
I was able to compile the contract by setting `TAQ_LIGO_IMAGE` environment variable to the `ligolang/ligo:0.63.2`:
```
export TAQ_LIGO_IMAGE="ligolang/ligo:0.63.2"
```

It works fine and compiles both Option.value and Option.is_none. The problem appears to be related with the LIGO image used in Taqueria v0.28.5-rc. I am not sure, should I close this issue then?

**Comment by mweichert** [comment]
Thanks for the additional information. Please leave this open for now and
we will close it when we update the image. Thanks!

**Comment by mweichert** [comment]
Taqueria 0.28.6 now uses ligolang/ligo:0.63.2 will we can close this issue.
