### ISSUE TITLE
Create e2e tests for smartpy plugin command

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#204]
### Description
As an SDET, I want to provide quality for the smartpy plugin, so I need to create tests for each command implemented by the plugin.

#### Acceptance Criteria
- [ ] Test for command compile
- [ ] Test for compile fileName

**Comment by alexzbusko** [comment]
@russellmorton @hu3man I think this can be closed, we have these tests already for the smartpy plugin covered in https://github.com/ecadlabs/taqueria/issues/229

**Comment by russellmorton** [comment]
Thanks @alexzbusko.

Closing. Covered in #229
