### ISSUE TITLE
Artifacts Registry System/State and API

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#210]
As a smart contract developer, I want identifiers (common across the dapps, tests, environments and networks) for accounts, contracts and IPFS content scoped by network, with tracking of state.

**BACKGROUND:**
Being really clear at the outset of this is important because I think that we would need to create apis to this data in multiple languages in order for Taqueria to have multi-language support. 

**USES CASES**

- Smart contract that address needs to be in React app
- Have multiple dependent smart contracts
- Contract with metadata that needs to be sent to IPFS first
- If I was using Java, and I originate a new contract using the java lib/plugin, I would want to update the state via native java API/object and read that data too. Example languages: Go and Java.
- As a developer, I want to be able to refer to another smart contract address in the initial storage of another contract. I don't want this to be hardcoded.
- As a tester, I want to be able to refer to an implicit account in my test case as well as refer to other contracts addresses
- An asset contract and simulate 100k unique token holders

**SOLUTION OPTION**

Dependency graph

**ACCEPTANCE CRITERIA**

- [x] Track implicit accounts (tz1, tz2, tz3 addresses)
- [x] Track originated accounts (KT1 addresses)
- [ ] Generate new accounts on demand
- [ ] Support for global constants ([Taquito support](https://tezostaquito.io/docs/global_constant/))
- [ ] Support for tickets
- [x] Ability to reference named contract
- [x] Ability to reference named accounts
- [ ] Track and update changes across all networks and environments
- [x] State persists in a JSON in .taq directory

**ISSUES:**
- [x] #548
- [x] #549
- [x] #617 
- [x] ~#523~
- [x] #431 

**DEFERRED TO LATER ITERATION**

- [x] #544 
- [x] #545 
- [ ] #546

**Comment by russellmorton** [comment]
- State persisted as JSON in .taq directory

- Addresses - implicit, originated, _sapling_ accounts (tz and KT addresses)
- Keygen API - rewritten as a Taqueria plugin
 - used to generate accounts or provide named wallet account
 - generate new accounts on the fly
 - Use case: asset contract and simulate 100k unique token holders

**Comment by russellmorton** [comment]
As part of my deployment process, I want to call [endpoint] on [contract] with [value]

**Comment by mweichert** [comment]
As a developer, I want to be able to refer to another smart contract address in the initial storage of an other contract. I don't want this to be hardcoded.

**Comment by mweichert** [comment]
As a developer, I want to be able to refer to an implicit account in my test case.

**Comment by russellmorton** [comment]
Deferred to later iteration:

- [ ] Track operation history
- [ ] Track versioning information

**Comment by russellmorton** [comment]
**DEFERRED TO LATER ITERATION**
- [ ] #544
- [ ] #545

**Comment by russellmorton** [comment]
flowchart LR
	N154["START"]
	N155["Originating Contract 5"]
	N156["Contract 4"]
	N157["Big map value from contract 3"]
	N158["Big map value from contract 2"]
	N159["Contract 1"]
	N154 --> N155
	N155 -- "depends on" --> N156
	N156 -- "depends on" --> N157
	N157 -- "depends on" --> N158
	N158 -- "depends on" --> N159
