### ISSUE TITLE
[Feature]: Add Pull Request Template with CLA and Checkbox

### ISSUE THREAD

**Issue by neilmangan** [ecadlabs/taqueria#212]
### Describe the feature you would like

Add a Contributor License Agreement (CLA) to the repository. Add/modify pull request template to require third-party agreement to CLA terms.

### Is this feature solving a problem?

Adding a CLA will clarify and confirm the terms upon which a contributor to the project adds code to the project. Accepting third-party code without a CLA creates uncertainty about ownership and licensing of the contribution. Third-party contributions to Taqueria are expected as the product matures and external parties test the product and develop plugins.

### Please share any additional details you have?

Taqueria CLA should be modelled on Apache Foundation CLA, as adopted for Google open-source projects, etc.
Adding confirmation of CLA terms to pull request template, and confirming agreement for third-party contributors, will allow the project to avoid the use of CLA bots.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing: fixed in #501
