### ISSUE TITLE
Documentation for smartpy plugin to include section that specifies smartpy must be installed locally to function

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#214]
Right now the smartpy plugin for taqueria requires smartpy to be installed locally to function for compiling contracts. This should be added to the documentation with a link to the smartpy cli installation page (https://smartpy.io/docs/cli/)

**Comment by hu3man** [comment]
This is listed in the SmartPy Plugin documentation already https://taqueria.io/docs/plugins/plugin-smartpy
