### ISSUE TITLE
[TASK] Create e2e tests for taqueria cli commands

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#228]
As an SDET I want to provide quality for taqueria cli core commands so I need to create tests for each command implemented.

#### Acceptance Criteria
The tests should cover at least these scenarios:
- [x] Test for command taq --help
- [x] Test for command taq --version
- [x] Test for command taq -e
- [x] Test for command taq --env (same as -e)
- [x] Test for command taq -d
- [x] Test for command taq ---configDir (same as -d)
- [x] Test for command taq -p
- [x] Test for command taq --projectDir (same as -p)
- [x] Test for calling task that does not exist <- Negative scenario
- [ ] Test for calling parameter that does not exist <- Negative scenario

**Comment by alexzbusko** [comment]
The `taq -e|--env` options are currently being used in the PR https://github.com/ecadlabs/taqueria/pull/314 so I will count them complete here with them being used there

**Comment by alexzbusko** [comment]
Same thing with the setting up an environment to fail, this is outside the scope of this task since environment setup is only for the taquito. I have added it to the task https://github.com/ecadlabs/taqueria/issues/201
