### ISSUE TITLE
[TASK] Create e2e tests for smartpy plugins

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#229]
### Description
As an SDET, I want to provide quality for a project that includes both ligo and smartpy plugins so I need to create tests for each command implemented by both plugins

#### Acceptance Criteria
The tests should cover at least these scenarios:
- [ ] Test for command taq compile without specifying plugin name  <- negative scenario
- [ ] Test for command taq compile --pluginName
- [ ] Test for command taq compile fileName --pluginName
- [ ] Test for command taq compile multiple files --pluginName
- [ ] Test for command taq compile wrong file --pluginName

**Comment by alexzbusko** [comment]
This is currently blocked by https://github.com/ecadlabs/taqueria/issues/627 @mweichert @russellmorton @hu3man
