### ISSUE TITLE
Define Usage Analytics

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#23]
### Description
Evaluate the different channels of usage analytics we would like to monitor including:

- [x] #35
- Opt in Taqueria usage analytics
 - VS Code Extension
 - CLI

- [x] #34
- Analytics for Taqueria website
-  Analytics for social media channels
- User feedback on documentation and product
#### Acceptance Criteria
- [x] Channels defined and documented
- [x] Metrics defined and documented in line with the proposal
- [x] Methods of acquiring data defined
- [ ] Legal review by @neilmangan

#### Additional Context and Related Items
- Legal review for all activities

**Comment by hu3man** [comment]
Closing: complete
