### ISSUE TITLE
USER STORY: “Hello world” contract and companion dApp can be compiled, deployed, & tested

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#236]
- [x] #383
- [ ] 
Related: #239

**Comment by mweichert** [comment]
Hey @hu3man!

I've fixed #250 and also pushed a change to the `taqified` branch which takes things a little further by allowing the developer to test the dapp against a deployed version of their contract on the sandbox.

To call this issue done, I think we need to do the following:
- Update our website tutorial to reflect the latest changes to https://github.com/ecadlabs/hello-tacos/blob/taqified/taqification-steps.md
- Discuss with @jevonearth  and @claudebarde  changes that should be made to the main branch to make taqifying steps a little cleaner. I'll list some of them below.

#### Suggested changes to the dapp before taqification:
- Wallet component has an effect which depends on Tezos toolkit: https://github.com/ecadlabs/hello-tacos/commit/f38d482d47c22401e0df87c24b0fad9ce29698ea#diff-d6f57d18eeb2ee4dfe8d83130cf9fe6379912e574ecfb89e61aae8b33927a4d4
- Interface component was deliberately throwing an error. Looks like this was committed by mistake: https://github.com/ecadlabs/hello-tacos/commit/f38d482d47c22401e0df87c24b0fad9ce29698ea#diff-4a8885db596cb729bdfde23119599108193f2006736045d6f468358b72f170c7

**Comment by hu3man** [comment]
This is currently blocked pending a decision about what changes will be made to the app to simplify taq'ifying it

**Comment by russellmorton** [comment]
@hu3man is there an issue we can track against to know when its ready to go?

**Comment by hu3man** [comment]
I don't think so but @mweichert may have one
