### ISSUE TITLE
Create and provide a newcomer documentation

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#237]
**PURPOSE**
Teach users how to start a Taqueria project, understand how Taqueria is used in the Tezos development ecosystem and how to add Taqueria to an existing project by using the scaffolding functionality.

**SCOPE**
- Project scaffolding
- Hello Tacos
- Quickstart project
- New boilerplate project (barebones Taqueria project with Ligo, Flextesa, Taquito and Contract Types)
- Detail usage and workings of each plugin
- Functionality to be covered:
  - Compilation
  - Sandbox lifecycle methods
  - Origination/Deployment 
  - Targe both sandbox and testnet using environment
  - Configuring custom sandboxes
  - Configuring and using networks
-  Type generation
  -  CLI usage
  - How it changes Taquito method calls
  - Using the generated types with IntelliSense and tooltips
  - Compile-time type safety enforcement
- Docker in relation to Taqueria

**REQUIREMENTS**
- [x] #426
- [x] #427
- [x] #428
- [x] #429
- [x] #430
- [x] #439

**NOTE**
LIGO centric by default

**Comment by Innkst** [comment]
All tasks were complete
