### ISSUE TITLE
[Feature]: Create and publish taqueria Github Action

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taqueria#239]
### Describe the feature you would like

I want to have a pre-built Taqueria Github Action that I can use in my Github CI/CD pipelines to easily build, test, deploy my Tezos appliaction.

### Is this feature solving a problem?

Setting up CI/CD for a Tezos application involves a lot of setup, glue-code and plumbing. By making a ready made Taqueria Github Action, we will provide users with a convenient starting point for getting their application running in CI/CD. Reducing friction and overhead for developers to adopt best practices.

### Please share any additional details you have?

As Taqueria is a plugin based system, I think we should make our Github action to include the popular/common plugins used in many projects. The action should be extensible, so a user of the action can, without unreasonable effort, add taqueria plugins that are not present in the Github action image.

Proposed plugins (and dependencies);

- Ligo
- Smartpy
- Taquito
- Contract Types plugin

We should discuss inclusion of Flextesa. I think putting flextesa in the github action will make it too large/unweidly, and it would be better for a Taqueria github action image to depend on a Flextesa container, and those should be composed together in the Github action configuration files.

Github docs on creating Github actions:
https://docs.github.com/en/actions/creating-actions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GImbrailo** [comment]
@hu3man, this work was completed and I think this issue can be cloased

**Comment by mweichert** [comment]
Done
