### ISSUE TITLE
[Bug]: VSCode extension does not compile ligo smart contract through command palette

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#241]
### What happened?

When you run the command to compile a ligo smart contract in the command palette in vscode you run into the error "The @taqueria/plugin-ligo plugin experienced an error when executing the proxy.". When running the same command through the CLI (`taq compile`) there is no issue. This may be due to an error when installing the ligo plugin though the command palette in vscode which just returns "There was a problem running taq."

### What should have happened?

What should have happened is running the latest 0.0.8 release on a linux system/subsystem we should be able to install the ligo plugin through the command palette and then add a ligo contract and compile it through all the vscode extension. 

### Steps to reproduce the bug

Steps to reproduce the error:
1. Download a taqueria binary from the releases page (0.0.8 at the time of writing this) - https://github.com/ecadlabs/taqueria/releases and add it to the path on the machine that will be running the vscode extension
2. Install the taqueria vscode extension in your vscode instance through the marketplace (at the time of writing 0.0.8 is in pre-release)
3. Initialize a taqueria project through the command `taq init {your_project_name}`
4. cd into the directory for your taqueria project
5. Initialize it as a npm project through running `npm init -y`
6. Open up vscode to the taqueria project
7. Open the command palette and select the command "Taqueria: Install Plugin", select ligo. This is where the first error happens where it says that there was an error running taq. There is no output beyond that
8. If you install the taq plugin through the command line through `taq install @taqueria/plugin-ligo` then there is no issue with installation
9. Once the ligo plugin is installed then add a contract to the contracts directory named increment.jsligo with the following inside of it:
```
type storage = int;
type parameter =
| ["Increment", int]
| ["Decrement", int]
| ["Reset"];
type return_ = [list <operation>, storage];
/* Two entrypoints */
let add = ([store, delta] : [storage, int]) : storage => store + delta;
let sub = ([store, delta] : [storage, int]) : storage => store - delta;
/* Main access point that dispatches to the entrypoints according to
   the smart contract parameter. */
let main = ([action, store] : [parameter, storage]) : return_ => {
 return [
   (list([]) as list <operation>),    // No operations
   (match (action, {
    Increment: (n: int) => add ([store, n]),
    Decrement: (n: int) => sub ([store, n]),
    Reset:     ()  => 0}))
  ]
};
```
10. Open the command palette and select "Taqueria: Compile (LIGO)". This is where the error with the proxy comes in while running the compile command through the CLI has no issue

### Screenshots and images

Screenshot and images:

Installing the ligo plugin
https://user-images.githubusercontent.com/29528321/153069076-999c911c-21cc-4d45-9e54-d55fd417c17d.mp4

Trying to compile after installing the ligo plugin through the CLI
https://user-images.githubusercontent.com/29528321/153069332-370a13e5-72de-42c0-aacd-ad93a4c9d730.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@alexzbusko is this still an issue?

**Comment by hu3man** [comment]
I just tried to reproduce, and I can't even get the VS Code Extension to install the LIGO plugin...
![Screen Shot 2022-05-10 at 9 47 08 PM](https://user-images.githubusercontent.com/32914364/167916302-5d016f42-89c6-49e3-9d3c-77c44b6083d0.png)

**Comment by hu3man** [comment]
I just tried to reproduce but the VS Code Extension fails when I try to install the LIGO plugin...
![Screen Shot 2022-05-11 at 11 01 53 AM](https://user-images.githubusercontent.com/32914364/167916486-5d7de0cc-bdc4-4c82-b023-8697659f64d2.png)

**Comment by hu3man** [comment]
Assigning to @MichalLytek for further investigation

**Comment by russellmorton** [comment]
@AlirezaHaghshenas please verify if this is still an issue?

**Comment by sinapsist** [comment]
It works now if the contract has been added to the registry, meanwhile there is no command to add contract to registry

**Comment by sinapsist** [comment]
@AlirezaHaghshenas just confirmed that there is a PR to add a command to the command palette. This issue can be closed.
