### ISSUE TITLE
Use i18n strings throughout CLI & VS Code

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#263]
### Describe the feature you would like

Taqueria has support for i18n strings and uses them in a lot of places, but there are still messages which aren't using i18n strings.

All i18n string should reside in the CLI, and be exposed for the VS Code extension to consume and utilize. The same should be true (and already implemented) for plugins.

### Is this feature solving a problem?

Tezos developers are all around the world. Therefore, its required that Taqueria be a localized and internationalized application.

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing: out of scope
