### ISSUE TITLE
[Feature]: Run unit tests on-commit

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#267]
### Describe the feature you would like

We use create a husky pre-commit which runs our unit tests, and if a failure occurs, prevents the commit.

### Is this feature solving a problem?

This issues that our changes are tested before committed, and prevents breaking functionality.

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexzbusko** [comment]
Completed with https://github.com/ecadlabs/taqueria/pull/299
