### ISSUE TITLE
VS Code CI/CD Adjustments

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#268]
### Describe the feature you would like

We should ensure that the CI/CD process is consistent with the process for CLI and NPM workflows:
- [x] After a VXIS has been built, it should be posted as a comment in a PR
- [x] The VXIS should be stored on GCS
- [x] #277
- [x] A release shouldn't be published on the marketplace till the release draft is published.

### Is this feature solving a problem?

Keeps things consistent and therefore easier to understand. Less room for error when publishing a release due to fewer exceptions.

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GImbrailo** [comment]
Please see the linked PR for more information

**Comment by GImbrailo** [comment]
@mweichert the changes have been merged. Could you please check to see if the acceptance criteria for this issue are met when next you create a release?
