### ISSUE TITLE
[Bug]: Taq sandbox start clears JSON formatting from config.json transfer it to one line string 

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#275]
### What happened?

Config.json formatting clearing out after running `taq start sandbox {sandboxName}` command

### What should have happened?

Running taqueria commands should not re-format or clear formatting json format.

### Steps to reproduce the bug

1. Create taquified project
2. Observe ./taq/config.json format
3. Run taq start sandbox local
4. Observe  ./taq/config.json format

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Ivan confirmed that this is fixed and no longer an issue. Alex and I can't reproduce either.
