### ISSUE TITLE
[Feature]: Quickstart guide

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#282]
### Describe the feature you would like

A how-to guide that teaches users how to use Taqueria by doing

### Is this feature solving a problem?

The process of installing Taqueria and several plugins takes many steps which makes it harder for a new user to get going 

### Please share any additional details you have?

This will come under the getting-started section in Docusaurus

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Blocked by release of scaffold functionality

**Comment by russellmorton** [comment]
Covered by #427
