### ISSUE TITLE
[Feature]: Taqueria Environments Docs

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#288]
### Describe the feature you would like

Documentation that covers the purpose, installation, configuration, and usage of Taqueria environments

### Is this feature solving a problem?

There is no existing documentation coverage for this feature

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Making this a sub-issue (task) for the implicit state user story #549

**Comment by russellmorton** [comment]
Awaiting implicit accounts related to state API.
