### ISSUE TITLE
Document build and runtime dependencies

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#297]
We need to have documented and shared understanding of what version of Deno is used to build Taqueria. This can become common shared knowledge and used in our build scripts as well as CI/CD.

- [x] Added check to build.sh that enforces the Deno version
- [x] Update README.md with the recommended Deno version
- [x] Update website build instructions with recommended Deno version
- [x] Update CI/CD to use minimum recommended Deno version

In addition, we need to document runtime requirements for each plugin. At this time, I'm not sure what version of Node to suggest as a minimum, but I would suggest that the Active LTS release always be the minimum requirement that we list, which in this case, would be v16.

https://nodejs.org/en/about/releases/

- [x] Decided NodeJS version to list as a minimum requirement for plugins
- [x] Updated README.md for each plugin to note minimum NodeJS version
- [x] Updated website to note minimum NodeJS version for each plugin
- [x] Update CI/CD to use minimum NodeJS version

**Comment by hu3man** [comment]
Closing this as we have coverage for everything in this ticket
