### ISSUE TITLE
TASK - Taqueria SDK

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#30]
### Description
Taqueria SDK finalization

#### Acceptance Criteria
- [x] SDK released
- [ ] SDK documentation updated
  - [ ] Github documentation
  - [ ] Website documentation
  - [ ] Internal documentation
  - [ ] API documentation
- [ ] Unit tests

**Comment by hu3man** [comment]
#312

**Comment by russellmorton** [comment]
Covered in:
#446 
#312

**Comment by hu3man** [comment]
#446
