### ISSUE TITLE
[Bug]: Running taq init --help creates taq'ifed project instead of output help info into console 

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#309]
### What happened?

Running `taq init` with `--help` key creates taqified project under this folder.

### What should have happened?

Running `taq init` with `--help` key should display a help message about the init command

### Steps to reproduce the bug

1. Run `taq init` with `--help` parameter
2. Observe results - see that current folder has been converted to taqified project instead of showing help about init command

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@sinapsist, please re-verify this since the ticket is so old now

If still present it's quite a bad ux and we should handle soon

**Comment by hu3man** [comment]
Closing, will be fixed by internal tasks = plugin tasks refactor
