### ISSUE TITLE
Deploy to testnet and mainnet

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#320]
As a dapp developer, I want to be able to deploy to Mainnet and Testnet using Taqueria so that I can manage my complete development process.

### Current Taqueria Functionality
Taqueria allows networks to be configured for local testnets but has a requirement for the faucet to be stored in the config file of the project. This is a workable solution but is not an ideal solution for managing private keys.

Mainnet deployments would need to be handled in a similar way and this method is undesirable to mainnet deployments.

### Signing Options
Signing can be handled 
- Environment variable
- CI/CD halting process
- Remote signer
 
**ISSUES**
- [x] #669

**Comment by zamrokk** [comment]
I think that taq should look at   **SIGNER_PRIVATE_KEY** env var that would override any mainnet credentials during deployment

it is how I would do it on a CI/CD pipeline
