### ISSUE TITLE
Newcomer LIGO developers can build and test applications with smart contracts. "Hello World" contract and companion dapp can be compiled, deployed and tested

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#322]
As a newcomer developer, I want to build, deploy and test my application and smart contracts so that I can easily get started with a Tezos project.

 **Acceptance Criteria** 
- [x] #456
- [ ] #458
- [ ] #457
- [x] Scaffolded testing
- [x] Deploy to Sandbox
- [x] Interact with dapp
- [x] Interact with Sanbox 

**OUT OF SCOPE**
Type generation

**Comment by russellmorton** [comment]
-[ ] Hello Taco Simplification:
 - [ ] Remove Ligo native tests
 - [ ] Change source code to reduce number of steps to taqify app
 - [ ] Update directory name

**Comment by hu3man** [comment]
Closing: Redundant issue
