### ISSUE TITLE
Contract Types Plugin - Std Out & Logging - Adjust to use table layout

### ISSUE THREAD

**Issue by ricklove** [ecadlabs/taqueria#332]
### Description

Improve the std out and logging to use table layout.

#### Acceptance Criteria

- [ ] Use simplified plugin std out integration.
- [ ] Use table layout console log output
- [ ] Two columns - contract file name and path to generated code

#### Additional Context and Related Items

- https://github.com/ecadlabs/taqueria/issues/176

**Comment by russellmorton** [comment]
#479
