### ISSUE TITLE
[Bug]: Can't install latest vscode extension from market place

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taqueria#333]
### What happened?

From inside vs code, I went to market place, searched for "taqu", found taqueria `v0.0.9` with the `Pre-Release` label, I clicked to install it, but it did not install.

I got this pop-up error message from vs code;

![image](https://user-images.githubusercontent.com/1114943/154702021-47cfca4b-eec2-4da4-86d9-d09e745e8039.png)

### What should have happened?

It should have installed successfully :upside_down_face: 

### Steps to reproduce the bug

As above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
All tagged versions push a "Release" version of the extension. This avoids us having to explain in documentation how to install using the pre-release drop down:

![image](https://user-images.githubusercontent.com/7251388/154728503-fe866478-f9c5-4e44-9f5c-7b53c169b3c9.png)

**Comment by mweichert** [comment]
Duplicates effort covered in #268
