### ISSUE TITLE
As a taq user, I want a clear and actionable message returned if there are no contracts to deploy so that I'm not confused by ugly error messages

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#357]
### Describe the feature you would like
Currently, if no valid contract is found in the "artifacts" folder when originating, Taqueria returns a message that is not explicit.

As a smart contract developer, I want to have an explicit message shown when I try the `originate` task when there are no compiled contracts so that know more clearly what the problem is.

### Acceptance Criteria
- [ ] When the `originate` task is run with an empty artifacts folder, the message `No contracts originated. Artifacts folder empty` must be shown to the user. 

### Describe the feature you would like

Currently if no valid contracts found in the "Artifacts" folder taqueria will return empty output.

### Is this feature solving a problem?

Yes, it will provide more details about the contract(s) deploying status.

### Please share any additional details you have?

![Greenshot 2022-02-23 09 52 53](https://user-images.githubusercontent.com/10706087/155377995-7ec786cb-a982-4403-8b23-29ed6224c1b7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@sinapsist please check if this still happens.

I get the following:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/7251388/167951886-3be52c73-635e-4529-880b-c88e8823522d.png">

**Comment by hu3man** [comment]
@sinapsist @russellmorton, is there a PR associated with this ticket?

**Comment by alexzbusko** [comment]
@hu3man @russellmorton after setting up a local environment I am seeing the above that Russell posted. After getting a local sandbox up and running I am seeing the following:
```
Http error response: (400) Failed to parse the request body: Data_encoding__Binary_error_types.Invariant_guard("Operation lists should not be empty.")
No contracts originated.
```

I think it's safe to say that there is a message for no contracts found but it isn't explicit. I think we can either make an update to this ticket to make it say what we want or close it
