### ISSUE TITLE
Add a test to verify deploying a complex contract with complex storage value

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#361]
## Approach
- [ ] Investigation of possible storage formats @jchenche 
- [ ] Test plan to ensure comprehensive coverage and behaviour @alexzbusko 
- [ ] Test implementation

## Considerations
- Generated storage

#A.C:
- [ ] Initial storage specified as plain JSON object
- [ ] Initial storage specified as Michelson-encoded JSON
- [ ] Initial storage specified as Michelson expression
- [ ] Each of the 5 A.C. on #235 should be covered by automated tests

As an SDET I want to add a test(s) to verify more complex scenarios for deploying contract

- [ ] Contract with complex storage value
- [ ] Complex contract with complex storage value
- [ ] Contract that has a dependency to another contract (?This item is under question, need to get more clarification if it is supported or will be supported by taqueria and, probably, move it to another issue).

**Comment by hu3man** [comment]
Relates to #235

**Comment by hu3man** [comment]
@alexzbusko, touch base with Claude, Rick, Michael K, and Roxanne,

**Comment by alexzbusko** [comment]
Taquito page for reference: https://tezostaquito.io/docs/complex_parameters/
Contract collection: https://tezostaquito.io/docs/contracts_collection/
Minter contracts that Rick said could be useful for this: https://github.com/tqtezos/minter-sdk/tree/main/packages/minter-contracts/bin
