### ISSUE TITLE
[Bug]: taq list accounts local command output if sandbox is not running does not output to the console

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#367]
### What happened?

Running "taq list accounts local" for not running sandbox does not place error message into stdout as result test is failing because it cannot get the message from the output:
error: Error: expect(received).toEqual(expected) // deep equality
Expected: "The local sandbox is not running."
Received: ""

### What should have happened?

Running "taq list accounts local" for not running sandbox shoud place error message into stdout

### Steps to reproduce the bug

Run 'Verify that taqueria flextesa plugin will return "The local sandbox is not running." if user tries to retrieve list of accounts that is not running' from e2e test automation suite.

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@sinapsist, is this still an issue?

<img width="318" alt="image" src="https://user-images.githubusercontent.com/7251388/167897538-330463cd-da51-4c21-b107-f02bb410d3b2.png">

**Comment by hu3man** [comment]
Closing: This was resolved during the refactor 

```
❯ taq list accounts local              
The local sandbox is not running
```
