### ISSUE TITLE
TASK - CLI Integration Testing Framework

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#37]
### Description
Building the foundation for CLI integration testing using a mock plugin.

#### Acceptance Criteria
- [x] All necessary library dependencies added to project
- [x] NPM target added to project
- [x] Test folder created for integration tests
- [x] Mock plugin draft created
- [x] Single integration test successfully runs against mock plugin

**Comment by sinapsist** [comment]
It has been done, there is an integration test up and running
