### ISSUE TITLE
Update CI to add docker on executor(s) to be able to run e2e tests that use docker (flextesa, taquito) as part of pipeline

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#376]
As an SDET/SRE I want to add docker on executor(s) to be able to run e2e tests that use docker (flextesa, taquito) as part of the pipeline. Currently, these tests are failing in every pipeline.

AC: E2E tests should pass in the pipeline.

**Comment by alexzbusko** [comment]
@sinapsist I was looking at this last week and the ubuntu 20.04 runner has docker on it by default so it should have docker installed already for most CI runs

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
