### ISSUE TITLE
Investigate and re-enable skipped tests for plugin-taquito after issue with stdout is resolved

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#377]
Currently, the error outputs neither to stderr nor to stdout. It cannot be caught and processed by the node execSync command, which makes it untestable. Currently, these tests are skipped.
Need to investigate why the error does not output to the std and after it is fixed re-enable tests.
Development ticket associated with it - https://github.com/ecadlabs/taqueria/issues/313

There is a list of tests:

- [ ] Verify that taqueria taquito plugin will show proper error when configuration is wrong -> initial storage is not provided
- [ ] Verify that taqueria taquito plugin will show proper error when configuration is wrong -> invalid pkh
- [ ] Verify that taqueria taquito plugin will show proper error when configuration is wrong -> empty
- [ ] Verify that taqueria taquito plugin will show proper error when faucet is wrong -> network url is wrong
- [ ] Verify that taqueria taquito plugin will show proper error when configuration is wrong -> invalid network name in environment
- [ ] Verify that taqueria taquito plugin will show proper error when environment does not exists'

**Comment by russellmorton** [comment]
Depends on #257
