### ISSUE TITLE
DocDev for `Checking for Taq'fied projects`

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#381]
#### Acceptance Criteria:
- [x] Add caution note that re-initializing a project wipes out the config

#### User Story Requirements:
- If a previously initialized project is initialized again, return a message saying the project is already Taq'fied - The project is already taqified
- If a previously initialized project is initialized again, do not re-initialize the folder
- Hide the option to change the configuration directory in CLI
- Works in both CLI and VS Code extension

**Comment by hu3man** [comment]
@russellmorton, I'm trying to figure out exactly where to put this warning and I think the best place may be in the quickstart. What do you think?

**Comment by russellmorton** [comment]
Quickstart is the best place we have for now.

**Comment by russellmorton** [comment]
Waiting for #427
