### ISSUE TITLE
EPIC: Scaffold Tutorial

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#399]
### Describe the feature you would like

Documentation that describes the structure and usage of the React app and associated Taqueria project in the quickstart scaffold project

Include a step by step guide to walk the user through scaffolding and implementing:
- the quickstart repo
- the hello-tacos repo

### Is this feature solving a problem?

Details about the problem your feature solves

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
Possibly merge with #237

**Comment by russellmorton** [comment]
Covered as part of #237
