### ISSUE TITLE
As a Taqueria developer, I want automated testing of contract deployment to a sandbox so I can be confident that my changes didn't break core plugin functionality

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#405]
As an SDET I want to add tests to verify that contract(s) can be deployed to a sandbox.
Additionally we need to make sure that only specified contract has been deployed to the sandbox by using API call to the block
curl http://localhost:20000/chains/main/blocks/head/context/contracts
and parsing response.

**Comment by hu3man** [comment]
Should ensure that multiple contracts can be deployed successfully to a sandbox

Should test deploying to multiple sandboxes running different protocols defined in a single environment (local, sandbox2)

**Comment by alexzbusko** [comment]
@hu3man I think we should hold off on the different protocols for now since Jakartanet isn't currently supported by the latest flextesa image since it is still in development according to their website. Hangzhou is over so I don't see much use going with that. I think this is something to come back to once things are a bit more firm with the J protocol

**Comment by hu3man** [comment]
Agreed

**Blocked**
Pending release of protocol J

**Comment by russellmorton** [comment]
The website says Jakarta2 is supported as of today:

`RUN WITH DOCKER
The current released image is oxheadalpha/flextesa:20220510 (also available as oxheadalpha/flextesa:latest):

It is built top of the flextesa executable and Octez suite, for 2 architectures: linux/amd64 and linux/arm64/v8 (tested on Apple Silicon); it also contains the *box scripts to quickly start networks with predefined parameters. For instance:

image=oxheadalpha/flextesa:latest
script=ithacabox
docker run --rm --name my-sandbox --detach -p 20000:20000 \
       -e block_time=3 \
       "$image" "$script" start
All the available scripts start single-node full-sandboxes (i.e. there is a baker advancing the blockchain):

ithacabox: Ithaca-2 protocol.
jakartabox: Jakarta-2 protocol.
alphabox: Alpha protocol, the development version of the K protocol at the time the docker-build was last updated.
See also docker run "$image" tezos-node --version.`

**Comment by alexzbusko** [comment]
This is also currently blocked by https://github.com/ecadlabs/taqueria/issues/707. Once that is resolved this should be good to go

**Comment by hu3man** [comment]
Closing: functionality included in #777
