### ISSUE TITLE
[Feature]: Independent Docker Containers per Taqueria Project 

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#411]
### Describe the feature you would like

Currently, the Flextesa local sandbox is shared across all Taqueria projects. It would be useful to have a sandbox per project instead of a shared sandbox.

### Is this feature solving a problem?

This allows developers to work on more than one project and sandbox combination at one time.

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@AlirezaHaghshenas, is this still relavent?

**Comment by AlirezaHaghshenas** [comment]
> @AlirezaHaghshenas, is this still relavent?

No, I think this can be closed.

**Comment by hu3man** [comment]
Closing: no longer relavent
