### ISSUE TITLE
As an ECAD SDET, I want automated tests to ensure that user/group permissions are being set for artifacts correctly so that our end users don't run into frustrating errors

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#415]
### Describe the feature you would like

Automated tests that will ensure that any system generated files will have the correct non-root user/group permissions. Right now the things that will cause files to be generated are:

- Compiling a ligo contract
- Compiling a smartpy contract
- Building taqueria as part of a scaffolding project (`npm run setup && npm run build:taqueria` after running `taq scaffold`)

### Is this feature solving a problem?

For files/artifacts that are created by taqueria there are some that have the the user/group set to root which isn't too good for people needing to modify these files since they can run into permissions issues

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing: duplicate #374

**Comment by hu3man** [comment]
Relates to: #374

**Comment by AlirezaHaghshenas** [comment]
@alexzbusko This can be closed, right?

**Comment by alexzbusko** [comment]
@AlirezaHaghshenas it definitely can be. I don't understand how it isn't in the done state when it says that is was moved to the done state previously
