### ISSUE TITLE
As a new Taqueria user, I want an example and explanation of how compilation, deployment, type generation and Taquito all work together in a full-stack project so I can develop my projects with the full power of Taqueria

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#428]

**Comment by hu3man** [comment]
Currently blocked due to the quickstart-scaffold using Taquito to do contract origination on the front end

Once the state API is released, the scaffold will be refactored and work on this document can be resumed

**Comment by hu3man** [comment]
Closing: moving to scaffold docs ticket
