### ISSUE TITLE
USER STORY: Feedback Command

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#43]
### User Story
As a: Taqueria user I want to submit feedback about Taqueria so that I can easily share feedback to the Taqueria team about features I would like to see and errors that I encounter

### Background
Examples:
`>taqueria feedback feedback goes here`
Command pallet command to submit feedback.
Consider implement similar functionality to `gh create issue`

### Acceptance Criteria
- [ ] Feedback can be logged via CLI or VS Code extension
- [ ] Feedback is stored in GitHub issue for triage

**Comment by hu3man** [comment]
Closing: website will handle
