### ISSUE TITLE
[Bug]: `taq start sandbox` returns success message when the command has failed

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#432]
### What happened?

The Flextesa plugin has an issue where the `taq start sandbox` command will return the error message `Started sandbox` when the sandbox has not been started

This can occur when:
- The docker daemon is not running
- The docker container crashes during startup

### What should have happened?

Taqueria should validate that the correct container exists before returning a success message and if validation fails, a meaningful error message should be returned to the user

### Steps to reproduce the bug

Steps to reproduce the error

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
Covered as part of #257.
