### ISSUE TITLE
Simplify Hello Tacos

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#458]
- [x] Create an un-taq'ified version in it's own repo (to be cloned as part of newcomer doc 3 - guide to taq'ifying a project)
- [x] Create a fully scaffolded version 
- [x] Remove Ligo native tests
- [x]  Change source code to reduce number of steps to taqify app
- [x]  Update directory name
- [x] Fix empty folders
- [x] Add setup instructions
- [x] Update readme

Out of Scope:
- [ ] Add contract metadata (m2.2)

**Comment by hu3man** [comment]
Implemented in a new repo at https://github.com/ecadlabs/taqueria-scaffold-hello-tacos-tutorial

closed by: [PR](https://github.com/ecadlabs/taqueria-scaffold-hello-tacos-tutorial/pull/1)
