### ISSUE TITLE
[Feature]: Contract Type Plugin: Test Stub Generator

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#474]
### Describe the feature you would like

The contract type plugin should provide a means to generate a file(s) with test stubs for each public method defined in the processed contract

The test stub files should expect to be used with Jest and the upcoming support for testing in Taqueria

### Is this feature solving a problem?

Creating tests for a `.tz` file is difficult and time-consuming 

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Duplicates #572
