### ISSUE TITLE
[Feature]: Build Common Documentation Pages from a Single Source

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#488]
### Describe the feature you would like

We currently serve plugin documentation via these channels:
- npm registry `https://www.npmjs.com/package/@taqueria/plugin-ligo`
- github/project repo `/taqueria-plugin-ligo`
- docusaurus site `https://taqueria.io/docs/plugins/plugin-ligo`

The content for the ligo plugin documentation on npm and github comes from  /taqueria-plugin-ligo/readme.md while the content on the website lives in /website/docs/plugins/plugin-ligo.md. Given that both files are markdown and have essentially identical information, they should be built from a common source to reduce maintenance burden and reduce code duplication

There are a few issues that need to be worked out to make this viable:
- the plugin `readme.md` file displayed in git and uploaded to NPM registry expects a file named `readme.md` to exist in each plugin subdirectory (need to map content from named files to a `readme.md` file in the correct location)
- the docusaurus-terminology plugin does a substitution on certain terms which replaces the term with a hover-over link. As this is not supported without the library, there needs to be a separate substitution to the plain text term for the version output to the plugin dir `readme.md`'s
- the `readme.md` files exist as static files in the repo and are not currently generated, we would likely need to generate or overwrite these files as part of the PR build process (or something...)

### Is this feature solving a problem?

Details about the problem your feature solves

### Please share any additional details you have?

This should likely be implemented after we figure out how the terminology plugin build will work (or at least have a good idea of how it will be done and the implications)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
1. Getting docs into Docusaurus
2. Compiling docs in GitHub and docusaurus
3. 3...
