### ISSUE TITLE
Token indexing testing/assertion plug-in

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#491]
From a testing perspective, when you are creating a contract that is issuing a token you want to be able to check or have surety that it's getting correctly indexed by indexers.

 - Developers should be testing that token metadata is correct
 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/7251388/171694867-83a8334e-f056-4e77-ac48-b5ebf1b0f37b.png">

- Assurance of token being indexed
- Create tests to check that token is being indexed correctly

_start with manual best practice instructions_
_linter for token metadata_

Prelaunch checklist best practices - refer to Taquito dapp pre-launch checklist

**Comment by mweichert** [comment]
@russellmorton or @hu3man , when either of you get a sec do you mind adding a description to this issue please?
