### ISSUE TITLE
[Bug]: Website images not rendering correctly 

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#498]
### What happened?

Images on the homepage are not loading correctly

### What should have happened?

Images should load

### Steps to reproduce the bug

Go to taqueria.io

### Screenshots and images

![image](https://user-images.githubusercontent.com/7251388/158893915-e264c5f7-975c-40ff-826b-0bbd9d54e292.png)

<img width="549" alt="image" src="https://user-images.githubusercontent.com/7251388/158893715-feaf1700-3c3f-42c2-831c-d2828cb3f317.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
FYI @hu3man

**Comment by russellmorton** [comment]
@HamidGoudarzi1988, please will you take a look at this?

**Comment by hu3man** [comment]
Hey @HamidGoudarzi1988 , were you able to look into this?

**Comment by HamidGoudarzi1988** [comment]
Hey @hu3man, sorry for being late, please take a look at my pr:
https://github.com/ecadlabs/taqueria/pull/531

Let me know if it needs more tweaks, thanks

**Comment by hu3man** [comment]
No worries, thanks for pushing a fix!

Looks good on my end, will get another pair of eyes on it to confirm and will let you know if we encounter any issues
