### ISSUE TITLE
Help menu not aware of tasks after installing plugin

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#528]
After you install a plugin and run `taq --help`, the tasks from the newly installed plugin aren't immediately available. This is because the state file hasn't been updated. If you were to run `taq` on its own immediately after installing the plugin, this would regenerate the state file and display the help menu, which displays the tasks from the newly installed plugin.

NOTE, this requires a broader adjustment to how the install/uninstall tasks are executed.

**Comment by hu3man** [comment]
Note: this must be caught by an automated test!

**Comment by alexzbusko** [comment]
Whenever this is started we will need to make sure that the e2e tests have their work arounds removed since they are in a lot of places

**Comment by russellmorton** [comment]
@mweichert ping

**Comment by jchenche** [comment]
Same bug with `taq uninstall` too
