### ISSUE TITLE
[Bug]: Scaffold feature does not remove `.gitignore` files in cloned repo

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#530]
### What happened?

When running `taq scaffold XXX dir-name`, the `.gitignore` files should be recursively removed from all directories

For example, in the `quickstart-scaffold` project, `.gitignore` files exist in:
- `/`
- `/app`

### What should have happened?

After cloning the remote repo and removing the `/.git` directory, the task should remove any `.gitignore` files contained in the cloned project

### Steps to reproduce the bug

Steps to reproduce the error

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@claudebarde, please help with some suggestions for this issue.

- Once you scaffold a project and you have the Taqueria project, should it have a .gitignore file that we have prepopulated?

**Comment by claudebarde** [comment]
@russellmorton What kind of files does a Taqueria project create that need to be in a `.gitignore` file?
In general, it could be interesting to have such a file so the users don't have to create it themselves.

**Comment by hu3man** [comment]
The 'node_modules' directory doesn't get checked in, so maybe it does make sense to leave that

**Comment by russellmorton** [comment]
@mweichert FYI
