### ISSUE TITLE
[Feature]: The VS Code Extension should have access to the `taq scaffold` command

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#532]
As a Taqueria VS Code Extension user I want the `taq scaffold` to be available in the command palette and show the available scaffolds so that I don't have to manually type the scaffold name in the command palette.

### Acceptance Criteria
- [x] Opening command palette shows `taq scaffold` as `Taqueria: Scaffold`
- [x] Once 'Taqueria: Scaffold` is selected, a list of available scaffolds is shown (create QuickPick - https://code.visualstudio.com/api/references/vscode-api#window)
- [x] User is able to select the scaffold from the list
- [x] Once selected, the project is scaffolded out from the selected option
- [ ] Honour 1st Party, Verified 3rd Party, Unverified 3rd party, Banned 3rd Party
- [ ] Minimum version number for
   - [ ] Taqueria core
   - [ ] Taqueria VS Code Extension

### Solution Options
- Awesome Lists
- Homebrew model

### Issues
- [x] #801
- [x] #802
- [x] #803
  - [x] #804
- [x] #805
- [x] #806
- [x] #807

### Initial Repository.json fields
- Name
- Description
- Path to repo
- 1st Party, Verified 3rd Party, Unverified 3rd party, Banned 3rd Party
- Link to repo
- Icon URL
- Homepage URL
- Simple name (Alias)

## Deferred
- UI for scaffolds inside VS Code

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
Is there an epic for bringing the extension to parity with the CLI or should we turn this into one?

**Comment by AlirezaHaghshenas** [comment]
Remaining steps moved to #1101.
Closing this one
