### ISSUE TITLE
[Bug]: Build failing because taq cannot be found

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#555]
### What happened?

After running `npm run build-all` for the first time, I noticed a build error (refer to log output).

### What should have happened?

Build should succeed without any errors.

Workaround: make sure `taq` is in the path and then run `npm run build-all` again.

### Steps to reproduce the bug

1. Download all the dependencies specified in the README.md file
2. `npm run build-all`

### Relevant log output

```shell
> @taqueria/flextesa-manager@0.2.0 build-docker
> TAQ_VERSION=`taq --version` BUILD=`taq --build`; docker build . -t "ghcr.io/ecadlabs/taqueria-flextesa:${TAQ_VERSION}-${BUILD}"

sh: taq: command not found
sh: taq: command not found
invalid argument "ghcr.io/ecadlabs/taqueria-flextesa:-" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
npm ERR! Lifecycle script `build-docker` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @taqueria/flextesa-manager@0.2.0 
npm ERR!   at location: /Users/jimmychenchen/taqueria/taqueria-flextesa-manager
```

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Good catch @jchenche!

@russellmorton , @mweichert; how should we approach this?

I don't like the idea of running shell scripts to modify the users terminal config and detecting and correctly doing this for all environments and shells would be difficult and error prone

The most simple solution would be to call this out in the build instructions, and add some logic to the build that would check for the existence of, and correct version (in case the user followed the instructions on the site and installed an older binary to their `/usr/local/bin` directory which could also cause build issues); and then output a friendly CLI message

**Comment by russellmorton** [comment]
@hu3man, I agree with handling this as described. This was partially covered in #119.

**Comment by hu3man** [comment]
Closing: Handled in ^^

**Comment by russellmorton** [comment]
@jchenche this will be for the August sprint.

**Comment by sinapsist** [comment]
Need to run `npm build` before npm `run build all`
