### ISSUE TITLE
[Feature]: Break up the CLI commands tests into specific plugin based files to limit the amount of time that installation/uninstallation takes

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#559]
### Describe the feature you would like

There are a growing number of tests for each plugin in the taqueria project. Since there are tests that check the help messages for each plugin there are a number of install/uninstall operations per each test to make sure no test will depend on any other tests. As more functionality is added this will likely increase the number of tests and time it takes to run them. These tests should be split up into different files either based on plugin or operation (for example having a file dedicated to compiling using both the ligo and smartpy plugins). This would let us install once at the beginning of the tests and not have to constantly install/uninstall/reinstall in a single test suite run

### Is this feature solving a problem?

This solves the problem of the time that our tests take to run getting ridiculous and making the feedback loop on feature changes longer and longer

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Done: #680
