### ISSUE TITLE
Match VS Code commands to CLI

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#564]
As a Taqueria VS Code user I want to run all of the same commands that exist for the CLI from the VS Code extension so that I can use the VS Code extension for all Taqueria functionality.

**Background**
Some commands are not available in the VS Code extension so there is a mismatch between the functionality available in the VS Code extension and the CLI.

Currently, the extension can:

- [x] Initialize a project
- [x] Install plugins
- [x] compile Ligo
- [x] deploy contract
- [x] start sandbox
- [x] stop sandbox
- [x] list accounts
- [x] Compile Smartpy contracts

**Acceptance Criteria**

- [x] Uninstall plugins
- [x] Compile Archetype
- [x] Generate types using type generator plugin
- [ ] Update originate commanded to target an environment from config.json
- [ ] Confirm no other additional commands are missing
- [x] Taq scaffold
- [x] Opt-in to Analytics
- [x] Opt-out from Analytics
- [x] Typecheck contracts
- [x] Test

**Comment by russellmorton** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/7251388/162329113-5fbb5649-8d89-40a0-a6f9-8378f9dd4f48.png">

**Comment by hu3man** [comment]
Note, we do have another ticket for dynamic population of values [issue #565 ](https://github.com/ecadlabs/taqueria/issues/565)

**Comment by hu3man** [comment]
Closing: covered by #565
