### ISSUE TITLE
Test Stub Generation

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#572]
As a test author, I want Taqueria to generate test stubs for all entry points in my project's contracts so that I save time and increase coverage when writing tests

As a type generation plugin user I want to have test stubs for all contract entry points be automatically generated as part of the type generation plugin so that can I have test coverage across all entry points.

***USE CASE***
The user using the type generation plugin generates type information for their smart contract and at the same time is provided with test stubs for the entry points within the contract.

**Comment by ricklove** [comment]
The current direction on this is that the type plugin would expose a handful of utility methods that would generate a snippet of code. These snippets would then be used by a framework specific plugin (like jest) which would generate the actual test files.

The structure would be something like this:

```
export type ContractCodeGeneratorFactory = {
    /** Load the contract from it's .tz file */
    load: (contractTzPath: string) => ContractCodeGenerator;
}

export type ContractCodeGenerator = {

    /** Generate the required imports for the tests, like the contract types or type alias utilities */
    generateImports: () => string;

    /** Generate the code to setup the tezos toolkit, originate a contract (providing the default storage), wait for confirmation, and set the contract instance variable */
    generateOriginationCallWithDefaultStorage: (contractInstanceVarName: 'contract' | string) => string;

    /** Generate the code to use the contract instance to call an endpoint (providing the default params) and wait for confirmation */
    generateEndpointCallWithDefaultParams: () => string;

    /** Generate the code to use the contract instance to get the storage value and set it to a variable */
    generateReadStorageValue: (actualVarName: 'actualResult' | string) => string;
}

```

**Comment by hu3man** [comment]
Would it make sense to move some/all of the utility methods/logic to the SDK so that the `contract-types` plugin isn't a dependency for the testing plugin?

**Comment by ricklove** [comment]
@hu3man it wouldn't be ideal to move it to the sdk because on the level of complexity. I think the most manageable architecture is that it would be a package dependency. It's pretty low level similar to the compiler or flextesa plugin which would also be needed for the test plugins.

**Comment by hu3man** [comment]
Got it, sounds good to me!

**Comment by hu3man** [comment]
@ricklove, where are we at with this?

**Comment by ricklove** [comment]
This was merged by @mweichert with https://github.com/ecadlabs/taqueria/pull/852 and should be part of the jest plugin.

**Comment by hu3man** [comment]
@mweichert, is this exposed via the `create` method on the Jest plugin or is it not released yet? I haven't seen it working
