### ISSUE TITLE
[Feature]: Implement Plugin Templates (contracts, tests, metadata)

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#590]
### Describe the feature you would like

Right now we have the ability to scaffold entire projects. However, we should have the ability to create new instances of particular types of entities based on an existing template.

Some entities that I would like templates for:
- ligo contract for each syntax
- smartpy contract
- archetype contract
- jest test case
- JSON for basic contract metadata

To create an instance of one of these templates, I would do:
` taq create contract hello --plugin ligo --syntax mligo`
` taq create contract increment --plugin smartpy`
`taq create contract vault --plugin archetype`
`taq create test increment --contract increment`
`taq create metadata increment`

### Is this feature solving a problem?

The first complaint from Claude when I introduced him to Taqueria was a way to quickly get started with a LIGO smart contract.

It removes the need to write a lot of boilerplate code, and yet not have to pull in the weight of an entire project scaffold.

### Please share any additional details you have?

This could be utilized by #588 to provide the following:
```
taq create alias compile \
--handler "taq compile --plugin ligo && taq compile --plugin smartpy"
```

It could also be used to provide a scaffold for plugin authors:
`taq create plugin my-plugin --sdk node-sdk`

If we have the ability to scaffold plugins, it could be that #588 isn't necessary.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
We have two interpretations of it as the moment, almost at a macro level and a micro-level. 

The macro-level is basically what we have implemented under the scaffold task currently, where it's fetching a complete project template and making it ready for the user.

The second is more aligned with where a user may want to just scaffold out something specific in their project and call a more granular scaffold, like for example taq scaffold metadata and have the metadata scaffold execute.

Both of these are valuable, but I think we need to be clear that there are two different lines of thinking.

This ticket references the micro-level version. We should disambiguate the term scaffold to ensure there is no confusion.

@mweichert suggested we should use different terms to disambiguate - "scaffold" for the first variant, and "template" for the second.

**Comment by hu3man** [comment]
Yes, from my understanding a lot of the micro-level stuff will actually be tasks that call templates (state API) defined in plugins

At this time I've only been using the term `scaffold` to refer to the `taq scaffold <repo> [projectDir]` command and would prefer to use terms like `template`/`create`/etc for non-project/cloning related stuff
