### ISSUE TITLE
[Feature]: Implement Hook Authoring

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#593]
### Describe the feature you would like

As a plugin author, I would like to execute code before or after a task is executed, whether that task is exposed from my plugin, or another plugin.

**Acceptance Criteria**
- [ ] A hook can be implemented on a plugin and consumed via SDK @mweichert 
- [ ] If a post-hook fails, the pipeline should fail and the user informed @mweichert 
- [ ] Documentation: hook concepts and usage @hu3man 
- [ ] Documentation: how to author a hook as a plugin dev @mweichert @hu3man 
- [ ] Errors in hooks should propagate up to the initial hook and warn the user that their state could be inconsistent @mweichert 
- [ ] The Taquito `originate` task should have a hook which executes @mweichert 
- [ ] Test: pre-hook @alexzbusko 
- [ ] Test: post-hook @alexzbusko 
- [ ] Test: multiple hooks @alexzbusko 
- [ ] Test: hook priority @alexzbusko 
- [ ] Test: post-hook that causes an event which triggers another hook @alexzbusko 

### Is this feature solving a problem?

Yes, this is a feature that Agile Ventures requested when wanting to build their Dappetizer plugin.

Additionally, it was a foundational component I had envisioned using to construct workflows and make it easy for developers to do accomplish much with single commands.

Finally, It would be rather inconvenient for an end-developer if they were required to manually create every operation (see #591) needed to fulfill their project. Hooks can address this.

E.g. If a user were to execute a single command, such as `taq create contract increment`, then using hooks we could also do the following:
- Create an operation to compile the contract
- Create an indexer for the contract
- Create the basic metadata for the contract
- Create an operation to originate the contract
- Create an operation to publish the metadata using IPFS
- Create a test case using the Jest plugin
- Generate typescript classes using the contract types plugin
- VS-code specific hooks - open contract in editor

### How to author hooks

To address this, plugin authors can attach a hook that gets executed when a task is invoked.

> REMINDER: A task can be invoked by the end-developer interacting with the CLI or VS Code extension, or it could be triggered by some kind of automation such as a cron job, CI/CD process, etc.

For instance, the LIGO plugin author might want to generate an operation for compiling the contract when a new contract is created from one their templates:

```ts
Plugin.create({
    tasks: [
        // the "compile" task defined here
    ],
    templates: [
        // the "contract" template defined here
    ],
    operations: [
        // the "compile" operation defined here
    ],
    hooks: [
        Hook.create({
            task: "create",
            template: "contract",
            plugin: "ligo",
            priority: 50,
            kind: "posthook",
            handler: "taq create op compile <%= it.filename %> compile_<%= it.filename %>.ts"
        })
    ]
})
```

The hook defined above would create a compile operation each time the developer used `taq create contract` to create their contract.

### Customization of hooks

The configuration of a hook can be customized in the _.taq/config.json_ file, either by having its properties overwritten, or disabled:

```
hooks: {
    "taquito.create-originate-op-for-ligo-contract": {
       "priority": 100,
        "enabled": false
    }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
After looking into this, I've found some complications due to the hook propagation depth. To account for this, Taqueria needs to compute a DAG representation and then execute hooks in batches.

**Comment by hu3man** [comment]
Closing:
