### ISSUE TITLE
As a Taqueria user, I want the deployed contract address to be available in my front end code and test specs so that I don't have to manually hardcode the value and update it every time I re-deploy or change environments

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#594]
### Describe the feature you would like

There is a file called _.taq/state.json_ which is a type of cache / ephermal state which maps tasks to plugins to reduce the amount of chatter at the protocol layer, which is great for performance.

To avoid confusion between ephermal and persistent state, I'd like to rename _.taq/state.json_ to _.taq/cache.json_.

### Is this feature solving a problem?

Yes, it will allow for #591 to use _.taq/state.json_ for its persistent state.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing: task level ticket that's implicitly covered in other user stories
