### ISSUE TITLE
[Feature]: allow compile tasks from all plugins to accept zero or more source files

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#596]
As a smart contract developer, I want the CLI parser to handle multiple arguments that are optional or required, each of which can handle zero or many inputs (e.g. file names).

- Multiple inputs
- Multiple arguments

### Describe the feature you would like

`taq compile hello-tacos.mligo hello-tacos2.mligo` should compile both files.

### Is this feature solving a problem?

The command above will ignore the second file.

### Please share any additional details you have?

This allows fine-grained compilation of multiple contracts. Currently we can only compile one file or all files.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Unnecessary with upcoming changes
