### ISSUE TITLE
SPIKE - Michelson Prototype

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#6]
### Description
Purpose of the spike is to validate the plugin framework design can accommodate Michelson smart contracts in the future.

Note: consider using Michel codec from Taquito

### Acceptance Criteria

- [x] Explore the ability for Taqueria to validate a smart contract written in Michelson
- [x] Explore the ability for Taqueria to originate smart contract written in Michelson
- [x] Create Michelson compile user story

**Comment by hu3man** [comment]
Closing: All requirements met
