### ISSUE TITLE
Provide automated tests for Michelson type check in Flextesa plugin

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#604]
As an SDET I want to add automated tests to verify the Michelson type check plugin to cover at least these three options:

- [x] Michelson contract with valid types
- [x] Michelson contract with invalid type(s)
- [x] Multiple Michelson contracts
- [ ] Empty Michelson contract

**Comment by hu3man** [comment]
Is this ticket taken care of as part of the epic #547 ?

**Comment by hu3man** [comment]
@sinapsist , is this implemented?

**Comment by russellmorton** [comment]
@sinapsist @jchenche please check if this is fulfilled already?

**Comment by jchenche** [comment]
I believe the first 3 is covered

**Comment by hu3man** [comment]
I don't think we need coverage for the 4th item and I think we can close this out

Running typecheck on an empty file results in:
```
❯ taq typecheck                              
 
Fatal error:
  syntax error in program

┌──────────┬─────────┐
│ Contract │ Result  │
├──────────┼─────────┤
│ empty.tz │ Invalid │
└──────────┴─────────┘
```

And simulate:
```
❯ taq simulate example.tz '1'                
 
example.tz: Does not exist

┌────────────┬────────┐
│ Contract   │ Result │
├────────────┼────────┤
│ example.tz │ N/A    │
└────────────┴────────┘
```

@jchenche, what do you think?

**Comment by jchenche** [comment]
@hu3man I don't think we need to check for empty files. I agree

**Comment by hu3man** [comment]
Closing: Requirements fufilled
