### ISSUE TITLE
VC Code Extension Test to verify compile command for LIGO plugin

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#605]
As an SDET, I want to add tests to verify that ligo plugin can be installed and taqieria.compile {filename} command will run to compile a contract

**Comment by hu3man** [comment]
@sinapsist, let's timebox this task so we can move on to higher value stuff. How about whatever is ready by Monday afternoon we merge in and come back to the rest later?

Also, please link the PR to this issue

**Comment by hu3man** [comment]
Complete!
