### ISSUE TITLE
Taqueria State

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#620]
Defined by the plugin author, plugins have a number of operations. When an operation is created, it will output code to the /operations folder

*Acceptance criteria*
- [x] SDK exposes a means for defining operations
- [x] A task called `provision [op]` is implemented (creates an operation exposed by a plugin) for Taquito
- [x] The mock plugin exposes an operation that can be consumed by the testing framework
- [ ] CLI command exposed to list operations `taq list operations`
- [ ] CLI command exposed `taq apply` to apply the operations
- [ ] Documentation: using operations
- [ ] Documentation: adding operations to a plugin (mock)
- [ ] Test: unit
- [ ] Test: Plugin info call
- [ ] Test: `taq create op` / check list of operations
- [ ] Test: `taq apply`

**Comment by hu3man** [comment]
Re-opening and adding to 'in-review' so AC can be discussed

**Comment by mweichert** [comment]
This was started in 620-operations but got put on the back-burner to focus on having `taq originate` populate the persistent state.

The operation construct is fully implemented, however the when() clause of a provision needs more thought now that provisions.json is a JSON versus TypeScript file.

The `taq list operations` task needs done, but all constructs are in place to make it easy to add.

There's a `taq apply` command that is started but still much work to be done.

There's also a `taq plan` task implemented which outputs a Mermaid diagram, although this may still need some work.
