### ISSUE TITLE
Use Hooks to create an Implicit Operation when `taq originate` is Called 

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#622]
Taq originate should implicitly create an operation and then execute that operation so that the state is updated by the operation

A pre-hook should be registered on the `taq originate` task which detects if the execution context is an operation or a task

If the execution context is not an operation, an operation should be created and then executed. If the context is a task, but an associated operation exists, the CLI should execute the operation associated with the command

**Acceptance Criteria**

**Comment by mweichert** [comment]
Closed in favor of #623.
