### ISSUE TITLE
[Architecture]: Define/standardize the accepted storage formats in Taqueria

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#626]
Increasingly, there is a need to determine what formats and representations will be accepted for storage values that are defined or used in Taqueria. 

Acceptance criteria
- A clear definition of what formats are accepted
- An understanding of whether those formats are accepted both in config and as CLI arguments, or one or the other
- The expectations/requirements for passing the various formats through the CLI
- The JSON schema for `config.json` updated to support and enforce allowed formats
- Documentation of the structure of each supported format
- Documentation on defining the storage in config and injecting to cli commands
- Reserve any terms we decide on, add them to the glossary, and enforce their unique usage throughout product and docs

### Describe the feature you would like

- The simulate task should later accept storage formats in different representations, such as JSON (object literals), Micheline, or Michelson Expression (encoded as a string). Essentially, it should accept the same three representations as Taquito does when specifying storage for originating a contract: https://tezostaquito.io/docs/originate
- Any of our tasks that are working with storage values should behave consistently, and therefore if storage parameters to be specified as a CLI argument, it should also allow all three representations to be used.
- Finally, for consistency, we should perhaps reserve "storage" and "storage-format" as the name for specifying these, where the value for storage-format could be "json", "micheline", and "michelson".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Thanks for creating this issue @jchenche! I've been running into some uncertainty about this recently

At this time, can you or @mweichert give a rundown of accepted formats for specifying initial storage for the following?
- In the `config.json` env initial storage property
- At the CLI using the simulate task with the -s flag

Thanks!

**Comment by hu3man** [comment]
Updated this ticket with some additional context as the more I think about it the more there is to consider
