### ISSUE TITLE
[Bug]: Provide friendly error when the version of node <16

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#631]
### What happened?

taq install [@Taqueria-e2e-test-notifications](https://ecadlabs.slack.com/team/U037TPSBKAQ)/plugin-ligo
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for yargs@17.4.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: yargs@17.4.1
npm WARN notsup Unsupported engine for yargs-parser@21.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: yargs-parser@21.0.1
npm WARN test-taqueria@1.0.0 No description
npm WARN test-taqueria@1.0.0 No repository field.
+ [@Taqueria-e2e-test-notifications](https://ecadlabs.slack.com/team/U037TPSBKAQ)/plugin-ligo@0.2.1
added 41 packages from 41 contributors and audited 41 packages in 3.472s
5 packages are looking for funding
  run npm fund for details
found 0 vulnerabilities
Plugin installed successfully

### What should have happened?

Should install with no warnings.

### Steps to reproduce the bug

Install Ligo plugin on a fresh instance of WSL2.

### Screenshots and images

<img width="784" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/7251388/165629822-821b694d-ff2d-4cb1-8cdf-725447e77179.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@hu3man FYI

**Comment by hu3man** [comment]
Closing: #107
