### ISSUE TITLE
NPM / Docker environment setup docs

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#636]
### Describe the feature you would like

As a newcomer developer using Windows, I need instructions on how to get WSL2/docker/node correctly installed and configured so that I can start using Taqueria without friction

** Will require some help and input from Windows users (@alexzbusko?) **

### Is this feature solving a problem?

Currently, it is difficult and frustrating for a Windows user to get their environment set up in a way which allows Taqueria to be used as documented

### Please share any additional details you have?

- Confusion about which binary to use (installation instructions)
    - Add context for windows specific instructions to include 
- Be more explicit about installing Docker in the install guide
- Docker link should point to the get-started page that has the download 
    - Must be explicit about docker desktop (for Windows)
    - Need to add installation instructions for Docker to Windows install specific to WSL2
 - Default Node version is 10.9 which breaks Taqueria, need to detail steps to upgrade in WSL
 - Should add a health check step to make sure everything is working before user proceeds 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@alexzbusko , let me know when you have this roughed out. If possible, it would be great to get a first version of the Windows installation steps up on the site before the TezTalks on Thurs as we will probably see an increase in new users visiting the site 

If not, we may want to consider removing the Windows instructions from the site altogether ( @russellmorton ) . Since we had 2 ECAD engineers fail to get their env setup for Taqueria on Windows, I don't think new users have much of a chance at the moment....

**Comment by russellmorton** [comment]
@hu3man if the new installation steps aren't complete, lets removed Windows until they are.

**Comment by hu3man** [comment]
Sounds good, we can reassess this tomorrow afternoon and push changes one way or the other

**Comment by alexzbusko** [comment]
@hu3man @russellmorton I have gone through the setup process for ubuntu 20.04 WSL2 and these are my notes:

-  Node, NPM and NVM can all be installed/set up with this handy Microsoft guide https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl
- The only thing here is that there is some inconsistency with how we refer to WSL. We use WSL in some places and WSL2 in others. We should probably just standardize on WSL2
- When it comes to installing docker we should probably link to the docker WSL pages https://docs.docker.com/desktop/windows/wsl/

Overall getting things setup was quite easy with the help of the above guides and from what things I tried to do I had no issue doing them

**Comment by hu3man** [comment]
@russellmorton @alexzbusko, do we want to link to the MS docs, or rewrite the process in a more concise manner in an 'Environment Setup' doc?

**Comment by russellmorton** [comment]
Is there any reason to link users out of our site or can we get them across the line with concise steps?

If the steps can be condensed I would say keeping them in the flow on our site is better. However if there is value in the user linking out or a risk that we would end up with a disproportionate number of steps, then link to the MS docs.

From what @alexzbusko has said, it seems like we will be able to condense the steps and possible just provide links in a learn more section?

**Comment by russellmorton** [comment]
> @hu3man @russellmorton I have gone through the draft PR and run the steps and things look good. The one question I have is do we want to explicitly not have people download a node version management tool? We will likely eventually need to move to a newer version of node and I am just wondering if we want to get people in the habit of getting a version manager onto their systems

It may make sense to recommend a node version manager, but it should not be listed as a requirement. These are newcomer docs so it would be helpful to some users.

**Comment by alexzbusko** [comment]
Okay cool, thank you for letting me know Russell

**Comment by hu3man** [comment]
I'm torn on recommending NVM to users. While it is best practice, it adds complexity to the installation to get set up properly and may be confusing for users less familiar with cli apps. Definitely would like more opinions on this!

Also, I used node v16 in the draft, but am leaning towards 17/18 as 16 is already getting pretty dated... thoughts?

**Comment by russellmorton** [comment]
It does add complexity to getting started, but it does stand the user in good stead for future development. And if they are that new that they don't know how to handle node, I'm sure the guidance would be appreciated.

I think we should reference the version that would install by default for a user. In this case, v16 is still the LTS version.

**Comment by alexzbusko** [comment]
@russellmorton @hu3man I was just looking at the schedule for node version and we only have about 5 months left of v16 being the LTS version. After that 18 kicks in and becomes the LTS version. Considering that I think we should have some sort of section for handling changing node versions for development. The MS doc for getting node on your system has a link to getting existing versions off of your system since they can mess up things in weird ways https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm. 

With those two things I think we should strongly encourage people to install a version manager to make the transition easier even if we don't make it a requirement to get set up at the beginning

**Comment by hu3man** [comment]
Good find @alexzbusko. I'll change the install guide to target v18 (but leave requirements at the plugin doc level at 16)

For a version manager, it's probably best to include steps for all platforms. I'm most familiar with NVM, do you have any reservations about that for WSL?

If not, can you confirm that the following steps are valid/recommended?
- `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash`
- `nvm install 18`
- `nvm alias default 18`
- `nvm remove 14`
- `nvm use 18`
- `npm install --global`

**Comment by hu3man** [comment]
@russellmorton, given the length of the environment setup, what do you think about moving the environment setup to it's own page which would become the landing page for `Try the Beta`

We could then have a link for users to skip to the binary installation if their env is already configured correctly

**Comment by russellmorton** [comment]
That can work.

A brief intro to Taqueria, with a link for people to skip environment setup directly or continue on to setup.
