### ISSUE TITLE
Parse and validate config file

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#642]
Currently, only sections of the config file are being parsed and validated.

The `getRawConfig` method and `getConfig` method should be the primary methods for parsing the config. Currently these methods do no parsing/validation at all. This is very problematic - for example:  a user could have an environment referring to a network or sandbox that isn't defined.

This is a rather significant oversight.

There is a test case for testing whether an environment is referring to an invalid network config in the Taquito E2E test suite, which is currently being skipped:

```
test.skip('Verify that taqueria taquito plugin will show proper error when configuration is wrong -> invalid network name in the environment', async () => {
        try {
            // Environment test does not exist on default config.json
            environment = "test"

            // 1. Copy config.json and michelson contract from data folder to artifacts folder under taqueria project
            await exec(`cp e2e/data/config-taquito-test-environment-invalid-config-networkname.json ${taqueriaProjectPath}/.taq/config.json`);
            await exec(`cp e2e/data/hello-tacos.tz ${taqueriaProjectPath}/artifacts/`);

            // 2. Run taq deploy on a network described in "test" environment
            await exec(`taq deploy -e ${environment}`, {cwd: `./${taqueriaProjectPath}`})

        } catch(error) {
            expect(error).toContain("E_INVALID_PLUGIN_RESPONSE");
            // throw new Error (`error: ${error}`);
        }

    });
```

This test case can be reinstated once the config file is fully parsed and validated.

**Comment by hu3man** [comment]
This will be great to have implemented. Will we be adding/enforcing a JSON schema as part of this work?

**Comment by mweichert** [comment]
I'd like to use this throughout the codebase:
https://github.com/colinhacks/zod

The ecosystem behind that project is huge, and has support for generating JSON schemas as well.
