### ISSUE TITLE
Add end to end  smoke test to simulate simple user flow for newcomers

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#646]
As an SDET I want to add test(s) to simulate simple user flow for newcomers starting from installing taqueria and ending with having the contract deployed to a network.
There are possible items that it can include
1. Build taqueria
2. Scaffold project
3. Generate types (?)
4. Use the taquito plugin to originate contract
5. Fetch contract from the network

AC: A quick test that can replace running all e2e tests in CI to reduce time and effort.
In this case, e2e tests will run as part of the release only or locally.

**Comment by hu3man** [comment]
Would it be possible to test against new versions of node/docker with this test or would that be out of scope?

So far, all 3 of our Demo users had environment issues relating to node/docker/cli config so it would be helpful to catch any new issues that might be introduced by recent updates to dependencies
