### ISSUE TITLE
[Bug]: If elevated privileges are required for `docker run `, Taqueria commands fail in an ugly way

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#647]
### What happened?

When doing a product demo with Edmond, we ran into some ugly and uninformative errors when running any task that required executing a Docker command

The issue was that due to his local configuration, docker required elevated privileges. This resulted in the Taqueria task failing with an un-informative error

All Taqueria `taq` commands needed to be prefixed with `sudo` to work correctly

### What should have happened?

A friendly message that Docker had failed / couldn't connect to docker / etc

### Steps to reproduce the bug

Contact Edmond for the particulars of his environment

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@mweichert ping!
