### ISSUE TITLE
[Bug]: Running `taq originate` with an empty `/artifacts` folder does not provide an error message

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#653]
### What happened?

Details about what happened.

### What should have happened?

Running `taq originate` with an empty artifact directory does not provide any user output

### Steps to reproduce the bug

Steps to reproduce the error

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@hu3man, can this be closed:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/7251388/167898803-b707c5c4-a078-4cb8-8fc3-d300a8804b0c.png">

**Comment by hu3man** [comment]
Yep!

Closing: issue resolved
