### ISSUE TITLE
[Feature]: Add network/env from CLI

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#656]
### Describe the feature you would like

Taqueria should provide a task that helps the user set up a new network/env. It would be a command like `taq add environment` or `taq add network`. This task would pull a list of current networks from teztnets.xyz, allow the user to select a network, ask if the user would like their implicit accounts created for the network, then provide a link to the faucet page, and then prompt the user to paste the facuet file in

The user flow would be similar to:
- select the network you want to add
- would you like to create your implicit accounts on this network
- what would you like to name your environment
- paste your faucet file here
- Success, connected to xyz network
- would you like to make this your default network?

What things occur under the hood:
- a new network created in config
- a new named environment created
- the new network added to that new environment
- global implicit accounts created on the network, added to config, and funded from faucet
- default env updated

### Is this feature solving a problem?

It's currently difficult and error prone to manually set up new networks/environments/accounts/faucet/etc

### Please share any additional details you have?

This supports and is related to #549 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zamrokk** [comment]
"global implicit accounts created on the network, added to config, and funded from faucet"  <= why not create just an alias user passed as argument to taq CLI ?   (like tezos-client does it from a faucet JSON file)
