### ISSUE TITLE
[Feature]: Let users know there is a new version of Taqueria available

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#657]
### Describe the feature you would like

Details about the feature request

### Is this feature solving a problem?

Details about the problem your feature solves

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Ready for planning

**Comment by hu3man** [comment]
handling in #1165
