### ISSUE TITLE
As an SRE, I want to be able to execute against Taqueria running in a container so that I can improve efficiency by integrating Taqueria into my CI/CD process

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#660]
Implementation:

Docker image

**Comment by GImbrailo** [comment]
The [Dockerfile](https://github.com/ecadlabs/taqueria-github-action/blob/main/Dockerfile) is complete and functional. It might change again slightly at a later stage if the github action becomes more complex.

**Comment by hu3man** [comment]
This looks good to me, is there a need for more review or can we close this?

**Comment by russellmorton** [comment]
@jchenche please will you review this and provide an approval here?

**Comment by jchenche** [comment]
@russellmorton Disclaimer: not very fluent with Docker image 😅 but it looks good to me!
