### ISSUE TITLE
Wireframe for mainnet operation signing

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#669]

**Comment by hu3man** [comment]
@russellmorton , is this the ticket for the UX mock-up for signing mainnet transactions, or something different?

**Comment by russellmorton** [comment]
@hu3man, yes this is the ticket for the wireframe.

Draft here: https://lucid.app/lucidchart/96a1a8ab-da17-426f-9848-37de65614e38/edit?page=0_0&invitationId=inv_46688bf1-919a-442a-bbc3-1415a5085e55#

Note that there are three pages.
