### ISSUE TITLE
[Bug]: Originating to a sandbox before it has been started in a new project results in a config error

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#670]
### What happened?

While running `taq originate` on a new project, the command fails if the sandbox is already running (started from a different project) with a configuration error

The root cause of this is that `config.json` does not have keys for each sandbox account until the sandbox is started. Since it was started by another project, the existing error handling does not handle this case gracefully

### What should have happened?

A better error message at a minimum, ideally would detect the lack of keys and instantiate the accounts implicitly

### Steps to reproduce the bug

1. In Project 1, run `taq start sandbox local`
2. Initialize Project 2 (`taq init`): add a `.tz` contact to `/artifacts` and install Taquito plugin
3. From Project 2, run `taq originate`
4. See error output

### Relevant log output

```shell
taqueria-scaffold-demo on  main 
❯ taq originate -e all
{
  errCode: 'E_INVALID_SANDBOX_ACCOUNT',
  errMsg: 'Please configure a default account for the local to be used for origination.',
  context: {
    accounts: {
      default: 'bob',
      bob: [Object],
      alice: [Object],
      john: [Object],
      jane: [Object],
      joe: [Object]
    },
    label: 'Local Tezos Sandbox',
    protocol: 'PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx',
    rpcUrl: 'http://localhost:20000'
  }
}
```

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jchenche** [comment]
```
No accounts are available for the sandbox called local to perform origination.
No contracts originated.
```

Got the above instead (on main branch). Means it might be already fixed? @hu3man
