### ISSUE TITLE
[Bug]: Taquito plugin throwing error when network rpc url invalid

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#673]
### What happened?

Tried originating to http://invalid.test which threw an error:
```
HttpRequestFailed: Error: getaddrinfo ENOTFOUND invalid.test
```

### What should have happened?

We should capture the HttpRequestFailed error and show a human-friendly message, "There was a problem communicating with invalid.test".

### Steps to reproduce the bug

Set the url of your testnet to something invalid. Then try originating a contract.

### Relevant log output

```shell
HttpRequestFailed: Error: getaddrinfo ENOTFOUND invalid.test
```
```


### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Note, the following E2E test is skipped till this is fixed:
> Verify that taqueria taquito plugin will show proper error when faucet is wrong -> network url is wrong

**Comment by jchenche** [comment]
It failed at line 132 (`const op = await batch.send();`) of `originate.ts` from the Taquito plugin.
With wrong rpcUrl, the error I get is
