### ISSUE TITLE
Add automated tests for flextesa plugin commands for VS Code Extension

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#686]
As an SDET, I want to add tests to verify that the next CLI commands can run from VS Code command palette.

@command:taqueria.install @taqueria/plugin-flextesa
@command:taqueria.start_sandbox
@command:taqueria.list_accounts
@command:taqueria.stop_sandbox

**Comment by hu3man** [comment]
@michaelkernaghan for context

**Comment by michaelkernaghan** [comment]
dupe of #1650
