### ISSUE TITLE
Add automated tests for SmartPy Plugin commands for VS Code Extension

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#687]
As an SDET, I want to add tests to verify that the next CLI commands can run from VS Code command palette:
@command:taqueria.install @taqueria/plugin-smartpy
@command:taqueria.compile_smartpy

**Comment by hu3man** [comment]
@michaelkernaghan for context

**Comment by michaelkernaghan** [comment]
dupe of #1650
