### ISSUE TITLE
[Bug]: Small issues/questions with the website documentation

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#691]
### What happened?

I was going through the website documentation to see what our users would see and came up with the following list of things that could be changed/questions I have. Sorry for the formatting:

Main page:

- [x] Quickstart on the home page footer link goes to introduction instead of the quickstart guide.
- [x] Two links to github in the bottom part of the footer on the main page. Should one be removed?

Introduction page:

- [x] No reference to the archetype or tezos client plugins on the intro page https://taqueria.io/docs/intro/#taqueria-plugins
- [x] Non-capitalized 'cli' when all other places reference it as "CLI" https://taqueria.io/docs/intro/#taqueria-sdk
- [x] We are inconsistent with the use of TS types plugin and contract types plugin 

Understanding plugins page
- [x] (Jev mentioned this before the teztalk) Archetype plugin not listed in plugin table https://taqueria.io/docs/getting-started/plugin-basics/#available-plugins

Quickstart page:
- [x] Note has spelling of 'whether' as 'wether' https://taqueria.io/docs/getting-started/plugin-basics/#available-plugins
- [x] Working with plugins section has code formatting as `taq install command` when it should probably read "`taq install` command" https://taqueria.io/docs/getting-started/quickstart/#working-with-plugins

Networks page:
- [x] Since hangzhounet is no longer the default should we change the default protocol in our config.json to use "protocol": "Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A" instead of "protocol": "PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx" https://taqueria.io/docs/getting-started/networks/#configuration

Flextesa plugin page:
- [x] Accounts sections has a code formatted section with no closing backtick "`accountName : { initialBalance: '3000000000'}" https://taqueria.io/docs/plugins/plugin-flextesa/#accounts 
- [x] Protocol section has no closing quote in section header
- [x] Protocol for Ithaca is "Ithica2", probably should be changed
- [ ] Are the 'start/stop flextesa' command actual aliases? It works but isn't available in the CLI help documentation HTTPs://taqueria.io/docs/plugins/plugin-flextesa/#flextesa-plugin-task-registry

Smartpy plugin page:
- [ ] The smartpy plugin currently comes with the teapot task but that isn't mentioned in the docs. Should we remove the teapot? https://taqueria.io/docs/plugins/plugin-smartpy/#plugin-architecture

Contract types plugin:
- [x] The aliases listed are not what is available in the CLI help for the type generation plugin. The website doc specifies the aliases "gen types" and "genTypes" while the cli help command specifies "[aliases: gen, gentypes] https://taqueria.io/docs/plugins/plugin-typescript-generator/#cli-aliases

Contribute to taqueria page:
- [x] Funky formatting for repo, issues and discussion links https://taqueria.io/docs/taqueria-dev/contributions/

### What should have happened?

Details about what should have happened.

### Steps to reproduce the bug

Go to the listed pages

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Thanks for putting this together @alexzbusko!

Fixed everything except for the following:

-Are the 'start/stop flextesa' command actual aliases? It works but isn't available in the CLI help documentation https://taqueria.io/docs/plugins/plugin-flextesa/#flextesa-plugin-task-registry

They are actual aliases as defined in the Flextesa plugin `index.ts` file:
```
        Task.create({
            task: "start sandbox",
            command: "start sandbox [sandboxName]",
            aliases: ["start flextesa"],
            description: "Starts a flextesa sandbox",
            options: [],
            handler: 'proxy',
            positionals: [
                PositionalArg.create({
                    placeholder: "sandboxName",
                    description: "The name of the sandbox to start"
                })
            ]
        }),
        Task.create({
            task: "stop sandbox",
            command: "stop sandbox [sandboxName]",
            aliases: ["stop flextesa"],
            description: "Stops a flextesa sandbox",
            options: [],
            handler: 'proxy',
            positionals: [
                PositionalArg.create({
                    placeholder: "sandboxName",
                    description: "The name of the sandbox to stop"
                })
            ]
        }),
```

@russellmorton @mweichert, should we add these to the CLI help output?

-  The smartpy plugin currently comes with the teapot task but that isn't mentioned in the docs. Should we remove the teapot? https://taqueria.io/docs/plugins/plugin-smartpy/#plugin-architecture

I agree it should be removed from the SmartPy plugin but as @mweichert has mentioned, it's a really useful example for a plugin dev to see

Would it be appropriate to put it in the mock plugin? If not maybe we could create a demo plugin. What do you think?

**Comment by hu3man** [comment]
PR #692 is ready for review which implements the fixes above

**Comment by russellmorton** [comment]
Yes we should add the start/stop flextesa aliases to the help output.

Teapot should be removed and added to a mock plugin. Can the mock plugin serve as the demo plugin?

**Comment by hu3man** [comment]
@mweichert, where would I change the help output from?

Not sure about the mock plugin as it's used for testing but that would be ideal
