### ISSUE TITLE
[Bug]: cannot compile example.jsligo from scaffold repo

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#693]
### What happened?

I use vs code, and I am running "Taqueria : Compile Ligo" from the scaffold demo

I get this error

`An internal error ocurred. Please, contact the developers. (Sys_error "artifacts/example.tz: No such file or directory").`

### What should have happened?

compile ligo and add tz file to artifacts folder

### Steps to reproduce the bug

as above

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sinapsist** [comment]
@zamrokk, do you have docker running on your machine? Also, can you please provide a terminal log to see the taqueria response (if possible)?

**Comment by zamrokk** [comment]
yes , I have Docker running but I don't see the purpose ?

btw, if I create the folder manually myself, then the file is generated.
I think is just a bug on the script , not checking if folder was existing or not and forget to create it if not

**Comment by sinapsist** [comment]
Ligo plugin also use dockerized version to execute compile command. But you're right. It should not be critical in this case. Because it runs the command, it just cannot find the file for some reason. Let me try to repro on my side.

**Comment by hu3man** [comment]
Hi @zamrokk, 

Thanks for reaching out about this, I'm to help troubleshoot this with you

It sounds like you may still need to run the setup steps on your project after scaffolding to install NPM dependencies and initialize the project with Taqueria 

If this is the case, you can follow these steps which are also found in the `readme.md` files:

For the [taqueria-scaffold-quickstart](https://github.com/ecadlabs/taqueria-scaffold-quickstart) project, run the following setup script from the project root:
```
npm run setup
```

For the [taqueria-scaffold-demo](https://github.com/ecadlabs/taqueria-scaffold-demo) project, run the following two commands:
```
npm install
```
```
taq init
```

If you have already completed the setup steps and are still experiencing errors, please ensure that you have the minimum requirements installed on your machine:
- Node.js v16 or later
- Docker v0.8 or later (with the daemon running)

Then provide details on the following (and any other relevant log output or screenshots) to help us investigate the issue:
- Your operating system and version
- The output of: `taq --version`
- The output of : `npm version`
- The output of : `docker -v`
- The output of: `uname -p`

Let me know how that goes!
Houston

**Comment by zamrokk** [comment]
I think the taq init is the one that is creating the artifacts folder
