### ISSUE TITLE
[Bug]: taq start sandbox local    just does not start or I need to wait for how long ..?

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#694]
### What happened?

I have the plugin flextesa installed but when I run

`taq start sandbox local`

nothing starts, even after a while   :'(

### What should have happened?

New context should bootstrap

### Steps to reproduce the bug

use the taq scaffold on the demo scaffold and then run  `taq start sandbox local`

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sinapsist** [comment]
@zamrokk Could you please, check if docker is running on your machine. Some of the plugins rely on it to run plugin docker. Thank you!

**Comment by zamrokk** [comment]
Docker was running. I am using WSL2 with Ubuntu

**Comment by sinapsist** [comment]
@zamrokk Would it be possible to ask you to provide terminal logs? But run t`aq --version` and` taq --help` first and then `taq start sandbox local`

**Comment by zamrokk** [comment]
taq --version
`v0.3.0
`
taq --help
```
taq <command>

Commands:
  taq init [projectDir]                     Initialize a new project
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold
  taq install <pluginName>                  Install a plugin
  taq uninstall <pluginName>                Uninstall a plugin
  taq compile [sourceFile]                  Compile a smart contract written in
                                            a Ligo syntax to Michelson code
                                                      [aliases: c, compile-ligo]
  taq typecheck [sourceFiles...]            Typecheck Michelson contracts
                                                                   [aliases: tc]
  taq simulate <sourceFile> <input>         Run Michelson contracts as a simulat
                                            ion                   [aliases: sim]
  taq deploy [contract]                     Deploy a smart contract to a particu
                                            lar environment [aliases: originate]
  taq start sandbox [sandboxName]           Starts a flextesa sandbox
                                                                [aliases: start]
  taq stop sandbox [sandboxName]            Stops a flextesa sandbox
                                                                 [aliases: stop]
  taq list accounts <sandboxName>           List the balances of all sandbox acc
                                            ounts

Options:
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]
  -p, --projectDir  Path to your project directory               [default: "./"]
      --configDir   Config directory (default ./.taq)        [default: "./.taq"]
  -e, --env         Specify an environment configuration
      --help        Show help                                          [boolean]

Taqueria is currently in BETA. You've been warned. :)
```

Docker is running but I don't see any container running for a while ...

**Comment by sinapsist** [comment]
@zamrokk  Thank you so much! Let me check with the same configuration on my end.

**Comment by hu3man** [comment]
Hi @zamrokk,

Sorry to hear you are running into this second issue and thanks for taking the time to reach out and file a bug report!

While it can take a bit of time to start up the sandbox for the first time (as the docker image needs to be downloaded), it sounds like there is something more going on in your case 

WSL2 has posed some issues for users in the past if not set up correctly. Here are some common issues that may be helpful:
- Docker desktop (for Windows) needs to be installed and running 
- The Docker <> WSL2 integration needs to be turned on: [guide](https://code.visualstudio.com/blogs/2020/03/02/docker-in-wsl2)
- WSL2 often has an outdated version of node (v10.x). This needs to be updated to v16 or later
- If you have elevated security permissions configured, you may need to run taq commands with elevated privileges (`sudo taq`)

If none of the above was relevant/helpful, please provide the information I requested in your other issue, as well as the contents of the `package.json` file from your project and we can investigate further

Let me know how that goes,
Houston

**Comment by zamrokk** [comment]
I just retry same command today and I see the container running    o.O
also the sandbox can start and stop

No idea of the reason so

**Comment by hu3man** [comment]
Glad to hear it's working for you now @zamrokk

Please reach out if you run into any other issues, or if you have any feedback for the project

Take care,
Houston
