### ISSUE TITLE
Investigate an ability to use selenium webdriver

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#696]
As an SDET, I want to investigate the ability to use a webdriver-based framework to interact with VS Code to improve VS Code Extention testing.
The current approach relies on VS Code APIs and has limitations on how we can interact with VS Code.
On the other side VS Code is a web-based application wrapped in Electron:
<img width="1434" alt="VS Code with Chrome Debugger" src="https://user-images.githubusercontent.com/10706087/167179353-aa16f00e-d987-49a7-8723-41b817f0d45b.png">

And Selenium tooling can be used there.

Some tools that can be used:
https://github.com/redhat-developer/vscode-extension-tester
Webdriver.io framework with a plugin
https://webdriver.io/docs/wdio-vscode-service/
https://webdriver.io/docs/wdio-vscode-service/
https://webdriverio-community.github.io/wdio-vscode-service/classes/WindowControls.html#elem_

**Comment by hu3man** [comment]
Closing for now: alternative solution found

**Comment by hu3man** [comment]
@michaelkernaghan for context

**Comment by hu3man** [comment]
Agreed! Thanks @michaelkernaghan!
