### ISSUE TITLE
[Feature]: allow invocation of Michelson entrypoints with annotations

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#705]
### Describe the feature you would like

`taq simulate sample.tz 'Left (Left 3)' --storage 5` will invoke the entrypoint annotated with "decrement".

But we want to be able to do this instead: `taq simulate sample.tz '3' --storage 5 --entrypoint decrement`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
This will be a great improvement!

As annotations are optional, we should ensure that both annotations and Michelson expressions work for `taq simulate`
