### ISSUE TITLE
[Bug]: Output from contract types plugin is not coming as a single blob of text which causes e2e tests to fail on branch gino-env-option-for-docker-volumes

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#713]
### What happened?

The e2e tests for the contract types plugin is no longer outputting all the output for the generate types command. When running the command as a user in a shell things will work fine since it looks like the first line is output then there is a slight pause and the rest comes.

### What should have happened?

All the output should have been available from the command `taq generate types` that the automated tests run

### Steps to reproduce the bug

Steps to reproduce the error:
Run the command in the taqueria root folder after building/installing the project `npm run test:e2e -w tests taqueria-plugin-contract-types.spec.ts`

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@alexzbusko, is this still relavent?
