### ISSUE TITLE
[Bug]: taq errors if path in `atrifactsDir` does not exist

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taqueria#723]
### What happened?

I `taq init` a new project
I add a new contract to `contracts`
I compile the contract using `taq compile` (it succeeds)
I update the `atrifactsDir` to a new path, such as `app/src/artifacts`
I run `taq compile` which fails with the following error;

```
$ taq compile
 
An internal error ocurred. Please, contact the developers.
(Sys_error "app/src/artifacts/example.tz: No such file or directory").

┌────────────────┬──────────────┐
│ Contract       │ Artifact     │
├────────────────┼──────────────┤
│ example.jsligo │ Not compiled │
└────────────────┴──────────────┘
```

### What should have happened?

I would like to see the `taq` command create the directory that it is going to write the artifact to, instead of throwing an error.

Running `taq init` again will fix the issue, but I feel this is weird, because I already initilized my project, why do I have to init it again?

The error message `An internal error ocurred. Please, contact the developers.` doesn't seem  like an appropriate/actionable error message for this place.

### Steps to reproduce the bug

See above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Additionally, `taq init` should run `npm init -y` if there is no `package.json` file in the project dir

This is something all demo users have run into when running `taq install ...` on a freshly initialized project. They will see this error output:
```
❯ taq install ../taqueria/taqueria-plugin-flextesa
taq [command]

Commands:
  taq init [projectDir]                     Initialize a new project
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold

Options:
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]
  -p, --projectDir  Path to your project directory               [default: "./"]
      --configDir   Config directory (default ./.taq)        [default: "./.taq"]
  -e, --env         Specify an environment configuration

Taqueria is currently in BETA. You've been warned. :)

This project isn't a valid NPM project. Please run: npm init
```

**Comment by sinapsist** [comment]
Marked is minor
