### ISSUE TITLE
Create a mocking mechanism to VS Code Extension

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#733]
As a Developer, I want to add a mocking mechanism to VS Code Extension so SDET can use it to mock responses running a plugin command.
Use case:  Running taq init command inside VS Code opens the dialogue box to select the folder that the automation test cannot bypass.  Need a solution to return a different response (skip opening dialogue box) to be able to test it. As a result, the test will focus on verifying mocked responses.

**Comment by hu3man** [comment]
@michaelkernaghan for context
