### ISSUE TITLE
As an ECAD SDET, I want all automated tests to be re-enabled so that implementation errors can be caught early in the pipeline again

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#737]
I had to skip some tests that were failing due to the output of a command not matching what was expected. However, when I viewed the output of these commands manually, the output seems to match what was expected.

### e2e/taqueria-cli-scaffolding-init.spec.ts
- [x] > Verify that taq scaffold quickstart project cannot be injected into an existing directory
- [x] > Verify that taq scaffold returns an error with a bogus URL

### e2e/taqueria-plugin-contract-types.spec.ts
- [x] > Verify that taqueria contract types plugin can compile one contract and generate types
- [x] > Verify that taqueria contract types plugin allows for different types folder specification
- [x] > Verify that taqueria contract types plugin can compile multiple contracts and generate types

*NOTE* - the above tests seem to be failing because stdout contains a single line of output versus multiple lines. Its as if stdout is being truncated, because if you run the same command locally you see the full output as expected.

### e2e/taqueria-plugin-flextesa.spec.ts
- [x] > Verify that taqueria flextesa plugin can start and stop a custom name sandbox
- [x] > Verify that taqueria flextesa plugin can start and stop a default sandbox without specifying name
- [x] > Verify that taqueria flextesa plugin will return "The local sandbox was not running." if user tries to call stop on sandbox that is not running

*NOTE* - like in _e2e/taqueria-plugin-contract-types.spec.ts_, the above tests seem to be failing because stdout contains a single line of output versus multiple lines. Its as if stdout is being truncated, because if you run the same command locally you see the full output as expected.

**Comment by russellmorton** [comment]
@sinapsist @alexzbusko who will be re-enabling these and what is the timeline for this? Should this be bumped to the next sprint?

**Comment by alexzbusko** [comment]
@russellmorton sorry for the last reply. Ivan and I have split these up and are working on them now. I think this should be bumped to the next sprint

**Comment by mweichert** [comment]
FYI, I've re-enabled the flextesa tests in 623-origination-operation

**Comment by alexzbusko** [comment]
@hu3man @sinapsist I have reenabled the tests, fixed the existing issues with the jest plugin release stuff and disabled the scaffolding tests for Houston's pending changes to all scaffolds. Closing this

**Comment by hu3man** [comment]
Awesome, thanks for getting this over the finish line this week @alexzbusko!
