### ISSUE TITLE
[Bug]: Website footer bullet points

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#738]
### What happened?

It appears that after Docusaurus was updated to v20, the styling on the footer was affected.

### What should have happened?

There should be no bullet points in the footer.

### Steps to reproduce the bug

- Go to taqueria.io
- Scroll to the bottom of the page

### Screenshots and images

Screenshot and images
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7251388/169580109-988c0209-15f0-4770-893c-c585919c5ce1.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
I spent quite a bit of time yesterday trying to add a `list-style: none` to the stylesheet for the docusaurus config but couldn't get it to remove the bullet points. Not sure if the style is overloaded by another stylesheet or something else

@HamidGoudarzi1988, do you have any idea as to where we would set this style?

**Comment by HamidGoudarzi1988** [comment]
Hi @hu3man , exactly true just need to select the items which are ".footer-items", could you please take a look at this pr:

[](https://github.com/ecadlabs/taqueria/pull/739)

and let me know if it needs more tweaks 

thanks

**Comment by hu3man** [comment]
Works great, thanks so much for hopping on this right away @HamidGoudarzi1988!
