### ISSUE TITLE
Refactor vscode to use common types and errors from taqueria protocol 

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#742]
### Describe the feature you would like

In 620-operations, there was a large refactoring effort to reduce code duplication by having many of our custom defined concrete types moved to the taqueria-protocol package, which is shared between the taqueria-cli, taqueria-sdk, and too, the vscode extension. As such, we were able to remove a lot of duplication from the SDK and I suspect we can do the same with the vscode extension.

The 620-operations branch should be merged in some time tomorrow. I hold hold on working on this issue till that occurs. 

### Is this feature solving a problem?

Consistent parsing, validation, and error messaging.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing: complete
