### ISSUE TITLE
Type parsing should return Result type

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#78]
### Description

Many types are parsed and return either the valid type or undefined. Although this works, it's not ideal as any context is lost as to why parsing failed. Instead, a Result sum type should be returned with Left or Right representing the failure or success value.

#### Acceptance Criteria
- No type parsing returns undefined
- Error messages are propagated back to the CLI or VS Code

#### Additional Context and Related Items

Need to source the best Deno and Node package for a Result type. In the past I've used Purity TS: https://github.com/gigobyte/purify

**Comment by hu3man** [comment]
@mweichert , can you provide additional details on this ticket?
