### ISSUE TITLE
[Bug]: Mobile rendering issues

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#780]
### What happened?

When navigating to the documentation pages of Taqueria.io, the text does not render across the whole screen and is squashed to one side.

### What should have happened?

Content should use the full width of the screen to show content on mobile.

### Steps to reproduce the bug

Go to https://taqueria.io/docs/intro/ or any other documentation page on a mobile device.

### Screenshots and images

iOS:

![image (4)](https://user-images.githubusercontent.com/7251388/170793501-7f448e2d-63b7-4f5c-ace4-2f6c3cb41cd7.png)

Android:
![Screenshot_20220527-114208](https://user-images.githubusercontent.com/7251388/170793508-027eebc0-b7f3-4bbc-a2ea-071b62980246.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@HamidGoudarzi1988, will you be able to assist with this bug?

**Comment by HamidGoudarzi1988** [comment]
Hello @russellmorton, could please take a look at this pr [](https://github.com/ecadlabs/taqueria/pull/796)? seems some updates change the classNames and they have conflict sometimes, please let me know if anything else is needed
https://b3283ee6.taqueria.pages.dev/docs/intro/

**Comment by russellmorton** [comment]
Thanks, @HamidGoudarzi1988, looks good to me, just waiting on another review.

@hu3man could this be another thing from the Docusaurus updates?
