### ISSUE TITLE
[Feature]: Package proxying for deno.land, esm.sh etc.

### ISSUE THREAD

**Issue by GImbrailo** [ecadlabs/taqueria#781]
### Describe the feature you would like

When we are running multiple pipelines at the same time we have noticed that we can sometimes get 403 HTTP errors. We believe these to be because of too many requests to package repositories and CDNs blocking this traffic. One way around this could be to setup a local mirror or proxy and cache requests to these package repositories. @mweichert mentioned setting up a Varnish instance, or similar tool, in front of deno.land, esm.sh, skypack, and any others we might want. 

### Is this feature solving a problem?

Prevents our CI requests to package managers from potentially being blocked by CDNs because of too many requests.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GImbrailo** [comment]
@mweichert if you have anymore information on this could you please add it here. Also could you please add any acceptance criteria you might have for setting this up.

**Comment by hu3man** [comment]
First time I've heard of Verdaccio but it looks like a good fit!

**Comment by GImbrailo** [comment]
After some discussions with SRE and Michael I am looking at using CICD caching and `deno.lock` files
