### ISSUE TITLE
[Bug]: Archetype contracts not compiling

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#787]
### What happened?

Certain Arechetype contracts do not compile in Taqueria:

### Original Bug Report

```
Bob:~/taqueria/my-archetype-project$ taq compile --plugin archetype
 
File "contracts/escrowWithPenalty.arl", line 5, characters 8-9: Error (parsing)
  Error while analyzing a variable declaration or a variable declaration or a variable declaration or a variable declaration or a variable declaration or a variable declaration or a variable declaration or a variable declaration or a variable declaration or a variable declaration or a variable declaration or a variable declaration.
 
File "contracts/escrowBasic.arl", line 34, characters 10-11: Error (parsing)
  Error while analyzing a transition or a transition.
 
File "contracts/auctionZilliqa.arl", line 30, characters 0-6: Error (parsing)
  Error while analyzing a specification declaration.
```

┌───────────────────────┬──────────────┐
 │ Contract                                                                       │ Artifact
├───────────────────────┼──────────────┤
 │ auctionZilliqa.arl                                                           │ Not compiled │
├───────────────────────┼──────────────┤
 │ escrowBasic.arl                                                            │ Not compiled │
├───────────────────────┼──────────────┤
 │ escrowWithPenalty.arl                                                 │ Not compiled │
└───────────────────────┴──────────────┘

## Reproduced using escrow site from https://docs.archetype-lang.org/contract-library/

```
archetype escrow_basic

variable buyer : role  = @tz1KmuhR6P52hw6xs5P69BXJYAURaznhvN1k

variable seller : role = @tz1XJYAURaznhvN1khR6P52hw6xs5P691Kmu

variable oracle : role = @tz15P69BXJYAURaznhvN1k1KmuhR6P52hw6x

variable price : tez = 10tz

(* action deadline *)
variable deadline : date = 2019-06-01T00:00:00

(* state machine *)
states =
 | Created initial
 | Aborted   with { i1 : balance = 0tz; }
 | Confirmed with { i2 : balance = price; }
 | Canceled  with { i3 : balance = 0tz; }
 | Completed with { i4 : balance = 0tz; }

transition abort () {
  called by buyer or seller

  from Created
  to Aborted
}

transition confirm () {
  from Created
  to Confirmed when { balance = price }
}

transition[%onlyonce%] complete () {
  called by oracle

  from Confirmed
  to Completed when { now < deadline }
  with effect {
    transfer price to seller
  }
}

transition[%onlyonce%] cancel () {
  called by oracle

  from Confirmed
  to Canceled
  with effect {
    transfer price to buyer
  }
}

security {
  s1 : only_by_role (transfers, oracle)
}
```

```
❯ taq compile
 
File "contracts/escrow-basic.arl", line 34, characters 10-11: Error (parsing)
  Error while analyzing a transition or a transition.
┌──────────────────┬──────────────┐
│ Contract         │ Artifact     │
├──────────────────┼──────────────┤
│ escrow-basic.arl │ Not compiled │
└──────────────────┴──────────────┘```



### What should have happened?

All Archetype contracts should compile

### Steps to reproduce the bug

1. Install Taqueria
2. Initiate taq project
3. Install Arechetype plugin
5. Add contract to contracts folder
6. Run ```taq compile```

### Relevant log output

_No response_

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
After some investigation, I found that this problem exists when using the completium-cli directly to compile the escrow contract. As such, this doesn't appear to be a problem with the plugin but rather the contract or the completium-cli.

I've assigned this to you @russellmorton as I believe you were going to reach back out to their team and get their feedback. Feel free to assign back to me if there's any work necessary on my part. Thanks!

**Comment by russellmorton** [comment]
Thanks, @mweichert, I have raised this with Benoit from Archetype.

**Comment by rognierbenoit** [comment]
Hi @russellmorton ,

indeed this version of escrow is outdated and we will soon update the entire doc site; sorry for the inconvenience.

Here is a working version:
https://github.com/edukera/completium-dapp-escrow/blob/technical-guide/contract/escrow.arl
and a presentation
https://completium.com/docs/dapp-escrow
(the dapp is plugged to the old testnet and would need a fresh up)

don't hesitate if question.
