### ISSUE TITLE
[Feature]: allow specifying ligo version in config.json

### ISSUE THREAD

**Issue by mbodecek** [ecadlabs/taqueria#798]
### Describe the feature you would like

We would like to be able to configure a specific ligo version for consistency across builds (local and CI)

### Is this feature solving a problem?

This solves multiple problems:
- Currently we can't fix the version so we end up with different .tz outputs over time
- If someone already has a ligo docker image with the `next` label, it uses that instead of downloading the current image
- The `next` version of ligo refers to an unreleased build from master, it might not be entirely stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Handling in #1166
