### ISSUE TITLE
As a dev, I want to be able to adjust the gas limit for the origination operation so that I can deploy a contract that has a very large initial storage value

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#800]

**Comment by jchenche** [comment]
@hu3man I assume Taquito takes care of that for us. Since we can just `taq deploy` without a problem. Though I've only tried deploying to a sandbox and not sure if sandbox has gas limits. If it does, then gas is taken care of by Taquito for sure.

**Comment by hu3man** [comment]
This is an old ticket so I don't remember the specifics @jchenche 

I think it was maybe @ricklove who reported the issue (from the DCP mint I believe)

**Comment by ricklove** [comment]
Actually I haven't seen this again. If there is a use case where such a large storage is being deployed, it will likely require a custom script for deploying instead of using the taq command directly.

**Comment by hu3man** [comment]
Great, thanks for the context Rick

I'm going to close this now and we can revisit it if and when it resurfaces as an issue
