### ISSUE TITLE
Improve Granularity of Data Sent to GA by CLI

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#809]
## Acceptance Criteria

Must Have:
- [ ] A field sent on the taq_task_executed payload with the name of the task (needs to work with multi-word task names) - we need to have granular metrics in GA and Data Studio and using another tool like Jupityr is a non-starter at this point
- [ ] A boolean field on the taq_test_executed task that indicates if the task invocation was successful or not

Nice to haves:
- [ ] A field which indicates if a CLI task was invoked via VsCE (command pallet)
- [ ] An error event with a payload containing non-identifiable, error-related fields that could be used to group and sort errors by type/class, and frequency

**Comment by hu3man** [comment]
@jchenche, do you have a rough idea of the complexity/effort required for this?

**Comment by jchenche** [comment]
@hu3man other than ephemeral state, it might be pretty straightforward if we are using Google Analytics.

**Comment by hu3man** [comment]
Ya we can skip the ephemeral state for sure 😅

Is it something we could easily add to your current pr or should we schedule it separately?

**Comment by jchenche** [comment]
Hmm probably have to schedule it separately. It might be straightforward, or it might not 😅

**Comment by mweichert** [comment]
Done in https://github.com/ecadlabs/taqueria/pull/1741
