### ISSUE TITLE
[Bug]: `makePathToTaq()` from VSCode should be memoized

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#834]
### What happened?

When invoking a Taqueria task from VSCode, the `taq` binary will be invoked twice as confirmation (by passing `testFromVsCode`) that VSCode is using the right binary.

### What should have happened?

Should only invoke once.

### Steps to reproduce the bug

1. Debug VSCode by placing breakpoint at `makePathToTaq()`.
2. Use start sandbox from command palette.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sinapsist** [comment]
It has been fixed
