### ISSUE TITLE
[Feature]: Enable GA tracking for VsCE

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#836]
### Describe the feature you would like

Right now, GA tracking is only for Taq CLI. It's not available for Taq VSCode.

For the MVP will be tracking the number of times the extension is loaded per uid
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Blocked by task refactor

**Comment by jchenche** [comment]
@AlirezaHaghshenas can you paste the line to uncomment on the VSCode side to enable Google Analytics here?

**Comment by AlirezaHaghshenas** [comment]
@jchenche in `taqueria-vscode-extension/src/extension.ts`
```
	// await helper.watchGlobalSettings();
```
