### ISSUE TITLE
[Feature]: Update VS Code extension name and description

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#842]
### Describe the feature you would like

Extension name should change from taqueria -> Taqueria

Description should change to:

Build, test and deploy smart contracts and dapps on Tezos

### Is this feature solving a problem?

Details about the problem your feature solves

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Do you know how this is done? I don't see anything in the publish workflow so I'm assuming there's an admin panel or something to manage our listing

**Comment by russellmorton** [comment]
I don't know. @danielelisi did the initial setup, Dan can you help us out?
