### ISSUE TITLE
Cannot build vsix locally

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#846]
### What happened?

If our vscode extension is adjusted to use versions of NPM packages that aren't yet published on npmjs.com then we cannot build a vsix using the vsce tool:

```sh
npx vsce package --no-update-package-json --no-git-tag-version
```

Output:
> npm ERR! missing: @taqueria/protocol@^0.4.0, required by taqueria-vscode@0.4.0
> npm ERR! missing: comment-json@^4.1.1, required by taqueria-vscode@0.4.0
> npm ERR! missing: promise-memoize@^1.2.1, required by taqueria-vscode@0.4.0
> npm ERR! missing: rambda@^7.0.1, required by taqueria-vscode@0.4.0

This is an known issue with this tool:
https://github.com/microsoft/vscode-vsce/issues/203

### What should have happened?

We should be able to build a vsix file using the vsce tool. FYI, the `--no-dependencies` doesn't work either, as you just get a corrupt build.

I think we can probably fork the vsce tool to add support for npm linked packages.

### Steps to reproduce the bug

Checkout e3a100ba297ad3986bb778222d3728e7cc10fd44 and run `npx vsce package --no-update-package-json --no-git-tag-version` from the taqueria-vscode-extension directory.

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Fixed

**Comment by RedCMD** [comment]
how did you fix it @mweichert?
