### ISSUE TITLE
[Feature]: UI improvement on Google Analytics

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#869]
### Describe the feature you would like

From @hu3man in https://github.com/ecadlabs/taqueria/pull/831:

Two questions regarding UX/UI:

Would it be possible/easy to toggle the taq opt-in/out commands displayed in the taq --help list? For example only show `opt-out` when the user has already opted in and vice versa
Can we increase the width of the CLI output? It's starting to look a bit cramped...
```
❯ taq          
taq [command]

Commands:
  taq init [projectDir]                     Initialize a new project
  taq opt-in                                Opt-in to sharing anonymous usage an
                                            alytics
  taq opt-out                               Opt-out of sharing anonymous usage a
                                            nalytics
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold

Options:
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]
  -p, --projectDir  Path to your project directory               [default: "./"]
  -e, --env         Specify an environment configuration

Taqueria is currently in BETA. You've been warned. :)

Your config.json file is invalid
Help improve Taqueria by sharing anonymous usage statistics in accordance with the privacy policy? (Y/n) 
```

If the user is already opted-in, running `taq opt-in` should display: `you have already opted-in to sharing anonymous usage analytics` (and the opposite if the users opt-out when they are not opted-in)

### Is this feature solving a problem?

Nicer UI for Google Analytics

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@jchenche can this be closed?

**Comment by jchenche** [comment]
@russellmorton nothing is being done for this issue yet.

**Comment by jchenche** [comment]
@russellmorton But we can decide to close this since these UI improvements aren't crucial.
