### ISSUE TITLE
Limit the number of task outputs persisted

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#876]
We made an adjustment to save task outputs to the persistent state / state registry along with the output of operations. This was to solve an immediate need - have the ability to reference the contract address of the last origination.

Although I'd treat this as an experimental feature that could be dropped at some point, until the state API has been fully realized this is a good feature to offer in the midterm.

However, _all_ task outputs are persisted, meaning that the persistent state can grow large and quickly. What would be best is to add a configurable limit per task in terms of how many outputs are persisted.

I think the last 5 outputs is a reasonable default.

In the config file, the end-developer can adjust the default:

```json
"state": {
  "tasks": {
     "limit": 5,
     "originate": 10
  }
}
```

The above configuration would ensure that the last 5 outputs of any task are persisted, with the `originate` increased to the last 10 outputs.

**Comment by alexzbusko** [comment]
Currently seeing that plugins will overwrite other plugins information in the environment-state.json file (default configuration will give you a development-state.json file). Steps to reproduce:

1. Initialize a taqueria project
2. Install the ligo, taquito and flextesa plugins
3. Start a sandbox and copy a ligo contract into the project contracts folder
4. Compile the contract a few times
5. Open up the development-state.json file and see the compilation records multiple compile executions
6. Open up the config.json and add storage for the ligo contract you have
7. Deploy the contracts to the local sandbox
8. Open up the development-state.json file and see that the compile tasks have been erased
