### ISSUE TITLE
Refactor CI/CD pipeline to enable an agile release process

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#878]
As a Taqueria release eng, I want to be able to build and publish pre-release versions of releases automatically with an RC tag so that we can use an iterative approach to releases and reduce the time and bug risks involved with the current process

**Considerations**
- VsCE Marketplace releases are immutable. Pre-releases are done on odd minor versions and marked pre-release
- Pre-releases should have package.json's updated so that devDependencies and dependencies use pr versions of npm packages
- NPM packages should be released as `@next` for pre-releases and `@latest` for full release
- Semantic version bump vs manual versioning in tag/workflow
- Script for bumping versions?
- Taqueria protocol package WS issue (circular dependency issue)

**Ideal release process:**
1. Create an RC branch off main
2. Push an RC tag to the branch (ie. `v0.4.5-rc1)
3. A publish-pre-release workflow starts
4. Binaries, plugins, VSCE, and docker images are built
5. NPM packages are published as pre-releases using `npm version prerelease --preid=alpha`
6. Docker images are published (currently they don't seem to be for PR versions)
7. The VSCE is published as a pre-release version
8. Approval of release candidate -> merge PR to main
9. Push a release tag to main

Steps:
- Version bump script

**Comment by hu3man** [comment]
Note from VSCE regarding pre-release versioning: 
```VS Code will auto update extensions to the highest version available, so even if a user opted into a pre-release version and there is an extension release with a higher version, that user will be updated to the released version. Because of this we recommend that extensions use major.EVEN_NUMBER.patch for release versions and major.ODD_NUMBER.patch for pre-release versions. For example: 0.2.* for release and 0.3.* for pre-release.```

**Comment by hu3man** [comment]
Issue to solve:
SDK npm package is required by plugins which means pre-release tags won't work as the package.json files will be referring to a release numbering (without an rc tag postfix)

`npm link` command may be helpful:
https://docs.npmjs.com/cli/v8/commands/npm-link#description

**Comment by hu3man** [comment]
The other option is to re-write package.json inside the build using something along the lines of: 
```
cat taqueria-plugin-ligo/package.json | jq ".dependencies[] |= $PRERELEASE_VERSION" >package.json
```

While this isn't the cleanest approach, it may be the easiest to implement for now

**Comment by mweichert** [comment]
Release preparation steps:
0) `git checkout -b 0.13.0`
1) Bump version #s of all packages, `npm version -ws 0.13.0`
2) Bump version # of taqueria package `npm version 0.13.0`
3) Update version # for each taqueria-* dependency or devDependency in each package.json
4) Run `npm update` to ensure that package-lock.json is up-to-date
5) Add all changes to changeset, `git add .`
6) Commit, `git commit -m "Prepared release"
7) Push branch, `git push -u origin 0.13.0`
8) Tag, `git tag v0.13.0`
9) Push tags, `git push --tags`

**Comment by hu3man** [comment]
Done!
