### ISSUE TITLE
Add Taqueria Version to Website

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#879]
### Describe the feature you would like

We need to add a current version call out to the Taqueria website so that users can easily tell what the latest version of Taqueria is, similar to the way Taquito shows this:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/7251388/174860008-da98df27-a865-4acc-a862-2422f9252a70.png">

### Is this feature solving a problem?

Details about the problem your feature solves

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@russellmorton, Is a static label ok for now? (if so we can g2m quickly)

The menu option shown above is for versioned documentation but we are a ways off from being able to implement that

**Comment by russellmorton** [comment]
For now, just calling out the version with a static label is good.
