### ISSUE TITLE
Move tests for tezos-client plugin simulation from flextesa.spec to it is own tezos-client.simulation.spec.ts

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#885]
As an SDET I want to re-organize tezos-client plugin simulation tests to make them more visible and easier to debug.

AC: tezos-client plugin tests for simulation moved to it is own fole

**Comment by hu3man** [comment]
Hey @alexzbusko, I thought I saw a PR for this already. Is it done now?

**Comment by alexzbusko** [comment]
It is done now @hu3man, I am going to close this issue

**Comment by hu3man** [comment]
Great, thanks @alexzbusko!
