### ISSUE TITLE
Improve Ligo plugin tests

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#890]
As an SDET I want to add tests to ligo plugin tests to verify additional options (entrypoint, syntax, infer) so this functionality will be covered by auto-tests during regression.

Additional as part of the check need to clarify if the same tests need to be added for other plugins such as archetype and/or smartpy) and if not need to add a test to verify once the second plugin is added these options are disabled.

AC: Tests to cover additional options (entrypoint, syntax, infer) added to the suite

**Comment by hu3man** [comment]
Hey @sinapsist I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/sprint-board-627afc6dad61b0002007f424/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
