### ISSUE TITLE
[Feature]: ipfs-pinata Plugin

### ISSUE THREAD

**Issue by ricklove** [ecadlabs/taqueria#893]
## AC
- [x] Pin task implemented
- [x] Publish task implemented
- [ ] Automated test coverage
- [ ] Documentation
- [ ] Integration with CI/CD

### Describe the feature you would like

ipfs pinata plugin should support two tasks:

- ipfs publish file|directory
  - Upload and pin a file using pinata as the pinning service
- ipfs pin hash
  - Pin a file that is already available in the ipfs network (assuming pinata can access a node where the file is available)

It will use the Pinata api to implement these tasks, and use the config.json for storing any required api keys.

### Is this feature solving a problem?

Deploying any file to ipfs

### Please share any additional details you have?

This fulfills User Story: https://github.com/ecadlabs/taqueria/issues/771

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@ricklove, can you give a status update on this ticket and the plugin?

**Comment by ricklove** [comment]
@hu3man this PR should complete this: https://github.com/ecadlabs/taqueria/pull/1143

**Comment by ricklove** [comment]
@hu3man here is the PR for the tests: They require a pinataJwtToken env variable to run. So this will need to be added for CICD and I'm not sure how this should be handled for local test running on dev machines where the env variable won't exist.

https://github.com/ecadlabs/taqueria/pull/1144

**Comment by hu3man** [comment]
Awesome, thanks for the update @ricklove!

**Comment by hu3man** [comment]
@GImbrailo, can you please look into how we would integrate the jwt token into our ci?

**Comment by hu3man** [comment]
#1116 -> alex

**Comment by GImbrailo** [comment]
@hu3man where can I get the `jwt`?

**Comment by GImbrailo** [comment]
@hu3man I have added the JWT as a secret called `PINATA_JWT_TOKEN`

**Comment by hu3man** [comment]
Awesome, thanks @GImbrailo!

**Comment by hu3man** [comment]
Done!
