### ISSUE TITLE
[Feature]: nft-scaffold

### ISSUE THREAD

**Issue by ricklove** [ecadlabs/taqueria#894]
### Describe the feature you would like

Use the nft-scaffold as a full end-to-end demonstration of taqueria features:

- Provisioned Operations
- ligo plugin
- contract-types plugin
- ipfs-pinata plugin
- metadata plugin
- Scaffold Projects

### Use Case

The nft scaffold itself will fulfill the following use case:

- As an artist, I want to create an nft collection on tezos full of my own unique artwork. I also want a website where I can display and sell my artwork.

### Scaffold Features:

- To deploy collection

  - Add the collection description in the `art` directory: collection-metadata.json
  - Run `taq apply` to:
    - upload the collection-metadata to ipfs
    - originate the contract with the collection metadata hash
    - Possibly: If the collection-metadata.json changes - the contract might have a operator function to allow for changing the collection metadata (but not the token metadata)

- To add a new artwork item

  - Add the artwork image/video/file into the 'art' directory token0x.xyz
  - Add the artwork thumbnail image token0x-thumbnail.xyz
  - Add the artwork description metadata.json (description, attributes, etc)
  - Run `taq apply` to:
    - upload the new art files to ipfs
    - inject the art file hashses into the token0x-metadata.json and upload that to ipfs
    - mint the token in the deployed contract (providing the token0x-metadata.json ipfs hash)

- To sell an art item

  - Browse to the website and connect to your operator wallet
  - Next to any nft price, click edit to modify the sell price or pause/start selling
  
- The website can be hosted on any static site host (like netlify, etc.) or the react components can be added to an existing react site.

### Is this feature solving a problem?

Demonstrate taqueria end to end use case and provide a useful nft scaffold for artists.

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Related

- https://github.com/ecadlabs/taqueria/issues/768

**Comment by hu3man** [comment]
@sinapsist, can you do some manual testing of the nft-scaffold so we can close out this ticket?
