### ISSUE TITLE
[Bug]: Running `taq compile` from contracts folder says config file is invalid

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#895]
When inside the contracts directory in the Taqueria project and the `compile` task is run, Taqueria throws an error that the config file is invalid.

Taqueria tasks should work from anywhere in the project. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sinapsist** [comment]
<img width="616" alt="Compile in Contract folder Config issue" src="https://user-images.githubusercontent.com/10706087/180493331-8a6b9614-6a9c-4727-8a78-449eea7a90e9.png">

**Comment by hu3man** [comment]
@mweichert, please estimate this
