### ISSUE TITLE
[Bug]: Nested contracts and relative paths to contracts do not compile correctly

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#896]
### What happened?

When compiling a multifile smart contract 

1.  where files are nested inside additional directories in the contracts,

OR

2.  where the path to the files that make up the smart contract are relative paths,

do not compile.

### What should have happened?

Taqueria should traverse through the directories inside the contracts folder to locate the files relevant to the smart contract.

AND

Taqueria should compile multifile smart contracts that are referenced using a relative path

Reproduction Steps:

1. Have a multi-file smart contract
2. Have the main contract in the /contracts folder
3. Have the additional files in a folder inside the /contracts folder
4. Compile the multi-file contract

**Comment by sinapsist** [comment]
Should be fixed with the contract registry @sinapsist needs to find dev ticket and close the bug.

**Comment by hu3man** [comment]
Closing, fixed via contract registry work
