### ISSUE TITLE
As a plugin author, I would like to be able to register callbacks in a PluginJsonResponse

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#916]
### Describe the feature you would like

As a plugin author, I'd like the ability to provide a callback in my PluginJsonResponse to Taqueria. For instance, this could be the response from `taq create contract`:
```javascript
{
  render: 'none',
  data: ['hello.mligo'],
  callback: {
    id: 'registered_contract',
    action: 'call-task',
    params: {
      task: 'add-contract',
      sourceFile: 'hello.mligo'
    }
  } 
}
```

The callback data provides information to Taqueria to do the following:
1) Taqueria would normally process the response by outputting something on stdout. Instead, it would emit the `call-task` action with the provided `params`.
2) The action gets processed and produces an output
3) The output above is proxied back to the plugin with a `callback-response` included in the RequestArgs object, and set to `registered_contract`.
3) The response from the proxy request is handled like any other PluginJsonResponse

Implementing this has the following advantages:
- Plugin communication becomes bidirectional.
- Better separation of concerns - plugins can delegate to Taqueria when it needs to perform something like writing to a file.
- Writing new SDKs become more scalable, as functionality can be developed in the Taqueria CLI or another plugin, such as listing contracts, and then SDKs (and therefore plugins) can just query Taqueria for this information.
- A plugin can query Taqueria (and indirectly, other plugins)

Example use-cases:
- Call `add-contract` after someone creates a contract from a template
- We write a teztnets plugin which provides a list of networks to Taqueria. The taquito plugin can ask Taqueria for a list of networks it's aware of

### Is this feature solving a problem?

Yes. As hooks are going to be more work to implement, this is useful mechanism that will compliment hooks when they arrive and yet provide a means for us to implement https://github.com/ecadlabs/taqueria/issues/907

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Moving to productboard: https://ecadlabs.productboard.com/feature-board/5219572-taqueria-features/features/15009618/detail
