### ISSUE TITLE
Generated jest.config.js files use absolute paths

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#917]
### What happened?

Our jest plugin works by running tests from logical containers called _partitions_. These partitions are simply directories in your project that you designate as a partition by running:
`taq test -i [partition]`

For instance, if you were to run `taq test -i unit` it would create a directory in your project called _unit_.

In addition to creating the directory, it also does the following:
- Looks in your .taq directory, and checks if a jest.config.js file exists. If it doesn't exist, it creates one. This serves as the project-wide settings for Jest.
- After creating the partition directory, it creates a jest.config.js file in that directory, which extends the project-wide .taq/jest.config.js file.

A partition specific jest.config.js file looks like the following after generated:
```js

const parentConfig = require('/Users/mweichert/Projects/taqueria/test-project/.taq/jest.config.js')

module.exports = {
    ...parentConfig,
    roots: [
        "/Users/mweichert/Projects/taqueria/test-project/tests"
    ]
}
```

As you can see, any paths in that file are absolute paths. This is problem because it means that you cannot use this project on another computer, as the absolute path will probably not resolve.

The code for generating the contents of jest.config.js file is on _line 41_ of the _taqueria-plugin-jest/proxy.ts_ file:
```typescript
const toPartitionCfg = (partitionAbspath: SanitizedAbsPath.t, rootConfigAbsPath: SanitizedAbsPath.t) => `
const parentConfig = require('${rootConfigAbsPath}')

module.exports = {
    ...parentConfig,
    roots: [
        "${partitionAbspath}"
    ]
}
`;
```

The acceptance criteria for resolving this issue is the following:
- [ ] A partition's jest.config.js file should use relative paths, not absolute paths
- [ ] Our e2e/taqueria-plugin-jest.spec.ts file should be updated to expect relative paths in the partition's jest.config.js file (see lines 45-50).

### What should have happened?

The jest.config.js file shouldn't have file paths that might not resolve when running from another computer.

### Steps to reproduce the bug

1. Create the default test partition: `taq test -i`
2. Look at _tests/jest.config.js_ and notice how absolute paths are being used

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
One suggestion would be to adjust the toPartitionCfg function's parameters to be `SanitizedPath` types instead of `SanitizedAbsPath`. Then, before invoking toPartitionCfg with its arguments, process each argument using a function with converts an absolute path to a relative path.

**Comment by sinapsist** [comment]
It should be fixed. @sinapsist Please verify it.
