### ISSUE TITLE
[Bug]: Flextesa hangs on boot

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taqueria#928]
### What happened?

When trying to run a sandbox using `taq` by running;

```
taq start sandbox local --debug
```
It outputs:
```
Booting sandbox...
Configuring sandbox...
```

to the console, and just hangs there indefinitely. 

I managed to fish out the docker command from my process table (ps) that gets executed by the plugin. 

I removed the --detach flag and put in -it instead, to see what it is doing.
docker run --name taqueria-development-local --rm -it --platform linux/amd64 -p 20000:20000 -p 19229:9229 -v
 /home/jev/scratch/artdemo:/project -w /app ghcr.io/ecadlabs/taqueria-flextesa:v0.5.3-rc1-f03fcec node index.js --sandbox local

That errors out with this message;

```
SyntaxError: Unexpected token } in JSON at position 3756
    at parse (<anonymous>)
    at async create15 (/app/index.js:41490:21)
    at async /app/index.js:41513:25
```

IDK what causes that error, and that error doesn't seem to bubble up to that taq start sandbox local cli either, because that command just hangs indefinitely. 

### What should have happened?

`taq start sandbox local` should either start a sandbox, or display an actionable & informative error as to why it cannot start a sandbox.

### Steps to reproduce the bug

Be me.
Running on linux

run `taq scaffold https://github.com/ecadlabs/taqueria-scaffold-ligo test_project`

```
cd test_project
taq start sandbox local
```

See the output
```
Booting sandbox...
Configuring sandbox...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jevonearth** [comment]
Upon digging further, the root cause of this issue is a malformed `.taq/config.json` file. In my case, I had a trailing comma where it was not supposed to me.

This surfaces two issues.

- `.taq/config.json` should probably be validated at the start of a command, so such issues can be surfaced to the user as an infromative and actionable error message.
- The flextesa plugin was not able to handle the `SyntaxError: Unexpected token } in JSON at position 3756`... error, and instead of doing something, it hangs indefinitely.

**Comment by jchenche** [comment]
Maybe it's Linux specific? I followed the reproduction steps and everything works fine (Mac user here). I am on the `main` branch
