### ISSUE TITLE
[Bug]: Multiple minor bugs in CLI and in TVsCE

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#930]
### What happened?

- [ ] - `taq --plugin ligo compile -p folder` will fail if the current working path is different from the project directory
- [ ] - `taqueria: compile (ligo)` can show failure, while it has succeeded and compiler has only outputted warnings
- [x] - If `.taq` folder is deleted, command states don't get updated
- [x] - After opening an empty folder in TVsCE, errors will be shown in output:taqueria that can be confusing for the user
- [x] - If the TVsCE shows errors and then succeeds later, the user can still see the error in output:taqueria and not realize that things are fine now

### What should have happened?

Details about what should have happened.

### Steps to reproduce the bug

Steps to reproduce the error

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Hey @AlirezaHaghshenas I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/sprint-board-627afc6dad61b0002007f424/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by russellmorton** [comment]
@AlirezaHaghshenas what is the status of this ticket? Is there a branch associated?

**Comment by AlirezaHaghshenas** [comment]
fixed in: #972
