### ISSUE TITLE
As an end-developer, I would like the ability to provision tasks in a declarative way to populate the state registry for my project

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#935]
For #620, we need the ability to provision a task, which will add the task to the .taq/provisioners.ts file.

When the user runs `taq apply`, the provisions in the provisioners.ts file will be applied to update the state.

**Comment by hu3man** [comment]
Hey @mweichert I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/sprint-board-627afc6dad61b0002007f424/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
