### ISSUE TITLE
[Bug]: Initializing a taqueria project within a directory/subdirectory of a NPM project will not NPM initialize the taq project by default 

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#939]
### What happened?

When initializing a taqueria project within our project (for example within the tests/e2e directory) the package.json is not created (or it silently errors) within the taqueria project like it is in other directories that are not NPM projects (creating a NPM project in your ~/ directory)

### What should have happened?

What should have happened is the taqueria init step should have created a package.json file through initializing the npm project within the directory (tests/e2e) the same way that it does in other directories that are not NPM projects

### Steps to reproduce the bug

Steps to reproduce the error:

1. Make sure the taqueria binary is in your system path and can be called from anywhere
2. `taq init` a project within your home directory (not within the taqueria git project directory)
3. Verify that the initialized project has a package.json file without any further action on your part
4. `taq init` a project within the taqueria git project directory (for example in the tests/e2e directory)
5. Verify that the new taqueria project doesn't have a package.json file

### Relevant log output

```shell
alexander@alexander:~/taqueria$ cd taqueria-plugin-ligo/
alexander@alexander:~/taqueria/taqueria-plugin-ligo$ ll
total 72
drwxrwxr-x  2 alexander alexander  4096 Jun 30 16:14 ./
drwxrwxr-x 31 alexander alexander  4096 Jul  4 14:52 ../
-rw-rw-r--  1 alexander alexander  2995 Jun 24 15:12 compile.ts
-rw-rw-r--  1 alexander alexander  5477 Jun 30 16:14 index.js
-rw-rw-r--  1 alexander alexander  8884 Jun 30 16:14 index.js.map
-rw-rw-r--  1 alexander alexander  1191 Jun  9 16:29 index.ts
-rw-rw-r--  1 alexander alexander 11357 May 30 21:54 LICENSE
-rw-rw-r--  1 alexander alexander  1703 Jun 20 15:03 package.json
-rw-rw-r--  1 alexander alexander  2409 Jun 20 15:03 _readme.eta
-rw-rw-r--  1 alexander alexander  2334 Jun 30 15:04 README.md
-rw-rw-r--  1 alexander alexander 10573 Jun  9 16:29 tsconfig.json
alexander@alexander:~/taqueria/taqueria-plugin-ligo$ taq init alex-ligo
Project taq'ified!
alexander@alexander:~/taqueria/taqueria-plugin-ligo$ cd alex-ligo/
alexander@alexander:~/taqueria/taqueria-plugin-ligo/alex-ligo$ ll
total 32
drwxrwxr-x 5 alexander alexander  4096 Jul  4 15:14 ./
drwxrwxr-x 3 alexander alexander  4096 Jul  4 15:14 ../
drwxrwxr-x 2 alexander alexander  4096 Jul  4 15:14 artifacts/
drwxrwxr-x 2 alexander alexander  4096 Jul  4 15:14 contracts/
-rw-rw-r-- 1 alexander alexander 10703 Jul  4 15:14 quickstart.md
drwxrwxr-x 2 alexander alexander  4096 Jul  4 15:14 .taq/
```

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexzbusko** [comment]
@hu3man @russellmorton @mweichert @jchenche this is still happening on the main branch with the steps above

**Comment by mweichert** [comment]
@alexzbusko @hu3man @sinapsist FYI, I don't think this is a bug:

If you try running npm init in a workspace, no package.json file will be created. This is intentional by NPM.

However, you can nest NPM modules outside of a workspace:
- In the taqueria root, run `mkdir test && cd test && npm init -y`
- You can then create another nested module, `mkdir inner-test && cd inner-test && npm init -y`

As Taqueria just makes called to `npm init` under-the-hood, you'll find that Taqueria works as it should:
- In the taqueria root, run `taq init test && cd test`
- Assure that package.json exists: `find package.json`
- Create a nested taqueria project, `taq init inner && cd inner`
- Assure that package.json exists: `find package.json`
