### ISSUE TITLE
[Feature]: Add progress bar or seconds counter to docker downloads

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#941]
### Describe the feature you would like

When downloading docker images in Taqueria, it will be useful to show users either:

1. A progress bar related to the download progress
2. A timer showing how long the process has been running

### Is this feature solving a problem?

This will provide users with a more intuitive UX and allow them to understand that Taqueria is working in the background.

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Deprioritized
