### ISSUE TITLE
[Feature]: Add a task to check if a sandbox is running

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#954]
As a Taqueria User I want a command to check it a sandbox is running on my machine so that I know I know the status of Flextesa at any time.

We currently have no way to check whether a sandbox is already running using Taqueria except for a user to run `docker ps`.

There are two use cases for checking whether a sandbox is running:

- Is the sandbox running for my project?
- Is the sandbox running for a different project?

### Acceptance Criteria
- [ ] Task created for checking if there is a sanbox running e.g. `taq sandbox status` or `taq sandbox status local` - if this follows the way the sandbox is currently referenced, this would be `taq status sandbox`
- [ ] VS Code command palette has support for sandbox status
- [ ] VS Code UI shows sandbox and relevant project
- [ ] Output to the user for CLI and VS Code extension shows the status of a sandbox and if it is running the project it is running relative to as well as the environment it is running relative to (could have more than one sandbox in a project)

**Comment by mweichert** [comment]
@russellmorton I've added this to the sprint as it sounds like @AlirezaHaghshenas will be handling this as part of his vscode work.

**Comment by russellmorton** [comment]
@AlirezaHaghshenas do you want to have refinement on this?

**Comment by russellmorton** [comment]
@AlirezaHaghshenas FYI, I have updated the ticket.

**Comment by AlirezaHaghshenas** [comment]
Sorry for late reply to these messages.
I implemented a test that does not involve a `taq` CLI invocation.
The logic is hard-coded inside TVsCE.

**Comment by hu3man** [comment]
Closing: implemented in VsCE
