### ISSUE TITLE
[Bug]: /root/ligo: permission denied: unknown

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#956]
### What happened?

I have installed the v0.6.5 but I still have the error described by #870  

It was supposed to be merged on main 14 days ago, so before the v0.6.5  on July 1st

I use WSL2 Ubuntu

` taq compile
 
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/root/ligo": stat /root/ligo: permission denied: unknown.

┌─────────────────┬──────────────┐
│ Contract        │ Artifact     │
├─────────────────┼──────────────┤
│ pokeGame.jsligo │ Not compiled │
└─────────────────┴──────────────┘`

### What should have happened?

Details about what should have happened.

### Steps to reproduce the bug

use WSL2 , install ligo plugin and try to compile

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zamrokk** [comment]
Q : why docker and not installing the CLI directly ?

**Comment by russellmorton** [comment]
@AlirezaHaghshenas what is the status of this bug?

**Comment by russellmorton** [comment]
> Q : why docker and not installing the CLI directly ?

Taqueria is cross-platform and as LIGO is not supported on MacOS natively, we chose to implement the Docker solution across the application.

Adding support for native binaries is on the roadmap for future development.

**Comment by AlirezaHaghshenas** [comment]
@zamrokk Sorry for late reply,

The fix in #870 expects a newer version of Ligo image. The older one cannot be run as root and shows the error you have observed.

Deleting the Ligo image (or clearing image cache) will fix this problem.

**Comment by AlirezaHaghshenas** [comment]
@zamrokk Do you still have this problem? Or can we close this ticket?

**Comment by zamrokk** [comment]
yes, I can compile with last V0.12

btw, I still have some errros on the taqueria state :/

Le mar. 9 août 2022 à 01:02, AlirezaHaghshenas ***@***.***> a
écrit :

**Comment by zamrokk** [comment]
yes , I can compile with v0.12 now 

Thx

**Comment by AlirezaHaghshenas** [comment]
> btw, I still have some errros on the taqueria state :/ 
@zamrokk 
Can you share your errors, and some reproduction steps with us? Maybe in a separate ticket.

**Comment by zamrokk** [comment]
I did some config cleaning and use the vscode plugin, now the state seems
to be ok. I can do all actions
Don't know what happened

Ben

Le mar. 9 août 2022 à 20:52, AlirezaHaghshenas ***@***.***> a
écrit :
