### ISSUE TITLE
[Feature]: taq compile storage <MYFILE>.jsligo 'Set.empty as set<address>'

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#957]
### Describe the feature you would like

compile storage from jsligo expression to the config.json configuration for the contract <MYFILE>.jsligo
on config.json output could be javascript like today or michelson expression

### Is this feature solving a problem?

actual init storage require manual update and knowledge of taquito storage representation whereas we develop on jsligo , for example

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@zamrokk this is definitely something we want to add. Thank you for logging this feature request.

**Comment by zamrokk** [comment]
Even better, we could be able to compile a storage referencing an environment. Example :

in ligo , we have 
```
ligo compile storage ./contracts/pokeGame.jsligo 'Set.empty as set<address>' --output-file ./artifacts/pokeGameStorage.tz --protocol jakarta
```

in taqueria I would liek to have : 
```
taq compile storage pokeGame.jsligo 'Set.empty as set<address>' -e "development"
```

and it should produce on .taq/config.json file, the storage section below: 

``` 
"development": {
            "networks": [],
            "sandboxes": [
                "local"
            ],
            "storage": {
                "pokeGame.tz": []
            }
        },
```

taqueria will have to read the Michelson .tz output and transform it direclty to taquito javascript representation. It will be transparent to the user

**Comment by hu3man** [comment]
@mweichert @jchenche, thoughts on this? ^^

**Comment by jchenche** [comment]
@zamrokk https://github.com/ecadlabs/taqueria/issues/963 and an upcoming plan to include the compile expression and compile storage command/task will solve this.

**Comment by hu3man** [comment]
Closing for now
