### ISSUE TITLE
[Feature]: taq compile --protocol <PROTOCOL>

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#958]
### Describe the feature you would like

reuse ligo command line to specify a protocol version for the michelson output

### Is this feature solving a problem?

depending on ligo version, default protocol is not the same and can lead to mistakes

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
Thanks @zamrokk, I have added this to our backlog to be added to the LIGO plugin.

**Comment by hu3man** [comment]
@jchenche, make sure this makes it into the spec

**Comment by hu3man** [comment]
Handling in #1166
