### ISSUE TITLE
[Feature]: Fixed LIGO Versions

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#959]
### Describe the feature you would like

add a specific version of LIGO, not the latest that could be unstable

### Is this feature solving a problem?

lastest is often unstable, do not use it and specify a version of ligo

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
Similar to the request from Miro.

**Comment by jchenche** [comment]
@hu3man instead of having to specify the version in the command, I think we should use the latest stable version and fix the version in our code internally (and not use the latest tag).

**Comment by hu3man** [comment]
I agree we should have a stable version per release. I think we just need to make clear what version is being used, both in documentation, but maybe via a cli command as well

**Comment by zamrokk** [comment]
Normal developers require latest stable version

Experimental developers (like me) require next unstable version

**Comment by mweichert** [comment]
Closing as duplicate of #798
