### ISSUE TITLE
TASK: Automated VS Code Extension Publishing

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#97]
### Description
Create the CI/CD pipeline for building and deploying the VS Code extension to the marketplace.

#### Acceptance Criteria
- [ ] VS Code extension builds automatically as part of the Taqueria CI/CD
- [ ] VS Code extension is published automatically as part of the Taqueria CI/CD

#### Additional Context and Related Items
https://code.visualstudio.com/api/working-with-extensions/continuous-integration

**Comment by danielelisi** [comment]
This is done. The VSCode Extension pipeline is triggered whenever there are code changes inside `taqueria-vscode-extension` folder. The extension is published to the VS Code marketplace whenever we tag a commit with SemVer.

VS Code Marketplace link: https://marketplace.visualstudio.com/items?itemName=ecadlabs.taqueria

![Screenshot from 2022-01-26 12-25-06](https://user-images.githubusercontent.com/22307776/151244081-269e973b-de44-4ec3-9f6d-9c91753574af.png)
