### ISSUE TITLE
[Feature]: refactor all task names to use dash instead of spaces

### ISSUE THREAD

**Issue by jchenche** [ecadlabs/taqueria#976]
### Describe the feature you would like

E.g. `taq start sandbox local` will become `taq start-sandbox local`

This change affects all plugins, the CLI, VSCode extension, and e2e tests.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Implementing in: https://github.com/ecadlabs/taqueria/issues/1159
