### ISSUE TITLE
[Bug]: If you close a folder in vscode there is no option to initialize a project

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#978]
### What happened?

If you are working in a folder in vscode and then close the folder so there is no folder shown in the left file explorer if you try to initialize a project it will not allow you select the initialize project option from the command palette

### What should have happened?

@AlirezaHaghshenas and I discussed that the option to initialize the project should be present and open a dialogue to select the folder to initialize the taqueria project to. This may change after some discussion/investigation has been done but as of right now that is the solution we landed on. 

### Steps to reproduce the bug

Steps to reproduce the error:

1. Install/open the vscode extension 
2. Click File -> Close Folder in vscode
3. Open the command palette

You should see the "Taqueria: Initialize Project" command

### Screenshots and images

<img width="771" alt="image" src="https://user-images.githubusercontent.com/29528321/178825891-bc7e27c1-9ffc-4db1-8281-99a5c543bd18.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlirezaHaghshenas** [comment]
fixed in: #972
