### ISSUE TITLE
[Bug]: Ligo plugin in VSCode will show compilation successful message when no contracts are found

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#980]
### What happened?

When running the ligo compile command in the vscode extension if there are no ligo contracts in the contracts directory vscode will say the compilation was successful though the output tab specifies no contracts found

### What should have happened?

We should make the CLI and the extension behave in a similar way where it will send a notification that no contracts were found

### Steps to reproduce the bug

Steps to reproduce the error:

1. Initialize a taqueria project in vscode
2. Install the ligo plugin
3. Run the ligo compile command from the command palette

This should output "No contracts found" or something similar to the CLI output of:
```
┌────────────┬──────────┐
│ Contract                 │             Artifact │
├────────────┼──────────┤
│ None found           │              N/A      │
└────────────┴──────────┘
```

### Screenshots and images

Screenshot and images

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlirezaHaghshenas** [comment]
Now with the contract registry, seems to be working fine, shows a warning.
