### ISSUE TITLE
JSON bridge between CLI and TVsCE

### ISSUE THREAD

**Issue by MichalLytek** [ecadlabs/taqueria#987]
Reporter: @AlirezaHaghshenas 

> Currently, if you run a typecheck command and some contracts do not pass this test, the command will not exit with success exit code.
Now this is normal CLI convention. You might want other code to fail because of this. But on the TVsCE, it's not easy to determine when we have failed to run the command, vs when the command has been executed successfully but the result was a failure (like a contract's types are not consistent).
We can handle this in patches, but we need a general way to handle this.
Maybe to do this, you need to implement a taq invoke command that the CLI implements and is tailor-made for the TVsCE, a command that gets all its input from a JSON that's piped into its standard input from TVsCE, and returns everything as a JSON in standard output to TVsCE. (unless execution fails, where standard error is involved).
Maybe things can be simpler.
I think this is one area that having a solid design and implementation can make a big difference.
One thing to note (again) is that this TVsCE-CLI connection is as much about failure as it is about success.
Different modes of failure should be precisely separated: (I have two in mind now:)
The command failed to run, for some reason
The command ran, but its result was a failure.
But the border between these two is not clear, there's a spectrum.

The idea is to have a simpler API for executing Taqueria command and queries from the VSCode extension.
We can achieve that by using the JSON format, so we just pass the object and receive the object (or array).
We don't need to parse the args to CLI string, then format the data back (e.g. list accounts using ASCII table).

The first iteration could use a simple translation layer in the CLI, using the `invoke` command.
Later we can experiment and discuss a possibility to have JSON as the core communication approach and CLI being a presentation layer on top of that.

**Comment by MichalLytek** [comment]
Putting that on hold until we need that. #1002 should be sufficient for now :rocket:

**Comment by hu3man** [comment]
Closing for now
